### ISSUE TITLE
Object detection Using YOLOv5

### ISSUE THREAD

**Issue by SoyabulIslamLincoln** [prathimacode-hub/ML-ProjectKart#10]

**Comment by prathimacode-hub** [comment]
Can you elaborate the project and what it does? Also do mention the project title. @SoyabulIslamLincoln

**Comment by SoyabulIslamLincoln** [comment]
Yes, In this project I am going to use object detection model YOLOv5. This will be a real time object detection. There will be squared block and name of the object detected on running video like car, human, animals etc. 
The title will be- Real Time Object detection

**Comment by SoyabulIslamLincoln** [comment]
Additionally, adding user interface with the counting of detected objects

**Comment by prathimacode-hub** [comment]
That's great. Sounds interesting. I had assigned this issue to you. Go ahead. 👍@SoyabulIslamLincoln

**Comment by SoyabulIslamLincoln** [comment]
Thanks a lot @prathimacode-hub .

**Comment by SoyabulIslamLincoln** [comment]
Thanks a lot @prathimacode-hub .

**Comment by prathimacode-hub** [comment]
Why had you closed the issue? You should never close the issue from your end even if you raise a PR. Don't you want to work on this issue? @SoyabulIslamLincoln

**Comment by SoyabulIslamLincoln** [comment]
Yes yes. I thought chat was closed
I want to do the task

**Comment by SoyabulIslamLincoln** [comment]
It was a mistake from my side @prathimacode-hub . I want to complete the issue.

**Comment by prathimacode-hub** [comment]
Ok, sure. Assigned you back. @SoyabulIslamLincoln

**Comment by prathimacode-hub** [comment]
It's been long time you hadn't responded back? @SoyabulIslamLincoln

**Comment by prathimacode-hub** [comment]
This issue was assigned 20 days ago. That's completely a long time, if you don't respond within 2 days I have to get it assigned to someone else. @SoyabulIslamLincoln

**Comment by prathimacode-hub** [comment]
I had closed this issue. Your time is up.
