### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [prathimacode-hub/ML-ProjectKart#105]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@prathimacode-hub pls assign this issue to me.

**Comment by ishitakapoor26** [comment]
Like this
![score card](https://user-images.githubusercontent.com/78542333/122352250-93eafa80-cf6c-11eb-8fb7-c074b6c88c2e.PNG)

**Comment by prathimacode-hub** [comment]
I don't think it's necessary to add in image format. Because this repo, is not purely for LGMSOC participants. But it accepts other contributors as well. It can be added as text. If you could add it that way you're free to take up this issue. @ishitakapoor26

**Comment by ishitakapoor26** [comment]
> I don't think it's necessary to add in image format. Because this repo, is not purely for LGMSOC participants. But it accepts other contributors as well. It can be added as text. If you could add it that way you're free to take up this issue. @ishitakapoor26

@prathimacode-hub okay I'll add it as text.

**Comment by ishitakapoor26** [comment]
@prathimacode-hub pls assign it to me.

**Comment by prathimacode-hub** [comment]
Ok, this issue is assigned to you. @ishitakapoor26
