### ISSUE TITLE
Add links to the badges

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/ML-ProjectKart#108]
Title: Add links to the badges in main README.md file
Name: Umesh Singh
Label: Enhancement Request
Define You
- [x] LGM-SOC'21 Participant
- [ ] Contributor

Solution For Issue:
I will add links to the badges present in the readme (see the below image)

![image](https://user-images.githubusercontent.com/83420185/122393351-6add6080-cf92-11eb-8e01-d1e7f0b09893.png)

**To Do**
- [x] Add some links in the general badges like contributors, etc.
- [x] Add some links in the badges of PRs, Issues, Stars, etc.
- [x] align badges to the center

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can proceed on it. @Umesh-01
