### ISSUE TITLE
Medical Cost Analysis for Smokers and Non-smokers

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/ML-ProjectKart#114]
Hello admin, 
In this project I would like to use several machine learning models and also will do an Exploratory data analysis about both the nonsmokers and smokers and after that I will analyze both of the categories based on the features like,
1. gender wise analysis
2. Cost wise analysis
3. age distribution
4. 18+ years old smokers and their medicine charges
5. Smoker parents who have children in their home
6. Health effects on the children.

Now talking about the algorithms, the following algorithms will be used here,
1. Linear Regression
2. Polynomial Regression
3. Lasso and Ridge regression
4. Random forest regression
5. Decision Tree regression
6. SVM

Using these algorithms I will make a comparative analysis for all those algorithms and predict the average medical charges for the smokers as compared to the non-smokers. The comparative analysis will be based on the factor of Cross validation score.

Dataset collected from kaggle website named as [insurance.csv](https://www.kaggle.com/mirichoi0218/insurance?select=insurance.csv)

Please assign me this project work, I will contribute in this successfully.

**Comment by abhisheks008** [comment]
@prathimacode-hub Please look in to the issue that I have created and assign me this so that I can contribute. 😃

**Comment by prathimacode-hub** [comment]
That was a wonderful elaboration of your project. But kindly add up the template given to get issue assigned to you. And also what's the task you're taking up. Please, let me know. That's to know you as a LGMSOC participant. @abhisheks008

**Comment by abhisheks008** [comment]
Project name : Medical charges analysis for smokers and non-smokers using ML
[x] LGMSOC participant
Task taken : Developing the backend model of the project based on machine learning

Description of the project :
This project will provide the comparative feature analysis of the medical charges of the smokers and the non-smokers and will also predict the average medical charges for the smokers and non-smokers.

@prathimacode-hub may be this time it is eligible to be assigned.

**Comment by prathimacode-hub** [comment]
Obviously, this issue is assigned to you. You can start working on it. All the best. @abhisheks008

**Comment by abhisheks008** [comment]
Thanks a lot for this opportunity! 😄

**Comment by abhisheks008** [comment]
@prathimacode-hub in this project I will also add a prediction model which will predict the average medical charges for the smokers, so you can also add the label of model creation.

**Comment by prathimacode-hub** [comment]
That's great.
