### ISSUE TITLE
Speech Emotion Recognition

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#12]
Hey LGM-SoC participants, good to see you.

The speech emotion recognition system uses audio data to identify different emotions like happy, sad, surprised, angry etc

Dataset : https://www.kaggle.com/uwrfkaggler/ravdess-emotional-speech-audio

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Sumit11081996** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by sy07** [comment]
Hi mam, I would like to work on this issue as LGMSOC21 participant. Please assign me to this task if possible.

**Comment by prathimacode-hub** [comment]
Sure, but first let me know of the approach you're going to take. How would you proceed? What's the task you're taking?

**Comment by sy07** [comment]
I would like to build model for SER and i will use algorithms like SVM etc.

**Comment by prathimacode-hub** [comment]
That's cool. Use atleast 2 to 3 algorithms for good optimization @sy07
