### ISSUE TITLE
Movie Recommendation Systems

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#128]
Hey LGM-SoC participants, good to see you.

Movie Recommendation Systems helps you in recommending and predicting the movies you can watch based on your previously watched data.

Dataset : https://www.kaggle.com/rounakbanik/the-movies-dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Rutikab12** [comment]
Hey @prathimacode-hub, I want to work on this issue. First I will work on just model creation and then will try to move to frontend and backend if possible. I'll convey you in time. Assign me if possible.

**Comment by prathimacode-hub** [comment]
Definitely, this issue is assigned to you. You can start your work. Proceed. @Rutikab12

**Comment by Rutikab12** [comment]
> Definitely, this issue is assigned to you. You can start your work. Proceed. @Rutikab12

Thank You

**Comment by prathimacode-hub** [comment]
It's been long, no update from you yet. @Rutikab12

**Comment by Rutikab12** [comment]
> It's been long, no update from you yet. @Rutikab12

I am uploading it right now @prathimacode-hub .
