### ISSUE TITLE
Bird Species Classification and Recognition

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#129]
Hey LGM-SoC participants, good to see you.

This bird species recognition helps you in classifying and recognizing the species of the bird based on various scenarios into consideration. 

Dataset : https://www.kaggle.com/gpiosenka/100-bird-species

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by harshita9621** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Sure, @harshita9621. Kindly let me know of the approach you would follow and how would you proceed, task you would take up. @harshita9621

**Comment by harshita9621** [comment]
In this project I first go with the basic parts, such as input pipeline, compose the model and data augmentation . I will classify the images of bird by using transfer learning and I will follow the transfer learning and fine - tuning which is tensorflow for the project and I am beginner for computer vision so if you assigned me this then it will very helpful for me to learn about new thing.

**Comment by prathimacode-hub** [comment]
That's good to see your enthusiasm to learn. Sure, this issue is assigned to you. All the best for your learning journey. @harshita9621

**Comment by prathimacode-hub** [comment]
It's been long, no update from you yet. @harshita9621

**Comment by harshita9621** [comment]
@prathimacode-hub Working on this issue

**Comment by abhisheks008** [comment]
@prathimacode-hub It's being 8 days since @harshita9621 has updated. Can I work in this issue with your permission @prathimacode-hub ?

Approach : I'll be using the Convolution Neural Network to classify the birds from the dataset. To be precise I'll be using the ResNet101 architecture for this classification algorithm.
Task Taken : Classification  Model Creation
 
- [x] LGMSOC Participant

**Comment by harshita9621** [comment]
@abhisheks008 I am working on this issue.

**Comment by abhisheks008** [comment]
Yeah I know but this issue is assigned to you 14 days back and still you haven't progressed. Also the time provided for each issue is 7 days, that's why I have approached @prathimacode-hub. Hope you'll understand!

**Comment by prathimacode-hub** [comment]
@abhisheks008, The point you said is right, but @harshita9621 atleast replied to my message earlier. If she doesn't even consider to reply, I could have taken you in. Can't be harsh, if you have noticed I had unassigned 3 people from the tasks as they didn't update for 20long days. That's ok, lets give her time up to 4 days. I'm adding up new issues now for you.

@harshita9621, kindly respond timely as @abhisheks008 said, the time to create PR is 5 days and updation about your progress should be informed so that we know you're working on that issue. Else, we can only assume things. Hope you got my point.

**Comment by abhisheks008** [comment]
It's ok ma'am. No issues.
