### ISSUE TITLE
Credit Card Fraud Detection

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#13]
Hey LGM-SoC participants, good to see you.

This project detects for fraudelent or genuine with credit card transactions.

**Dataset** : https://www.kaggle.com/mlg-ulb/creditcardfraud

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub I would really like to work on 'Model Creation' for this issue as a LGM-SOC participant to detect the credit card frauds using different EDA approaches, deal with imbalance data and oversampling. Lastly, will be using hypertuned bagging(Decision Tree, Random forest) and boosting techniques (XG-Boost) to predict result and discover model accuracy. Please assign me this issue if possible. Thank you.

**Comment by prathimacode-hub** [comment]
Are you interested work on this issue? As you have expressed interest for multiple issues as well. But only 1 issue is assigned at a time @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
> Hey @prathimacode-hub I would really like to work on 'Model Creation' for this issue as a LGM-SOC participant to detect the credit card frauds using different EDA approaches, deal with imbalance data and oversampling. Lastly, will be using hypertuned bagging(Decision Tree, Random forest) and boosting techniques (XG-Boost) to predict result and discover model accuracy. Please assign me this issue if possible. Thank you.

I would like to work on this issue. Please assign me if possible @prathimacode-hub . Thank you.

**Comment by prathimacode-hub** [comment]
Yes, sure. This issue is assigned to you. Go ahead. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
Yeah I will work on 'Model Creation'. Will inform once I have created the PR.

**Comment by Soumayan-pal01** [comment]
I have created the PR @prathimacode-hub . Please review it. Thank you.
