### ISSUE TITLE
Bitcoin Price Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#130]
Hey LGM-SoC participants, good to see you.

This project should be able to help in predicting the bitcoin price based on the dataset provided.

Dataset : https://www.kaggle.com/vikramjeetsinghs/bitcoin-dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by shivani6320** [comment]
I would like to contribute. Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Sure, let me know your approach and algorithms you would take into consideration. The tasl you're going to take up? @shivani6320

**Comment by shivani6320** [comment]
I would explore data using EDA techniques and try to recognize patterns within data. Then I would use Regression techniques like Linear regression as well as advanced regression algorithms like Ridge & Lasso regression to predict the price if bitcoin. For this Project I would also like to compare regression techniques with neural networks also, for better model performance.

**Comment by prathimacode-hub** [comment]
That sounds cool. You can proceed with the issue, it's assigned to you. @shivani6320
