### ISSUE TITLE
Football Match Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#131]
Hey LGM-SoC participants, good to see you.

Using machine learning, we can predict the output of the football match by taking various factors into account.

Dataset : https://www.kaggle.com/ricardomoya/football-matches-of-spanish-league

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub , I am up for this issue and I want to contribute in this.

Name of the issue : Football Match Prediction
Issue #131

- [x] LGMSOC Participant

Approach : To make this prediction model, I would like to use various classifiers for fitting the model. Using various classifiers will provide us the opportunity to find out the best fit algorithm. The algorithms which I am going to use, Random forest classifer, Decision Tree classifier, KNN classifier, logistic regression, SDG classfier, Gausian NB.

Description : This project will predict the result of a football match using machine learning, by taking various factors into account.

Task Taken : Developing the Prediction model for this project.

Please assign me this issue.

**Comment by Manasi2001** [comment]
Sounds perfect @abhisheks008. Just make the changes in your PR first and then you may go ahead with this issue.
