### ISSUE TITLE
Yelp User Reviews

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#132]
Hey LGM-SoC participants, good to see you.

Through this project, we are building a recommender system using Yelp Dataset.

Dataset : https://www.kaggle.com/yelp-dataset/yelp-dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub , I am up for this issue and I want to contribute in this.

Name of the issue : Yelp User reviews
Issue #132

- [x] LGMSOC Participant

Approach : To make the recommendation system I would like to develop the machine learning models using the neural networks. But firstly, I will use KNN for classifying the data and then SVD and Keras will be used for developing the model for the recommendation system.

Description : This project will recommend the users that which restaurant is better for them depending on the user reviews provided in the past times.

Task Taken : Developing the Recommendation model for this project.

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can start working. All the best. @abhisheks008
