### ISSUE TITLE
Cotton Disease Prediction using DL

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#133]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Tasks:

* Uses Deep learning to detect diseases on cotton plants.
* I'm assuming to solve this using transfer learning.
* Dataset consists of Images of 3 different brands ( I'll give the dataset for download in a separate folder).
* Build an End to End Web-application with flask as backend.

So, I'll be going fullstack = model + backend + frontend 
Thanks

**Comment by prathimacode-hub** [comment]
That sounds pretty interesting. Sure, you can proceed with the issue. @NEERAJAP2001
