### ISSUE TITLE
Water Quality Prediction

### ISSUE THREAD

**Issue by Jagannath8** [prathimacode-hub/ML-ProjectKart#134]
Title: Water Quality Prediction
Objective: The main objective of this project is to predicting the water quality based on the dataset provided using machine learning algorithms.
Dataset: https://www.kaggle.com/adityakadiwal/water-potability
About: Create model
Label: Feature Request

**Comment by Jagannath8** [comment]
I will use multiple machine learning algorithms to compare the accuracy.
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Sure, you can work with the issue. Proceed. This issue is assigned to you. @Jagannath8

**Comment by Jagannath8** [comment]
> Sure, you can work with the issue. Proceed. This issue is assigned to you. What's the task you will be working? @Jagannath8

EDA and Model Creation
