### ISSUE TITLE
Age, Gender and Ethnicity Prediction

### ISSUE THREAD

**Issue by Anshal55** [prathimacode-hub/ML-ProjectKart#138]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

I am going to build 3 models for the prediction of Age, Gender and Ethnicity on the dataset https://www.kaggle.com/nipunarora8/age-gender-and-ethnicity-face-data-csv

I am working on model creation for now, would work on Back End after.

**Comment by Anshal55** [comment]
Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Ok, sure. First, let me know of your approach you're going to follow. @Anshal55

**Comment by Anshal55** [comment]
I'm planning to use functional deep learning model for the prediction part and use flask and heroku to deploy the models.

**Comment by prathimacode-hub** [comment]
Ok, sure. This issue is assigned to you. You can proceed. @Anshal55

**Comment by Anshal55** [comment]
Thanks @prathimacode-hub
