### ISSUE TITLE
Solar Eclipse Classification

### ISSUE THREAD

**Issue by Soumayan-pal01** [prathimacode-hub/ML-ProjectKart#142]
---
Title: Solar Eclipse Classification
About: To predict the different types of Solar Eclipse where P = Partial Eclipse, A = Annular Eclipse, T = Total Eclipse, H = Hybrid or Annular/Total Eclipse.
Name: Soumayan Pal
Label: Feature Request
Assignee: 'Soumayan-pal01'

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Yes I have discussed with the Project Admin**

**Proper Exploratory data anlysis and comparative analysis of multiple classification model(Logistic Regression, Random Forest, SVMs) to predict the type of Solar Eclipse**

**Classification of different types of Solar Eclipses**

**Logistic Regression, Random Forest, SVMs approaches**

**Comment by Soumayan-pal01** [comment]
I would like to work on 'Model Creation'

**Comment by prathimacode-hub** [comment]
Yes, you can go ahead. All the best. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
Thank you @prathimacode-hub . I will inform when I have created the PR.

**Comment by Soumayan-pal01** [comment]
I have created the PR @prathimacode-hub . Please review it. Thank you.
