### ISSUE TITLE
Stroke Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#145]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/fedesoriano/stroke-prediction-dataset) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by Manasi2001** [comment]
Sure @Jagannath8, but first please let me know what kind of analysis you're willing to perform, the algos which you'll be using and whether you'll be working on frontend/backend/model creation. Then, I'll assign it to you :)

**Comment by Jagannath8** [comment]
I will use multiple machine learning algorithms to create model and compare the accuracy.

**Comment by Manasi2001** [comment]
Okay, go ahead. 👍🏻
