### ISSUE TITLE
Mushroom Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#146]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/uciml/mushroom-classification) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001  , I am up for this issue and I want to contribute in this.

Name of the issue : Mushroom Classification
Issue #146

- [x] LGMSOC Participant

Approach : For this classification model I would like to use various classification models such as, KNN, SVM, Random Forest, Logistic Regression, Naive Bayes And after deploying the models I would like to make a comparison between them.

Description : This project is all about deploying classification algorithms and comparing the models.

Task Taken : Developing the Classification model for this project.

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Yup, this issue is assigned to you. You can start your work. @abhisheks008
