### ISSUE TITLE
Resume Categorizing

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#148]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/gauravduttakiit/resume-dataset) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001  , I am up for this issue and I want to contribute in this.

Name of the issue : Resume Categorizing
Issue #148

- [x] LGMSOC Participant

Approach : For this prediction model I would like to use KNN classifier, Naive Bayes classifier, DTC, RFC, SVM and also additionally I want use ANN on this dataset. 

Description : This project is all about deploying the Classification model.

Task Taken : Developing the Classification model for this project.

Please assign me this issue.

**Comment by Manasi2001** [comment]
Go ahead @abhisheks008. ✨
