### ISSUE TITLE
American Sign Language (ASL) Recognition

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#149]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/grassknoted/asl-alphabet) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by sai-keerthi** [comment]
I would like to compare all the algorithms in keras and choose the appropriate 3 algorithms based on the accuracy and train the data and compare the performance. 
can you please assign my this task.

**Comment by Manasi2001** [comment]
Sounds good @sai-keerthi! Go ahead. 👍🏻
Just for the confirmation, you'll be working on model creation only, right?

**Comment by sai-keerthi** [comment]
yes

**Comment by sai-keerthi** [comment]
I am sorry but I cannot complete this project . kindly excuse me.

**Comment by prathimacode-hub** [comment]
> I am sorry but I cannot complete this project . kindly excuse me.

Ok, no worries.

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub I would like to work on 'Model Creation' for this issue using Multi Layer Perceptron(MLP) approach and CNN approach. Please assign me this issue if possible. thank you.

**Comment by prathimacode-hub** [comment]
Issue assigned. Good selection. All the best. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
I have created the PR. Please review it @prathimacode-hub . Thank you.

**Comment by prathimacode-hub** [comment]
> I have created the PR. Please review it @prathimacode-hub . Thank you.

Done.
