### ISSUE TITLE
CAPTCHA Decoding

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#150]
Hey LGM-SOC participant, great to have you here! 😀
The aim is to decode the CAPTCHA images using AI. If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/fournierp/captcha-version-2-images) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhishek2chikun** [comment]
I would like to work on this issue under LSMSOC21, Please do assign me.
Thanks.

**Comment by Manasi2001** [comment]
Hey @abhishek2chikun you can surely work on this, but first please let me know your approach, how are you willing to go ahead with this and also whether you'll be working on model creation/backend/frontend. Then I'll assign it to you :)

**Comment by abhishek2chikun** [comment]
Hey @Manasi2001 , I would like to try different Deep Learning algorithms like NN, CNN and will be working on the complete cycle i.e. Model Creation to Deployment. Will be using Flask for the Backend and basic HTML/CSS for the frontend.

**Comment by Manasi2001** [comment]
Sounds awesome! Go ahead. 👍🏻

**Comment by prathimacode-hub** [comment]
It's been 11 days, no update from you yet. @abhishek2chikun

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using Convolution Neural Network for detecting the CAPTCHA letters, and the model will be evaluated according to the accuracy score.
Task taken : Model Creation
Issue #150

Please assign me this issue!

**Comment by prathimacode-hub** [comment]
Yes, issue assigned. @abhisheks008
