### ISSUE TITLE
LEGO Minifigures Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#151]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/ihelon/lego-minifigures-classification?select=jurassic-world) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Isha307** [comment]
Can I work on this issue??
The dataset contains a lot of pictures of various LEGO Minifigures, I can use this dataset for the image classification tasks and I will create a model and try to get accurate predictions for the test set.

**Comment by prathimacode-hub** [comment]
That sounds good, you can proceed. @Isha307
