### ISSUE TITLE
Cryotherapy Analysis

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#153]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/mmkvarma/cryotherapy-analysis) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001  , I am up for this issue and I want to contribute in this.

Name of the issue : Cryotherapy Analysis
Issue #153

- [x] LGMSOC Participant

Approach : For this analysisl I would like to use various classification models such as, Decision Tree classifier, Gausian NB, SVM, Random Forest, Logistic Regression, Adaboost, Gradient boosting. And after deploying the models I would like to make a comparison between them.

Description : This project is all about deploying classification algorithms and then make an analysis of them.

Task Taken : Developing the Classification model and provide the analysis for this project.

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Wow, good choice of project selection. Issue is assigned to you. @abhisheks008
