### ISSUE TITLE
Zoo Animal Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#154]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/uciml/zoo-animal-classification?select=class.csv) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by anishamurmu13** [comment]
Can I work on this issue.
I'm a participant of LGM-SOC21.
I'll use different ML algorithms to create models and compare their accuracy.

**Comment by prathimacode-hub** [comment]
Ok, you can go ahead. This issue is assigned to you. @anishamurmu13
