### ISSUE TITLE
Fashion MNIST Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#155]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/zalando-research/fashionmnist) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by psyduck1203** [comment]
Hey, Can I work on this issue?

**Comment by prathimacode-hub** [comment]
Yes, but let us know about ur approach, algos you would consider and how would you proceed. What's the task you would take up. @psyduck1203

**Comment by psyduck1203** [comment]
I have already worked on this project. I have used KNN, SVM, and logistic regression. I'll do Data pre-processing, Model Training, and Model Evaluation.

**Comment by prathimacode-hub** [comment]
Ok cool, this issue is assigned to you. @psyduck1203

**Comment by prathimacode-hub** [comment]
No update from your yet. @psyduck1203

**Comment by psyduck1203** [comment]
Almost done. Will open a PR by evening.
