### ISSUE TITLE
Dandelion Recognition

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#156]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/coloradokb/dandelionimages) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by rammya29** [comment]
Please assign this project to me.

**Comment by Manasi2001** [comment]
@rammya29 what type of analysis are you willing to perform? Also, let me know what all algorithms you're planning to use and whether you'll be working on frontend/backend/model creation. Then I'll assign it to you :)
And remember, you can work on only one issue at a time so choose accordingly. Whichever project you're interested in, give the above listed details for that and then get it assigned.

**Comment by abhisheks008** [comment]
@Manasi2001 and @prathimacode-hub I want to work in this project please assign me this issue.
I will Convolution Neural Network for creating the recognition model for this project.

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. @abhisheks008
