### ISSUE TITLE
Flowers Recognition

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#157]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/alxmamaev/flowers-recognition) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Anshal55** [comment]
Hey @Manasi2001 , I would like to work on this issue.

Name of the issue : Flowers Recognition


- [x]    LGMSOC Participant

Approach : For this I would like to use keras pre-trained model and transfer learning along with CNN model to make the predictions and use flask to deploy this.

Task  : Developing the Prediction model and Deployment.

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
That sounds good. Issue is assigned to you. @Anshal55
