### ISSUE TITLE
Rain Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#158]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/jsphyg/weather-dataset-rattle-package) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Isha307** [comment]
> Hey LGM-SOC participant, great to have you here! 😀
> If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/jsphyg/weather-dataset-rattle-package) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
> Happy coding :)

Can I work on this issue?
I will work on the model creation and will try different algorithm and use the best one that will predict next day Rain.

**Comment by prathimacode-hub** [comment]
Yes, you can work on it. This issue is assigned to you. You can proceed. @Isha307
