### ISSUE TITLE
Fresher's Salary Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#159]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/benroshan/factors-affecting-campus-placement) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by ritikkumar55** [comment]
> Hey LGM-SOC participant, great to have you here! 😀
> If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/benroshan/factors-affecting-campus-placement) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
> Happy coding :)

@Manasi2001 As a LGMSOC21 participants. I would like to work on this issue.

**Comment by Manasi2001** [comment]
@ritikkumar55 you can work on this but first let me know what all analysis you're willing to perform, the algos that you'll be using and what task you will be working on backend/frontend/model creation. Then I'll assign it to you :)

**Comment by ritikkumar55** [comment]
As it is an regression problem I will use data visualization to shows relations between columns, encoding categorical data, scaling numerical data if required, handle outliers and will use  Linear Regression
2. Decision Tree
3. Xgboost Regression
4. Lasso Regression
5. Random Forest
6. Ridge Regression
7. Elastic Net regression algorithms and will use streamlit to deploy this model.

**Comment by prathimacode-hub** [comment]
That's great. You can proceed, this issue is assigned to you. @ritikkumar55

**Comment by prathimacode-hub** [comment]
No update from you yet. @ritikkumar55

**Comment by ritikkumar55** [comment]
> No update from you yet. @ritikkumar55

Working on multipage function on streamlit one for prediction and another for data visualization and working on hyperparameter optimization of models . As a beginner I also have to spent  a lot of time on learning new topics which is yet untouched along with making this project that's why it  is taking  more time.

**Comment by prathimacode-hub** [comment]
> > No update from you yet. @ritikkumar55
> 
> Working on multipage function on streamlit one for prediction and another for data visualization and working on hyperparameter optimization of models . As a beginner I also have to spent a lot of time on learning new topics which is yet untouched along with making this project that's why it is taking more time.

I understand. No worries, but intimating timely would help me in understanding your progress. @ritikkumar55
