### ISSUE TITLE
Traffic Sign Classification

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#16]
Hey LGM-SoC participants, good to see you.

This project should help you in classifying it according to the traffic signs.

Dataset : https://www.kaggle.com/flo2607/traffic-signs-classification

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Isha307** [comment]
@prathimacode-hub Can you please assign this issue to me?

**Comment by Manasi2001** [comment]
You can surely work on this @Isha307. But first, please let me know what you are willing to work on, 'front-end', 'back-end' or 'model creation'. Also, what all algorithms you are planning to use and the analysis you'll be performing. Then, I'll assign it to you :)

**Comment by Isha307** [comment]
> You can surely work on this @Isha307. But first, please let me know what you are willing to work on, 'front-end', 'back-end' or 'model creation'. Also, what all algorithms you are planning to use and the analysis you'll be performing. Then, I'll assign it to you :)
I will work on model creation.
I saw the dataset and it has 43 classification and one data folder that contains all the images file so I am thinking to use CNN.

**Comment by prathimacode-hub** [comment]
Great, this issue is assigned to you. You can start working on it. All the best. 
@Isha307
