### ISSUE TITLE
Bird Species Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#160]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/gpiosenka/100-bird-species) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by prathimacode-hub** [comment]
Hey, this issue is already taken along with same dataset. Harshita is working on it. @Manasi2001

**Comment by Manasi2001** [comment]
Oops sorry. Closed 👍🏻

**Comment by prathimacode-hub** [comment]
That's fine, glad to see you add up multiple interesting issues on board. 👍
