### ISSUE TITLE
Natural Images Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#161]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/prasunroy/natural-images) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001  , I am up for this issue and I want to contribute in this.

Name of the issue : Natural Images Classification.

Issue #161

- [x] LGMSOC Participant

Approach : For this classification model, I would like to use Artificial Neural Network (ANN) and Convolution Neural Network (CNN). After deploying both the algorithms, the accuracy scores will be checked and based on that better model will be represented.

Description : This project is all about deploying the Classification model.

Task Taken : Developing the Classification model for this project using Neural Networks.

Please assign me this issue.

**Comment by Manasi2001** [comment]
Assigned @abhisheks008. 👍🏻
