### ISSUE TITLE
Fish Weight Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#162]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/aungpyaeap/fish-market) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by sy07** [comment]
Hi mam, I would like to work on this issue as LGMSOC21 participant. Please assign me to this task if possible.

**Comment by Manasi2001** [comment]
Hey @sy07, just do the changes in your PR first, then get this one assigned. 🙃

**Comment by sy07** [comment]
> Hey @sy07, just do the changes in your PR first, then get this one assigned. 🙃

Okay mam

**Comment by rammya29** [comment]
Can I work on this??

**Comment by rammya29** [comment]
I wish to work on this project.
I am LGM-SoC-21 Participant.
Here I wish to use Multiple Linear Regression to design a model.

**Comment by Manasi2001** [comment]
Okay @rammya29 go ahead. Although the issues are assigned on FCFS basis but as @sy07 is working on his older PR as of now, so you may proceed.
@sy07 no need to worry, I'll be opening plenty of new issues soon, you may grab them. Or if you feel like really working on this issue only, then let me know I'll keep it open and you may contribute as well, no problem.

**Comment by sy07** [comment]
> Okay @rammya29 go ahead. Although the issues are assigned on FCFS basis but as @sy07 is working on his older PR as of now, so you may proceed.
> @sy07 no need to worry, I'll be opening plenty of new issues soon, you may grab them. Or if you feel like really working on this issue only, then let me know I'll keep it open and you may contribute as well, no problem.

Thank you mam, but its okay i'll work on another issue.
