### ISSUE TITLE
Student Performance Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#163]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/larsen0966/student-performance-data-set) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by ayushi424** [comment]
Hey @Manasi2001 
I'd like to work on this issue, mainly on model creation part.
Firstly, I'll explore the data and find any missing or null values. If found then remove or replace them.
Then visualize the data to understand features and their relationships.
And then select features and train the models, lastly will check efficiency by error check and accuracy check.
Please assign.

**Comment by prathimacode-hub** [comment]
Yup, this issue is assigned to you. You can go ahead. @ayushi424
