### ISSUE TITLE
Hotel Rating Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#164]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/andrewmvd/trip-advisor-hotel-reviews) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001  , I am up for this issue and I want to contribute in this.

Name of the issue : Hotel Rating Prediction
Issue #164

- [x] LGMSOC Participant

Approach : For this prediction model I would like to use Random forest, decision tree, logistic regression, SVM, Gausian NB and some more algorithms. After that I'll evaluate them based on the accuracy scores.

Description : This project is all about deploying the prediction model for the Hotel rating system.

Task Taken : Developing the Prediction model for this project.

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
That sounds good, issue is assigned. All the best. @abhisheks008
