### ISSUE TITLE
Fake News Detection

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#17]
Hey LGM-SoC participants, good to see you.

This project detects to identify whether the news is real or fake.

**Dataset** :  https://www.kaggle.com/c/fake-news/data

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by theanshulcode** [comment]
Please assign this task @prathimacode-hub

**Comment by sy07** [comment]
Hi mam, I would like to work on this issue as LGM-SOC'21 participant from June 10. Do assign me this task if possible.
Thank You!

**Comment by prathimacode-hub** [comment]
Express the interest on the project you want to work. As i can assign only 1 issue at a time. @sy07

**Comment by jayant766** [comment]
please assign it to me under LGM-SOC'21

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub  I would really like to work on 'Model Creation' for this issue as a LGM-SOC participant to detect the Fake News using NLP and LTSM approaches. Please assign me this issue if possible. Thank you.

**Comment by prathimacode-hub** [comment]
Definitely, this issue is assigned to you. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
Thank you @prathimacode-hub . Will inform once I have created the PR.

**Comment by Soumayan-pal01** [comment]
I have created the PR @prathimacode-hub . Please review it.
