### ISSUE TITLE
Stock Price Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#18]
Hey LGM-SoC participants, good to see you.

Predicts the stock price to know the future value and gain significant profits.

**Dataset** : https://www.kaggle.com/daiearth22/uniqlo-fastretailing-stock-price-prediction

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by theanshulcode** [comment]
Please assign me this task @prathimacode-hub

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by Sumit11081996** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by sy07** [comment]
Hi mam, I would like to work on this issue as LGM-SOC'21 participant from June 10. Do assign me this task tomorrow if possible.
Thank You!

**Comment by prathimacode-hub** [comment]
Also note it, don't rush over issues. All LGM-SOC participants are allowed to work on 1 issue at a time. It's your learning opportunity, a way to collaborate, don't think it as a competition. That's the beauty of open source. @sy07

**Comment by sy07** [comment]
Hi mam, I would like to work on this issue as LGMSOC21 participant. Please assign me to this task if possible.

**Comment by prathimacode-hub** [comment]
Yes, go ahead. Compare it using multiple algorithms. And dataset is provided above. All the best. Any doubts, don't hesitate to ask. @sy07
