### ISSUE TITLE
Crop Recommendation System

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#182]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/atharvaingle/crop-recommendation-dataset) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001  , I am up for this issue and I want to contribute in this.

Name of the issue : Crop Recommendation System
Issue #182

- [x] LGMSOC Participant

Approach : For this recommendation model I would like to use Random forest, decision tree, logistic regression, SVM, Gausian NB and some more algorithms. After that I'll evaluate them based on the accuracy scores.

Description : This project is all about deploying the recommendation model.

Task Taken : Developing the classification model for this project.

Please assign me this issue.

**Comment by Manasi2001** [comment]
Conquer 1 issue at a time @abhisheks008. 😬

**Comment by sy07** [comment]
Hi @Manasi2001 , I would like to work on this issue as LGM-SOC'21 participant. I would like to work on data modeling. I will use regression, random forest, KNN and some algorithms to evaluate accuracy.
Do assign me this task if possible.

**Comment by abhisheks008** [comment]
> Conquer 1 issue at a time @abhisheks008.

Conquered ma'am! Please assign me this issue.

**Comment by Manasi2001** [comment]
Go ahead @abhisheks008!
@sy07 the issues are assigned on FCFS basis. Abhishek's PR didn't require any further changes, so he can work on this as of now. Are you willing to use some different approach @sy07, other than Abhishek's? Then I can assign it to you as well.
