### ISSUE TITLE
Sarcasm Detection

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#184]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/rmisra/news-headlines-dataset-for-sarcasm-detection?select=Sarcasm_Headlines_Dataset.json) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001  , I am up for this issue and I want to contribute in this.

Name of the issue : Sarcasm Detection
Issue #184

- [x] LGMSOC Participant

Approach : For this detection model, I would like to use, Random Forest Classifier, Log Regression, Lasso, Huber, Ridge classifier and also I would like to use Convolution Neural Network for this.

Description : This project is all about deploying the classification model.

Task Taken : Developing the classification model for this project.

Please assign me this issue.

**Comment by Manasi2001** [comment]
Go for it @abhisheks008. ✨

**Comment by abhisheks008** [comment]
No issues! I'll do it first, then I'll go that issue.
