### ISSUE TITLE
Disneyland Reviews Analysis

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#186]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/arushchillar/disneyland-reviews) or any other dataset of your choice. The aim is to predict the rating attribute. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Soumayan-pal01** [comment]
Hey @Manasi2001 I would like to work on this issue for 'Model Creation' as LGM-SOC participant. I would use different NLP techniques and Sentiment Analysis approach to analysis the customer reviews and analyse their sentiments. Please assign me this issue if possible. Thank you.

**Comment by Manasi2001** [comment]
Sounds good @Soumayan-pal01. Just do that minor change in your PR first, then start working on this.

**Comment by Soumayan-pal01** [comment]
Thank you @Manasi2001 . I will inform once I have created the PR.

**Comment by Soumayan-pal01** [comment]
I have created the PR. Please review it @Manasi2001 . Thank you.
