### ISSUE TITLE
Plant Seedlings Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#187]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this dataset or any other [dataset](https://www.kaggle.com/vbookshelf/v2-plant-seedlings-dataset) of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001  , I am up for this issue and I want to contribute in this.

Name of the issue : PLANT SEEDLINGS CLASSIFICATION
Issue #187

- [x] LGMSOC Participant

Approach : For this project I would like to use CNN. The architectures that I am gonna use are, ResNet, AlexNet, Vgg, Inception, MobileNet, SqueezeNet, DenseNet.

Description : This project is all about deploying the classification model.

Task Taken : Developing the classification model for this project.

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Whooa, great. Issue is assigned to you. @abhisheks008
