### ISSUE TITLE
Water Quality Prediction 

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#188]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/adityakadiwal/water-potability) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Isha307** [comment]
> Hey LGM-SOC participant, great to have you here! 😀
> If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/adityakadiwal/water-potability) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
> Happy coding :)

I would like to work on this issue.
I will build a model that will predict if the water is good for consumption or not.
Please assign me @Manasi2001 @prathimacode-hub

**Comment by Manasi2001** [comment]
@Isha307 first do that minor change in your PR, then start working on this. Assigning to you.

**Comment by Isha307** [comment]
> @Isha307 first do that minor change in your PR, then start working on this. Assigning to you.

okay.
