### ISSUE TITLE
Forest Cover Type Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#189]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/uciml/forest-cover-type-dataset) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by rammya29** [comment]
Hello @Manasi2001 , I would like to work on this project. I decided to use a classifier algorithm to get the desired model. Can you assign this to me?

**Comment by Manasi2001** [comment]
@rammya29 first make the changes in your PR, then get this one assigned. 🙃

**Comment by Manasi2001** [comment]
Go ahead @rammya29.

**Comment by rammya29** [comment]
I cannot upload my CSV file in the dataset folder since it has a larger size. What should I do?

**Comment by prathimacode-hub** [comment]
You can try adding up in .zip format else you can add up the link to your dataset. @rammya29
