### ISSUE TITLE
Music Genre Classification

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#19]
Hey LGM-SoC participants, good to see you.

This project should automatically classify different musical genres from audio.

GTZAN Genre dataset : http://marsyas.info/downloads/datasets.html

If you like to work on this issue, follow the given guidelines for code as well as for the README.

Enjoy your open source journey!😎

**Comment by Raghavi20** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant. Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
Kindly explain your approach, algorithms you would follow and the task you're going to choose? @Raghavi20

**Comment by Abhilash249** [comment]
I would also like to contribute to this issue. Please assign me if possible.

**Comment by Raghavi20** [comment]
@prathimacode-hub
The dataset used here includes 10 different genres with 100 clips for each genre .So to do audio analysis ,data visualizations and feature extraction, I wanted to use a library called librosa .So after the features are extracted we need to choose a classifier which is responsible for classifying the music into different genres. I wanted to use CNN algorithm and compare the accuracy with SVM and XGboost.

**Comment by prathimacode-hub** [comment]
That sounds cool. You can proceed. But what's the task you'll be working on? "Model Creation" or "Front End" or "Back End" or "Designing"? @Raghavi20

**Comment by prathimacode-hub** [comment]
> I would also like to contribute to this issue. Please assign me if possible.

Issue is assigned on FCFS basis and only one can take up an issue. You can take up some other issue to work on. @Abhilash249

**Comment by Raghavi20** [comment]
@prathimacode-hub 
Thank You, I initially wanted to work on model creation and if that is completed i will try to work on the frontend and backend part

**Comment by prathimacode-hub** [comment]
Ok, for now I shall assign as model creation. But when you want on other things, let us know. We shall assign accordingly. @Raghavi20

**Comment by Raghavi20** [comment]
okk mam, thankyou

**Comment by Manasi2001** [comment]
Updates @Raghavi20?

**Comment by Raghavi20** [comment]
I completed audio analysis and feature extraction part. I still need to do the classification and training the 3 algorithms and compare accuracy.

**Comment by prathimacode-hub** [comment]
> I completed audio analysis and feature extraction part. I still need to do the classification and training the 3 algorithms and compare accuracy.

Ok complete it asap, but intimate us timely. @Raghavi20

**Comment by Raghavi20** [comment]
sure,will do

**Comment by prathimacode-hub** [comment]
It's been 10days again. @Raghavi20

**Comment by Raghavi20** [comment]
Sorry for the delay,i have completed the project but I got few errors in the backend deployment part (flask).I am trying to solve it .I will submit it by tomorrow.

**Comment by prathimacode-hub** [comment]
Ok, no worries as long as you update me your progress timely. @Raghavi20
