### ISSUE TITLE
Dance Form Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#190]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/souravkgoyal/identify-the-dance-form) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001  , I am up for this issue and I want to contribute in this.

Name of the issue : Dance Form Classification
Issue #190

- [x] LGMSOC Participant

Approach : For this classification model I would like to use the Feed work Neural Network and Transfer Learning Method. After that I'll evaluate the models based on the accuracy scores/

Description : This project is all about deploying the classification model.

Task Taken : Developing the classification model for this project.

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Kudos, this issue is assigned. @abhisheks008 👍
