### ISSUE TITLE
Horses or Humans Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#192]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/sanikamal/horses-or-humans-dataset) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by rammya29** [comment]
Here, I wish to work on this project. I would like to use OpenCV- TensorFlow to train the model and to classify either humans or horses. I would like to do this under LGM-SoC'21 - Participant. Please assign this work to me.

**Comment by prathimacode-hub** [comment]
First, your PR will reviewed and once it's approved. You can work on this issue. @rammya29

**Comment by Soumayan-pal01** [comment]
I would like to work on 'Model Creation' for this issue using different machine learning and deep learning approaches .Please assign this issue if possible @prathimacode-hub . Thank you.

**Comment by prathimacode-hub** [comment]
Can you take up an another issue @Soumayan-pal01, as @rammya29 has expressed her interest first and she isn't into any issue. If you wish to, you can come up with a new issue as well.

**Comment by Soumayan-pal01** [comment]
Okay @prathimacode-hub . I didn't notice the time actually. Sorry for that. I would like to open up a new issue for Flight Fare Predictions.

**Comment by prathimacode-hub** [comment]
Ok, no worries. All the best. Sure. @Soumayan-pal01

**Comment by prathimacode-hub** [comment]
@rammya29 do you want to work on this?

**Comment by rammya29** [comment]
Yes, I am willing to take

**Comment by prathimacode-hub** [comment]
Let me know your approach, algos you would consider and task you would choose? @rammya29

**Comment by rammya29** [comment]
I think do the model with TensorFlow and Keras module in python.

**Comment by prathimacode-hub** [comment]
Ok, good to know. All the best. Issue assigned. @rammya29

**Comment by rammya29** [comment]
@prathimacode-hub Hi mam, Actually I could upload my dataset in the folder, even my zipfile is too big more than 25 MB. Can you tell any other ways to it?

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub Hi mam, Actually I could upload my dataset in the folder, even my zipfile is too big more than 25 MB. Can you tell any other ways to it?

If you couldn't, you can just add up a link to the dataset @rammya29
