### ISSUE TITLE
Face  Generating using DCGAN

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#196]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

I'd Like to add Generating Face Project.
I would be using [This](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html) Data set to generate faces of celebrities using DCGAN.( will be following the total pipeline)

Describe the solution you'd like
In this project, I'll define and train a DCGAN on a dataset of faces. the goal is to get a generator network to generate new images of faces that look as realistic as possible!
1.I'll use, CelebFaces Attributes Dataset (CelebA) to train the adversarial networks.
2.The project will be broken down into a series of tasks from loading in data to defining and training adversarial networks.
3.At the end of the notebook, We'll be able to visualize the results of the trained Generator to see how it performs.
4.I'll add Model pkl File and Images as well.

I'll work on the model in the project.

**Comment by Manasi2001** [comment]
Sounds awesome, go ahead @NEERAJAP2001. 👍🏻

**Comment by prathimacode-hub** [comment]
Any updates? @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Yeah !! I'm sorry this is taking time, I'll make my first commit tomorrow is that okay @prathimacode-hub?

**Comment by prathimacode-hub** [comment]
> Yeah !! I'm sorry this is taking time, I'll make my first commit tomorrow is that okay @prathimacode-hub?

Yes, that's ok. If u let me know, it's more than enough. @NEERAJAP2001
