### ISSUE TITLE
Drowsiness Detection using Computer Vision

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#20]
Hey LGM-SoC participants, good to see you.

Using OpenCV, this project should be able to automatically detect the drowsiness of a person who is driving and buzzes an alarm when a person is drowsy

Refer this paper :  http://vision.fe.uni-lj.si/cvww2016/proceedings/papers/05.pdf.

If you like to work on this issue, follow the given guidelines for code as well as for the README. 

Enjoy your open source journey!😎

**Comment by psyduck1203** [comment]
Hey, This seems a pretty cool issue, can you please assign me this issue?

**Comment by prathimacode-hub** [comment]
Color Identification or Drowsiness Detection? You can work on only 1 issue at a time. So let me know about your decision? @psyduck1203

**Comment by psyduck1203** [comment]
Okay I'll work on color identification first.

**Comment by prathimacode-hub** [comment]
Good decision @psyduck1203

**Comment by jayant766** [comment]
please assign it to me under LGM-SOC'21

**Comment by prathimacode-hub** [comment]
Do you want to work on this issue? @jayant766

**Comment by jayant766** [comment]
@prathimacode-hub yes

**Comment by prathimacode-hub** [comment]
Ok, let me know about your approach you would follow and task you would take up. @jayant766

**Comment by jayant766** [comment]
I am using Dlib and OpenCV with Python for this Drowsiness Detection issue

**Comment by prathimacode-hub** [comment]
Ok, go for it. This issue is assigned to you. @jayant766

**Comment by Manasi2001** [comment]
This issue is open for contributions again. 💥

**Comment by ainy-123** [comment]
> This issue is open for contributions again. 💥

I am LGM-SoC participant. I work on this issue, will you please assign this to me?

**Comment by prathimacode-hub** [comment]
Kindly let us know of your approach, how would you proceed? And task you're choosing. @ainy-123

**Comment by ainy-123** [comment]
> Kindly let us know of your approach, how would you proceed? And task you're choosing. @ainy-123

I'll be using dlib facial landmark approach to check the position of mouth (how much open it is to check yawning condition) and eye(whether the person is drowsy or not).This way ,I will proceed with this issue.

**Comment by prathimacode-hub** [comment]
Sure, you can go ahead. @ainy-123

**Comment by Manasi2001** [comment]
Updates @ainy-123? We haven't heard from you in 11 days.

**Comment by ainy-123** [comment]
> Updates @ainy-123? We haven't heard from you in 11 days.

Sorry ,I got stuck in some urgent work. I will try to raise the PR by tomorrow. If, I fail to do so by tomorrow, You can unassign me ,anyone else can work on this.

**Comment by ainy-123** [comment]
> Updates @ainy-123? We haven't heard from you in 11 days.

hey @Manasi2001 ,I am having few errors in my code,  not getting the expected result.can I take 1 more day to debug and successfully raise PR?

**Comment by prathimacode-hub** [comment]
Ok, no worries. As long as you intimate timely, it's fine for us. @ainy-123

**Comment by ainy-123** [comment]
> Ok, no worries. As long as you intimate timely, it's fine for us. @ainy-123

Sorry, I won't be able to complete this, stuck with some urgent stuffs, unassigning myself.

**Comment by prathimacode-hub** [comment]
You can't unassign yourself. @ainy-123
