### ISSUE TITLE
Extending "Look Through The Kart Of Amazing Projects" section in README.md file

### ISSUE THREAD

**Issue by jannatulferdaws** [prathimacode-hub/ML-ProjectKart#209]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

I'd like to extend the "Look Through The Kart Of Amazing Projects" section in README.md file.
There are 50+ project in the repository. But in that section there is only 23 projects.

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can proceed. Follow up as it is. @jannatulferdaws

**Comment by prathimacode-hub** [comment]
How is it going? @jannatulferdaws

**Comment by jannatulferdaws** [comment]
Yeah. It's going okay till now.

**Comment by prathimacode-hub** [comment]
> Yeah. It's going okay till now.

Hope, you're upto date with the add-ons. @jannatulferdaws

**Comment by prathimacode-hub** [comment]
> > Yeah. It's going okay till now.
> 
> Hope, you're upto date with the add-ons. I need to get this done by tomorrow. If you couldn't let me know, I shall update it. @jannatulferdaws

**Comment by jannatulferdaws** [comment]
I will be done by tomorrow @prathimacode-hub

**Comment by prathimacode-hub** [comment]
> I will be done by tomorrow @prathimacode-hub .
> I had a question. Can I write the project names as ascending order?

If you want to add up in ascending order, you can. But make sure template doesn't change. @jannatulferdaws
