### ISSUE TITLE
Twitter Sentiment Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#21]
Hey LGM-SoC participants, good to see you.

This project analyses their sentiments by knowing the feelings of user shared on twitter.

Dataset : https://www.kaggle.com/crowdflower/twitter-airline-sentiment

If you like to work on this issue, follow the given guidelines for code as well as for the README. 

Enjoy your open source journey!😎

**Comment by Rutikab12** [comment]
hey, @prathimacode-hub I would like to work on this issue.

**Comment by Manasi2001** [comment]
@Rutikab12 you can surely work on this, but first let me know how you are planning to proceed, what all algorithms you will use and which task you'll be working on: backend, frontend or model creation. Then, I'll assign it to you :)

**Comment by Rutikab12** [comment]
> @Rutikab12 you can surely work on this, but first let me know how you are planning to proceed, what all algorithms you will use and which task you'll be working on: backend, frontend or model creation. Then, I'll assign it to you :)

Excuse me for conveying late, I have got another issue with this repo on which I am currently working. So you can assign it other participants. @Manasi2001

**Comment by PriyankaHotchandani** [comment]
Hey, I'd like to work on this issue under LGM-SOC'21. But just a request, can I use a different dataset instead? I'd recently read a research paper on "Evaluation of Deep Learning Techniques in Sentiment Analysis from Twitter Data" and in accordance to that, I'd like to implement it using Word2Vec word embedding model.

Link to proposed Dataset: https://www.kaggle.com/kazanova/sentiment140

**Comment by prathimacode-hub** [comment]
Yeah, sure. Go ahead. The datasets are provided just as a guidance. You're free to choose your own datasets as long as it fits the project. I had assigned this task to you. @PriyankaHotchandani

**Comment by PriyankaHotchandani** [comment]
Alright, thanks! Will start working on it. And yes, it's model creation. 
Is it okay if I attach the research reference as well while making the final commit?

**Comment by prathimacode-hub** [comment]
Yeah, you can attach it. @PriyankaHotchandani 👍
