### ISSUE TITLE
Flight Fare Predictions

### ISSUE THREAD

**Issue by Soumayan-pal01** [prathimacode-hub/ML-ProjectKart#210]
---
Title: Flight Fare Predictions
About: To predict the fare of flights of different Airlines and routes
Name: Soumayan Pal
Label: Feature Request
Assignee: 'Soumayan-pal01'

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Yes I Have discussed with the Project Admin**

**The flight fare is needed to be predicted**

**A comparative analysis of different regressor models to predict the flight fare.**

**Using different EDA techniques and vizualization. Using linear regression, KNN, Decision Tree, Random Forest, XGBoost models for training and testing.**

**Comment by Soumayan-pal01** [comment]
I will be working on 'Model Creation'.

**Comment by prathimacode-hub** [comment]
Assigned. Proceed. @Soumayan-pal01
