### ISSUE TITLE
Startup Profit Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#215]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/karthickveerakumar/startup-logistic-regression) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.
I will use Linear Regression algorithm to create model and predict the accuracy.

**Comment by Manasi2001** [comment]
1 issue at a time @Jagannath8.

**Comment by Jagannath8** [comment]
> 1 issue at a time @Jagannath8.

After completion of previous issue, I'll work on this.

**Comment by Jagannath8** [comment]
Can I start working on this issue? @Manasi2001 @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. Issue assigned. @Jagannath8

**Comment by Jagannath8** [comment]
@prathimacode-hub mam I want to try for backend

**Comment by prathimacode-hub** [comment]
Ok, model creation and backend? @Jagannath8

**Comment by Jagannath8** [comment]
yess
