### ISSUE TITLE
Advertisement Success Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#216]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this dataset or any other [dataset](https://www.kaggle.com/fayomi/advertising) of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.
I will use multiple machine learning algorithms to create model and compare the accuracy.

**Comment by Manasi2001** [comment]
Sure, go ahead. 👍🏻
