### ISSUE TITLE
Parkinson's Disease Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#22]
Hey LGM-SoC participants, good to see you.

Predicts whether the person is diagnosed with parkinson's disease or not

**Dataset** : https://www.kaggle.com/gargmanas/parkinsonsdataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by harshita9621** [comment]
Hii, @prathimacode-hub I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by harshita9621** [comment]
Hii, @prathimacode-hub I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant . Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
You had been assigned to this task. You can start with your work. @harshita9621
