### ISSUE TITLE
Salary Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#221]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/balakrishcodes/others?select=hiring.csv) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Anshal55** [comment]
Title: Salary Prediction
About: To predict salaries based on certain parameters.
Name: Anshal Singh
Label: Feature Request

Define You:

- [x] LGM-SOC'21 Participant
- [] Contributor


I'm planning to use different EDA techniques and multiple prediction algorithms and draw comparison between them and finally deploy the working model.

**Comment by Manasi2001** [comment]
Very good @Anshal55. Go ahead 👍🏻

**Comment by Anshal55** [comment]
Thanks!
