### ISSUE TITLE
Exports Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#222]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/balakrishcodes/others?select=house-votes-84.csv) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001  , I am up for this issue and I want to contribute in this.

Name of the issue : Exports Classification
Issue #222

- [x] LGMSOC Participant

Approach : For this recommendation model I would like to use Random forest, decision tree, linear regression and some more algorithms. After that I'll evaluate them based on the accuracy scores.

Description : This project is all about deploying the classification model.

Task Taken : Developing the classification model for this project.

Please assign me this issue.

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub and @Manasi2001  , I am up for this issue and I want to contribute in this.

Name of the issue : Heights and Weights Prediction
Issue #222

- [x] LGMSOC Participant

Approach : For this recommendation model I would like to use Random forest, decision tree, linear regression and some more algorithms. After that I'll evaluate them based on the accuracy scores.

Description : This project is all about deploying the classification model.

Task Taken : Developing the classification model for this project.

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Other issue is assigned to you. Give some time for us to create new issues. 😀@abhisheks008

**Comment by abhisheks008** [comment]
Completed the previous issue #220 and just made the PR. Can you assign me this issue now?

**Comment by prathimacode-hub** [comment]
How you do this yaar, so fast. Can't find words to appreciate you. This way issues would end up in a day. 😆
Yup, issue assigned. @abhisheks008
