### ISSUE TITLE
Salary Range Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#223]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/balakrishcodes/others?select=salaries.csv) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by ayushi424** [comment]
Hey @Manasi2001 & @prathimacode-hub,
I'd like to work on this issue.
Mainly on model creation part i.e. use different classification algorithms and find which works the best.
Please assign.

**Comment by prathimacode-hub** [comment]
Cool, go ahead. Issue assigned. @ayushi424
