### ISSUE TITLE
Titanic Survival Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#23]
Hey LGM-SoC participants, good to see you.

This project Predicting the chances of survival in RMSTitanic

**Dataset** : https://www.kaggle.com/c/titanic/data

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by theanshulcode** [comment]
Please assign me this task @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Hey, this is only for LGM-SoC participants.

**Comment by theanshulcode** [comment]
OK

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
Issues would be assigned only from June 10th on first come first serve basis. Stay tuned. @harshita9621

**Comment by harshita9621** [comment]
Hii, @prathimacode-hub I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
Can you let me know of the issue, you want to work on first. As only 1 issue is assigned at a time @harshita9621

**Comment by RHEA211** [comment]
Hi @prathimacode-hub  I would like to work on this project.Can you assign it to me

**Comment by prathimacode-hub** [comment]
How would work? Algorithms you would use? What's the approach? @RHEA211

**Comment by RHEA211** [comment]
Ma'am I would be using Naive Bayes method and can compare all- Gaussian ,Multinomial,Complement,Bernoulli and Categorical Naive Bayes Method to see the accuracy of each model

**Comment by RHEA211** [comment]
Task of-Titanic Survival Prediction #23

**Comment by prathimacode-hub** [comment]
Great, So you're going for Model creation right? @RHEA211

**Comment by RHEA211** [comment]
Yes Ma'am ,I will make the prediction model but completely new to open source.

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant . Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
Sorry, @harshita9621. It's on first come first serve basis. @RHEA211 expressed her interest first for this issue. I know you showed interest earlier than her. But you was working on another issue.

@RHEA211, you had been assigned to this task. Go ahead.

**Comment by RHEA211** [comment]
Sure ma'am
