### ISSUE TITLE
Face_Detection using Open Cv

### ISSUE THREAD

**Issue by anubhav201241** [prathimacode-hub/ML-ProjectKart#230]
Define You:

- [x] LGM-SOC'21 Participant 

**Is your feature request related to a problem? Please describe.**

YES, WANT TO ADD FACE_EYEDETECTION WITH THE USE OF PYTHON AND OPEN CV

**Describe the solution you'd like...**

I want to contribute to your project by adding Face and Eye detection part with the help of Opencv and Python
In which it can detect the face, eye, and middle part of the face with the use of open cv and Python

**Describe alternatives you've considered?**
IF NOT OPEN CV THEN I'LL TRY TO IMPLEMENT OTHER APPROACH WITH THE USE OF MACHINE LEARNING

**Additional context**

@prathimacode-hub  Kindly assign this issue to me under the label of LGMSOC'21

**Comment by prathimacode-hub** [comment]
Sorry to say, but this issue is already done. You can take up from issues up for grabs else, you can come up with new issue. @anubhav201241
