### ISSUE TITLE
DNA Sequencing Classification

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/ML-ProjectKart#238]
Define You: @abhisheks008 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to a problem. I want to add a project.

**Problem Statement**
The problem statement is, DNA sequencing classification using DNA datasets.

**Approach to be followed (optional):**
I am going to build 3 different classification models for Human, Dog and Chimpanzee. And for that building purpose I will be using several classification algorithms and will compare them to find the best fit algorithm for each of the 3 cases.

**Comment by prathimacode-hub** [comment]
It's unique project, you can proceed. @abhisheks008
