### ISSUE TITLE
Spam Message Detector

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#24]
Hey LGM-SoC participants, good to see you.

This project predicts whether the recieved message is spam or ham.

Dataset : https://www.kaggle.com/team-ai/spam-text-message-classification

If you like to work on this issue, follow the given guidelines for code as well as for the README. 

Enjoy your open source journey!😎

**Comment by sai-keerthi** [comment]
can you please assign me this issue

**Comment by prathimacode-hub** [comment]
Yeah, I would assign. But let me know how would proceed further or work with this project @sai-keerthi

**Comment by sai-keerthi** [comment]
firstly preprocessing the data ,then fitting the appropriate model staring from logistic regression, multinominal naive based classifier and comparing the performance of the model

**Comment by prathimacode-hub** [comment]
Ok great. Sure, this issue is assigned to you. @sai-keerthi

**Comment by sai-keerthi** [comment]
model creation
