### ISSUE TITLE
Malaria Disease Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#244]
Hey LGM-SoC participants, good to see you.

Malaria Disease Prediction helps in predicting whether the following person is affected with malaria or not.

Dataset : https://www.kaggle.com/miracle9to9/files1

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Soumayan-pal01** [comment]
I would like to work on 'Model Creation' for this issue using CNN approach. Please assign me if possible @prathimacode-hub . Thank you.

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
I have created the PR. Please review it @prathimacode-hub .
