### ISSUE TITLE
Walmart Sales Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#245]
Hey LGM-SoC participants, good to see you.

In this project, it would help us in predicting the walmart sales using dataset provided.  

Dataset : https://www.kaggle.com/divyajeetthakur/walmart-sales-prediction

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by shivani6320** [comment]
Hey!! I would like to contribute to this issue.

**Comment by prathimacode-hub** [comment]
Can you let me know of ur approach, algos and task you would consider? @shivani6320

**Comment by shivani6320** [comment]
I would create visualizations and perform Exploratory data analysis on sales data. I would use Linear models like Linear,Ridge,lasso regression as well as Non linear regressions like RandomForest Regressor,DecisionTree Regressor,XGB Regressor and compare these models and draw out best possible model suited for the data. Basically I would like to compare Linear & Non Linear models.

**Comment by prathimacode-hub** [comment]
That's great, Issue assigned. @shivani6320

**Comment by shivani6320** [comment]
Hey @prathimacode-hub . After some work I thought about my approach which is very familiar and recurrent. Plus ,with other prediction projects, ensemble modeling & comparison of various models have already been done. So why not try something other than usual approach this time....So how about doing Time series forecasting for predicting sales with great visualizations and explanation? If you agree with me I can work towards it.

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. @shivani6320
