### ISSUE TITLE
Fuel Consumption Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#247]
Hey LGM-SoC participants, good to see you.

Fuel Consumption Analysis helps in analyzing the consumption of fuel considering carious parameters.

Dataset : https://www.kaggle.com/anderas/car-consume

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to provide brief analysis using various visualizations. 

Enjoy your open source journey!😎

**Comment by Isha307** [comment]
@prathimacode-hub Can I work on this issue?
I will create model that will predict the consumption depending on the gas type.

**Comment by prathimacode-hub** [comment]
Sure, you can go ahead. @Isha307
