### ISSUE TITLE
Phishing Website Detection

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#248]
Hey LGM-SoC participants, good to see you.

Phishing Website Detection would help  us in detecting whether the concerned website had underwent or affected with phishing or not.

Dataset : https://www.kaggle.com/eswarchandt/phishing-website-detector

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by abhisheks008** [comment]
Hey, @prathimacode-hub I want to work on this issue.

Project Name : Phishing Website Detection
Issue : #248
Approach : For this detection system I'll be using various regression models and as well as classification models depending on the features that are going to be trained. After the implementation of all the models the accuracy  of the models will be checked using the accuracy score.
Task taken : Model Creation

Please assign me this issue!

**Comment by prathimacode-hub** [comment]
Assigned. @abhisheks008
