### ISSUE TITLE
Board Game Review Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#249]
Hey LGM-SoC participants, good to see you.

Board Game Review Prediction project would helps us in predicting the ratings of the board games using reviews.

Dataset : https://www.kaggle.com/gabrio/board-games-dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by abhisheks008** [comment]
@prathimacode-hub I am up for this issue.

Approach : I want to use Random forest regression and linear regression for this model. And before the model preparation I'd like to the analysis of the dataset.

Issue #249
- [x] LGMSOC Participant
Task Taken : Model Creation

Please assign me this issue!

**Comment by prathimacode-hub** [comment]
Great, you can proceed. Issue assigned. After this issue or whenever you want to, I'm looking forward to your take up on Covid Analysis. We're accepting different kinds of proposals for that particular issue for anyone who wants to work on it. It's not just a one person take up issue, as subject is demanding. Hope, you would. All the best. @abhisheks008

**Comment by abhisheks008** [comment]
Yeah sure why not! @prathimacode-hub I'll do that if I can!
