### ISSUE TITLE
Road Lane Detection

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#25]
Hey LGM-SoC participants, good to see you.

With this project, you should be able to detect the road and move forward in your own lane.

If you like to work on this issue, follow the given guidelines for code as well as for the README.

Enjoy your open source journey!😎

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub , I am up for this issue and I want to contribute in this.

Name of the issue : Road Lane Detection 
Issue #25

- [x] LGMSOC Participant

Approach : I will be solving this issue using the opencv library, apart from that I will be also using the libraries such as numpy, imutils, time. These are the essential components which I will be using to solve this complicated issue.

Description : This script will detect the lane in an input video or, an input image and provide the output as video and image respectively. Also it can take the input through the system's camera and can detect the lane in that input.

Task Taken : Developing the Back end/Model of this project.

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can proceed. All the best. @abhisheks008
