### ISSUE TITLE
Dogecoin Price Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#251]
Hey LGM-SoC participants, good to see you.

Dogecoin Price Prediction will help us in predicting the price of dogecoin using the dataset provided.

Dataset : https://www.kaggle.com/dhruvildave/dogecoin-historical-data

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by abhisheks008** [comment]
@prathimacode-hub I am up for this project too!

Here I'll use different types of regression algorithms for predicting the price of the dogecoin, such as linear regression, random forest, decision tree and many more!

Name : Dogecoin Price Prediction
Issue #251
Task taken : Prediction model creation
Accuracy : models will be checked using the accuracy scores

**Comment by prathimacode-hub** [comment]
Once you create a PR for earlier issue, I shall assign you with this. @abhisheks008

**Comment by abhisheks008** [comment]
@prathimacode-hub assign me this issue!

**Comment by prathimacode-hub** [comment]
Assigned.  @abhisheks008
