### ISSUE TITLE
Bike Crash Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#252]
Hey LGM-SoC participants, good to see you.

Bike Crash Anlysis wouldl help us in analyzing the bike crashes occured using dataset provided.

Dataset : https://www.kaggle.com/atharvaingle/bikepedcrash

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can analyze using various visualization techniques to get deeper understanding.

Enjoy your open source journey!😎

**Comment by abhisheks008** [comment]
Hey @prathimacode-hub I am up for this issue.

I'll be using different aspects of data visualization for analyzing the dataset.
Task taken : Analysis model
Name : Bike Crash Analysis
Issue #252

- [x] LGMSOC participant

Please assign me this issue

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. @abhisheks008
