### ISSUE TITLE
Crime Rate Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#254]
Hey LGM-SoC participants, good to see you.

This project will help us in predicting the crime rate around various states with various parameters taken into consideration.

Dataset : https://www.kaggle.com/nehaprabhavalkar/crime-in-india

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by suy1968** [comment]
Please assign me this issue as I am a participant of LGMSOC'21.

**Comment by prathimacode-hub** [comment]
Can you let me know of your approach, how would you proceed. Algorithms you would use up. And task you're going to choose? @suy1968

**Comment by suy1968** [comment]
For this, I used multi Linear regression although I used linear And logistics regression but in multi linear regression it is produced minimal error. Predicting graph between Crime type and year in which one is independent and one is dependent variable. 
At last model predict  crime type and data visualization on different types of graph like scatterplot, barplot etc.

**Comment by prathimacode-hub** [comment]
That's cool. Use atleast 3 algorithms and compare it to get good efficiency. Issue assigned. @suy1968

**Comment by prathimacode-hub** [comment]
It's been 5 days, no updat from you yet? @suy1968

**Comment by suy1968** [comment]
Maam, I will send PR today itself because last days my exam was held.

**Comment by prathimacode-hub** [comment]
Ok, sure. @suy1968

**Comment by prathimacode-hub** [comment]
No update from you yet @suy1968

**Comment by prathimacode-hub** [comment]
Are you working on this issue or not? @suy1968

**Comment by suy1968** [comment]
> Are you working on this issue or not? @suy1968

Maam please assign other because in this time my interview held @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Ok sure. @suy1968

**Comment by deepthi1107** [comment]
please do assign me mam @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Already an issue is assigned. @deepthi1107
