### ISSUE TITLE
Terrorist Attack Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#255]
Hey LGM-SoC participants, good to see you.

This project will help us in predicting the terrorist attack with various parameters taken into consideration by using the Global Terrorism Database.

Dataset : https://www.kaggle.com/START-UMD/gtd

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by 23-24** [comment]
can I work on this

**Comment by prathimacode-hub** [comment]
Let me know of your approach? The task you would take up and how would you proceed. @23-24

**Comment by 23-24** [comment]
I would use data analysis to gives an idea on the rate of terrorist attacks in each year, check the regions that are under attack, which country is mostly effected, kind of weapons used, trend of attacks.

**Comment by prathimacode-hub** [comment]
This is not just a data analysis project, it involves both data analysis and model creation.  @23-24

**Comment by 23-24** [comment]
ok maam,I will also use regression modals for prediction

**Comment by 23-24** [comment]
using decision tree

**Comment by prathimacode-hub** [comment]
Ok, issue assigned. @23-24

**Comment by 23-24** [comment]
Thankyou

**Comment by prathimacode-hub** [comment]
It's been 5 days, no update from you yet? @23-24

**Comment by 23-24** [comment]
working on it maam will upload  it soon

**Comment by prathimacode-hub** [comment]
You should update your progress once in 2 days, else how would I know if you are working or not. @23-24

**Comment by 23-24** [comment]
srry maam ,will complete it by today itself

**Comment by prathimacode-hub** [comment]
Take your time, you can even create your PR by tomorrow. But info is needed. No need to be sorry. @23-24

**Comment by 23-24** [comment]
Maam I am not able to upload the dataset given since it is too large
