### ISSUE TITLE
Zomato Bangalore Restaurants Recommendation Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#256]
Hey LGM-SoC participants, good to see you.

This project would help us analyzing the restaurants of bangalore based on various factors taken into consideration.

Dataset : https://www.kaggle.com/himanshupoddar/zomato-bangalore-restaurants

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to analyze it using various visualization techniques to get deeper understanding.

Enjoy your open source journey!😎

**Comment by rammya29** [comment]
Hi mam, I would like to work on this as an LGM-Soc'21 Participant. I would like to do that in a way like full data analysis and creating a simple model to extract some features and recommendations. Please assign this to me.

**Comment by prathimacode-hub** [comment]
That's great, you can proceed. @rammya29

**Comment by rammya29** [comment]
How to access the CSV file mam?. I am able to download it? Is there any other link for dataset?

**Comment by prathimacode-hub** [comment]
You're not able to download the dataset? @rammya29

**Comment by rammya29** [comment]
Yes

**Comment by prathimacode-hub** [comment]
> Yes

I mean you are saying, you are not able to download from kaggle or not able to download in ur forked repo. @rammya29

**Comment by rammya29** [comment]
Not able to download from kaggle itself mam

**Comment by prathimacode-hub** [comment]
Hmm, you can enter through any of ur mail id into kaggle and download it. @rammya29

**Comment by rammya29** [comment]
I actually getting error while downloading.

![IMG_20210628_180902.jpg](https://user-images.githubusercontent.com/70591317/123637729-f8933880-d83b-11eb-93b9-cf17ffa1e8e0.jpg)

**Comment by prathimacode-hub** [comment]
Ok, then you do one thing, get a public dataset of zomato bangalore restaurants and start working. It should download actually. @rammya29

**Comment by rammya29** [comment]
Sorry once again, how to get a public dataset?. If there is any link could you share?

**Comment by prathimacode-hub** [comment]
> Sorry once again, how to get a public dataset?. If there is any link could you share?

Here is the link : 

https://www.kaggle.com/ngokulakannan/zomato-india-restaurants2-lakh-restaurants-data (or) 

https://www.kaggle.com/aartithakurdocs/zomato @rammya29
