### ISSUE TITLE
Human Activity Recognition using Smartphones

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#257]
Hey LGM-SoC participants, good to see you.

With this project, we could recognize the human activity using smartphones. Here we use 6 daily life activities and various parents into concern.

Dataset : https://archive.ics.uci.edu/ml/datasets/human+activity+recognition+using+smartphones

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub I would like to work on 'Model Creation' for this issue. I would first perform EDA on the training data. Then I will perform a comparative analysis of multiple ML classifiers. Finally I will be using Artificial Neural Network approach to train the model and perform predictions. Assign me this issue if possible. Thank you.

**Comment by prathimacode-hub** [comment]
Yeah, issue assigned. As usual, rock it. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
I have created the PR. Please review it @prathimacode-hub . Thank you.
