### ISSUE TITLE
Gold Price Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#258]
Hey LGM-SoC participants, good to see you.

This project helps us in predicting the gold prices using the dataset provided.

Dataset : https://www.kaggle.com/shikhnu/gold-price

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by sy07** [comment]
Hi mam, I would like to work on this issue as LGMSOC21 participant. I would like to do model creation, I will apply various algorithms and compare accuracy.Please assign me to this task if possible.

**Comment by Manasi2001** [comment]
Go ahead @sy07!

**Comment by Soumayan-pal01** [comment]
I would like to work on 'Model Creation' for this issue @prathimacode-hub . Please assign me if possible. Thank you.

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. Go ahead. @Soumayan-pal01
