### ISSUE TITLE
Stars, Galaxies and Quasars Classification

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#259]
Hey LGM-SoC participants, good to see you.

This project will help us in classifying the stars, galaxies and quasars using the provided dataset.

Dataset : https://www.kaggle.com/lucidlenn/sloan-digital-sky-survey

If you like to work on this issue, follow the given guidelines for code as well as for the README. 

Enjoy your open source journey!😎

**Comment by abhisheks008** [comment]
I'll use different classifier models like SDG, Random forest, decision tree, knn and XgBoost for the creating the classification model. Then T'll evaluate on the basis of the accuracy score!

- [x] LGMSOC participant
Issue #259
Project Name : Stars, Galaxies and Quasars Classification
Task Taken : Model creation

Please assign me this issue @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. Again a good choice. @abhisheks008
