### ISSUE TITLE
Amazon Alexa Reviews Analysis

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#26]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/sid321axn/amazon-alexa-reviews) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper [project structure](https://github.com/prathimacode-hub/ML-ProjectKart#project-structure) for code as well as for the README.
Happy coding :)

**Comment by sonaliBedade** [comment]
I am a beginner in ML and I am familiar with basic algorithms. I would like to work on this. Can you please assign this issue to me?

**Comment by prathimacode-hub** [comment]
Sure, But first let me know of your approach and algorithms you would had thought working on? And as well, what's the task you're taking up? @sonaliBedade

**Comment by sonaliBedade** [comment]
I am planning to first visualize and plot the overall tone of the reviews and then classify them according to their positivity or negativity. But I'm not sure which classification algorithm would be suitable in this case

**Comment by prathimacode-hub** [comment]
Hmm, you can proceed. But as mentioned, atleast use 3 to 4 algorithms to get good efficiency and optimization. This issue is assigned to you. @sonaliBedade

**Comment by prathimacode-hub** [comment]
Is this all going ok, as there is no update from you? @sonaliBedade

**Comment by sonaliBedade** [comment]
Yes, I'm working on it

**Comment by prathimacode-hub** [comment]
Kindly correct the changes requested. @sonaliBedade

**Comment by sonaliBedade** [comment]
Yes I am getting an error while applying Naive Bayes that I am unable to understand and would need some help

**Comment by prathimacode-hub** [comment]
What's the error you're getting. Send me a screenshot? @sonaliBedade

**Comment by sonaliBedade** [comment]
![image](https://user-images.githubusercontent.com/71630760/124386805-bf563f00-dcf9-11eb-8eff-18829f7954f3.png)

**Comment by prathimacode-hub** [comment]
You can use try and except method, use print statement and check where it's going wrong. As it says, it's not able to convert string to float. It means from the starting point of the program all the syntaxes given, few or all are not in float. That's the reason it isn't able to fit. You know right, you can bring 2 parameters together onyl when they are of same data type. @sonaliBedade

**Comment by sonaliBedade** [comment]
Yes I'll try doing that
