### ISSUE TITLE
House Price Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#27]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/shree1992/housedata). Try using at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper [project structure](https://github.com/prathimacode-hub/ML-ProjectKart#project-structure) for code as well as for the README.
Happy coding :)

**Comment by Sumit11081996** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
Issues would be assigned only from June 10th on first come first serve basis. Stay tuned. @Sumit11081996

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by harshita9621** [comment]
Hii, @prathimacode-hub I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
I shall assign this issue to you. Let me know of the task you are interested in : Model Creation (or) Front End (or) Back End (or) Designing @harshita9621

**Comment by harshita9621** [comment]
Model Creation

**Comment by prathimacode-hub** [comment]
Ok, this issue is assigned to you. @harshita9621
