### ISSUE TITLE
Bike Rental Demand Analysis

### ISSUE THREAD

**Issue by Soumayan-pal01** [prathimacode-hub/ML-ProjectKart#277]
---
Title: Bike Rental Demand Analysis 
About: Analysis and prediction of customer demand for bike rental services
Name: Soumayan Pal
Label: Feature Request
Assignee: 'Soumayan-pal01'

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**The aim of the project is to make a forecast of the demand in Ola Bike Rental Services. The dataset contains 2 years data different features that are responsible for fluctuations in the customer ride request demand for training the model. This project predicts the upcoming nature of the customer request demand.**

**To perform a comparative analysis of different ML models**

**In this project we will perform a detailed analysis and visualization of the training dataset with different Exploratory Data Analysis techniques. Then a comparative analysis of different Regressors will be done to predict the request demand of Bike Rental Services.**

**Comment by Soumayan-pal01** [comment]
Can I work on 'Model Creation' for this issue @prathimacode-hub .

**Comment by prathimacode-hub** [comment]
Yes, you can. Proceed. @Soumayan-pal01
