### ISSUE TITLE
Churn Risk Score Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#28]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/imsparsh/churn-risk-rate-hackerearth-ml?select=train.csv) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper [project structure](https://github.com/prathimacode-hub/ML-ProjectKart#project-structure) for code as well as for the README.
Happy coding :)

**Comment by Sumit11081996** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
Issues would be assigned only from June 10th on first come first serve basis. Stay tuned. @Sumit11081996

**Comment by harshita9621** [comment]
Hii,  I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by Sumit11081996** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
I shall assign this issue to you. But let me know of the task you're going to work on like " Model Creation (or) Front End (or) Back End (or) Designing @Sumit11081996

**Comment by Sumit11081996** [comment]
model creation @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Ok, good to know. I had assigned this issue to you. @Sumit11081996
