### ISSUE TITLE
Stars Radiation -Analysis and Prediction

### ISSUE THREAD

**Issue by rajnish-488** [prathimacode-hub/ML-ProjectKart#280]
Stars radiation Prediction
Name :- Rajnish Singh (rajnish-488)

Define You:
LGM-SOC'21 Participant

The project will analysis the Data on multiple parameters (like star pressure ,temperature , wind speed) of the stars dataset by NASA. to predict the level of radiation emitted by the star .

The project use the multiple regressor and classification model to predict the radiation and do the classification of radiation rates.
project we will perform a detailed analysis of the training dataset with different Data Analysis techniques.

**Comment by rajnish-488** [comment]
Please Assign me this issue (rajnish-488)

**Comment by prathimacode-hub** [comment]
Great, so you will be working on model creation? @rajnish-488

**Comment by rajnish-488** [comment]
yes sir

**Comment by rajnish-488** [comment]
yes ma'am please assign me the  issue.

**Comment by prathimacode-hub** [comment]
Ok, issue assigned. @rajnish-488
