### ISSUE TITLE
World happiness report

### ISSUE THREAD

**Issue by Isha307** [prathimacode-hub/ML-ProjectKart#282]
Title: world happiness report
About: Analysis and prediction of happiness scores and rankings.
Name: Isha Shaw
Label: Feature Request
Assignee: 'Isha307'

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

The aim of the project is to predict happiness scores and rankings .The [dataset](https://www.kaggle.com/ajaypalsinghlo/world-happiness-report-2021) have the columns following the happiness score, economic production, social support, life expectancy, freedom, absence of corruption etc.

My aim is to perform a detailed analysis and visualization of the training dataset and create a model which help to predict happiness score. I will use different algorithms and finally create the model with best algorithm which will give best accuracy.

**Comment by Isha307** [comment]
> Title: world happiness report
> About: Analysis and prediction of happiness scores and rankings.
> Name: Isha Shaw
> Label: Feature Request
> Assignee: 'Isha307'
> 
> Define You:
> 
> * [x]  LGM-SOC'21 Participant
> * [ ]  Contributor
> 
> The aim of the project is to predict happiness scores and rankings .The [dataset](https://www.kaggle.com/ajaypalsinghlo/world-happiness-report-2021) have the columns following the happiness score, economic production, social support, life expectancy, freedom, absence of corruption etc.
> 
> My aim is to perform a detailed analysis and visualization of the training dataset and create a model which help to predict happiness score. I will use different algorithms and finally create the model with best algorithm which will give best accuracy.

Can I work for this issue @prathimacode-hub ?

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. @Isha307
