### ISSUE TITLE
Cartier Jewelry Classification

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/ML-ProjectKart#284]
Define You:

- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
I would like to make a classification model which will classify the Cartier Jewelry dataset.

**Describe the solution you'd like...**
For building the classification model, I'd like to use several algorithms and then measure them according to the accuracy scores. Also I will do a Data analysis portion for identifying the features.

@prathimacode-hub please assign me this issue

**Comment by prathimacode-hub** [comment]
Issue assigned @abhisheks008
