### ISSUE TITLE
Diamond Price Prediction

### ISSUE THREAD

**Issue by Jagannath8** [prathimacode-hub/ML-ProjectKart#285]
Define You:

- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

Diamond Price Prediction - Predicting the price of Diamond 
The project will predict the price of Diamond on multiple parameters.
Dataset: https://www.kaggle.com/shubhankitsirvaiya06/diamond-price-prediction

**Describe the solution you'd like...**

I will create models use Regression algorithms to predict the price of Diamond.
I would also try for backend.

**Comment by Jagannath8** [comment]
Can I work on this issue?

**Comment by prathimacode-hub** [comment]
Sure, you can go ahead.
