### ISSUE TITLE
Concrete Strength Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#29]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/prathamtripathi/regression-with-neural-networking) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper [project structure](https://github.com/prathimacode-hub/ML-ProjectKart#project-structure) for code as well as for the README.
Happy coding :)

**Comment by ayushi424** [comment]
Hello, I would like to work on this issue.
Please assign @prathimacode-hub.

**Comment by prathimacode-hub** [comment]
What's the task you will be working on? Model creation or front end or back end or designing @ayushi424

**Comment by ayushi424** [comment]
I would like to work on model creation for prediction.

**Comment by prathimacode-hub** [comment]
Ok, that's good. Issue is assigned to you. @ayushi424
