### ISSUE TITLE
Test Score Prediction

### ISSUE THREAD

**Issue by Isha307** [prathimacode-hub/ML-ProjectKart#290]
Title: Test Score Prediction
About: Prediction of Test Score of student.
Name: Isha Shaw
Label: Feature Request
Assignee: 'Isha307'

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

The aim of project is to build machine learning algorithms to predict the scores of the students.

[Dataset](https://www.kaggle.com/kwadwoofosu/predict-test-scores-of-students) contains information about a test written by some students. It include features such as: School setting, School type, gender, pretetest scores among other.

**Comment by Isha307** [comment]
> Title: Predict Test Score
> About: Prediction of Test Score of student.
> Name: Isha Shaw
> Label: Feature Request
> Assignee: 'Isha307'
> 
> Define You:
> 
> * [x]  LGM-SOC'21 Participant
> * [ ]  Contributor
> 
> The aim of project is to build machine learning algorithms to predict the scores of the students.
> 
> [Dataset](https://www.kaggle.com/kwadwoofosu/predict-test-scores-of-students) contains information about a test written by some students. It include features such as: School setting, School type, gender, pretetest scores among other.

@prathimacode-hub Can I work on this issue?

**Comment by prathimacode-hub** [comment]
Yeah, you can proceed. Keep the project title as "Test Score Prediction" @Isha307
