### ISSUE TITLE
IPL Winner Prediction

### ISSUE THREAD

**Issue by Soumayan-pal01** [prathimacode-hub/ML-ProjectKart#297]
---
Title: IPL Winner Prediction
About: To predict the winning team in an IPL match
Name: Soumayan Pal
Label: Feature Request
Assignee: 'Soumayan-pal01'

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**The aim of this project will be to predict the team that will win in an IPL match**

**Will be using a dataset containing match data between 2008 to 2020. Use different EDA techniques to make an analysis of the dataframe and perform visualizations on the training data. Lastly will use multiple ML models to train the Winner Predictor and perform a comparative analysis.**

**Comment by suy1968** [comment]
Please assign me this issue as I am a participant of LGMSOC'21

**Comment by Soumayan-pal01** [comment]
@suy1968 You can work on issues open by the Project Admin and Mentor or open your new issue and work on it mate.

**Comment by Soumayan-pal01** [comment]
I will be working on 'Model Creation' for this issue @prathimacode-hub .

**Comment by prathimacode-hub** [comment]
Sure, @Soumayan-pal01. Issue is assigned.

**Comment by prathimacode-hub** [comment]
@suy1968, you can come up with new issue or show your interest on available issues.

**Comment by SuryanshNaugraiya** [comment]
@prathimacode-hub i have already implemented all the above mentioned tasks and created an end to end project in which i have compared different ML algorithms and implemented the best algorithm. please assign the task to me. I want to contribute to this
![Screenshot (254)](https://user-images.githubusercontent.com/53707393/124263627-2389cf00-db51-11eb-862f-66ba6c74b80d.png)
![Screenshot (255)](https://user-images.githubusercontent.com/53707393/124263637-2684bf80-db51-11eb-9041-e34a56539646.png)
![Screenshot (256)](https://user-images.githubusercontent.com/53707393/124263649-284e8300-db51-11eb-884f-147bad85d15f.png)
![Screenshot (257)](https://user-images.githubusercontent.com/53707393/124263656-2a184680-db51-11eb-957d-522aadfba67e.png)
![Screenshot (258)](https://user-images.githubusercontent.com/53707393/124263660-2c7aa080-db51-11eb-9880-955f83e1b6cb.png)
![Screenshot (259)](https://user-images.githubusercontent.com/53707393/124263669-2e446400-db51-11eb-9f0a-a9ad4079e4cf.png)
![Screenshot (263)](https://user-images.githubusercontent.com/53707393/124263681-31d7eb00-db51-11eb-870e-1e88f80050d0.png)
![Screenshot (264)](https://user-images.githubusercontent.com/53707393/124263689-33a1ae80-db51-11eb-8faf-57a8284323a2.png)
![Screenshot (265)](https://user-images.githubusercontent.com/53707393/124263703-36040880-db51-11eb-85b5-afb4b5dd54bb.png)
![Screenshot (266)](https://user-images.githubusercontent.com/53707393/124263709-37cdcc00-db51-11eb-82a3-5b7237287e95.png)
![Screenshot (267)](https://user-images.githubusercontent.com/53707393/124263715-39978f80-db51-11eb-93c1-26ffecb63764.png)
![Screenshot (268)](https://user-images.githubusercontent.com/53707393/124263720-3bf9e980-db51-11eb-930f-fc1dffef4d34.png)
