### ISSUE TITLE
World Poverty Analysis

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/ML-ProjectKart#298]
Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
Creating an analysis model which will analyze the world poverty.

**Describe the solution you'd like...**
An analysis based on various datasets, which will show the poverty of the world's population.

**Dataset**
1. Kiva crowdfunding dataset : https://www.kaggle.com/kiva/data-science-for-good-kiva-crowdfunding
2. Multidimensional poverty measures : https://www.kaggle.com/ophi/mpi
3. World population : https://www.kaggle.com/walla2ae/world-population

Please assign me this issue @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Wow, wonderful choice of the project. You can proceed. @abhisheks008
