### ISSUE TITLE
E-Mail Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#30]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/datatattle/email-classification-nlp) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper [project structure](https://github.com/prathimacode-hub/ML-ProjectKart#project-structure) for code as well as for the README.
Happy coding :)

**Comment by Manasi2001** [comment]
@psyduck1203 you can surely work on this, but first let me know how you are planning to proceed, what all algorithms you will use and which task you'll be working on: backend, frontend or model creation. Then, I'll assign it to you :)

**Comment by psyduck1203** [comment]
Ig Naive Bayes would be good for this project and I'll first create the model and then think of creating the frontend and backend for it.

**Comment by Manasi2001** [comment]
Okay, sounds good. But try to use at least 2 more algorithms and then compare the results among them. Also, check all the necessary templates and follow the folder structure. 
@psyduck1203 assigning it to you 👍🏻

**Comment by prathimacode-hub** [comment]
Kindly do the changes asked in your PR, before you start working on this. @psyduck1203

**Comment by prathimacode-hub** [comment]
It's been 7 days. As said, time to complete PR is only 5 days and no update since then. I already mentioned, you should update your progress once in 2 days. @psyduck1203
