### ISSUE TITLE
Students Final Grade Prediction

### ISSUE THREAD

**Issue by Isha307** [prathimacode-hub/ML-ProjectKart#301]
Title:  Students Final Grade Prediction
About:  The data is about students of math and portuguese language who are in secondary school. It contains a lot of interesting social, gender and study information about students.
that characterize each student.
Name:  Isha Shaw
Label:  Feature Request
Assignee:  'Isha307'

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

The aim of project is to  predict students final grade.

[Dataset](https://www.kaggle.com/uciml/student-alcohol-consumption) contains information about grades and all important attributes.

**Comment by prathimacode-hub** [comment]
I guess it's similar to test score prediction. @Isha307

**Comment by Isha307** [comment]
> I guess it's similar to test score prediction. @Isha307

okay, I am closing this issue.

**Comment by prathimacode-hub** [comment]
You shouldn't close issues or PR from your end. @Isha307

**Comment by Isha307** [comment]
> You shouldn't close issues or PR from your end. @Isha307

I don't know this, Sorry.
