### ISSUE TITLE
Amazon Data Analysis

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/ML-ProjectKart#304]
Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

In this will create a model which predicts the score of the particular customer.
And for this will use csv dataset which will have details about customer like his/her profile name, profile id, what's the review, and what was the summary of the product by customer

Using this data will predict the score or upvote of the customer.

will use different libraries like numpy, pandas, nltk, seaborn, matplotlib,
will be using Logistic Regression for describing and analysing the data

**Comment by akash435** [comment]
@prathimacode-hub , if this can be added then please assign this to me under LGM SOC

**Comment by prathimacode-hub** [comment]
Yeah, but you need to consider multiple algorithms to get good analysis out of it. @akash435

**Comment by akash435** [comment]
yes mam, will try to use multiple nlp and ml model
