### ISSUE TITLE
Gender Classification Project Using Conv2D

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#305]
Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

This is a DL Project for predicting if the given image is Boy/Girl ( Image Recognition ) 
Find the Data Set  [Here](https://www.kaggle.com/ashishjangra27/gender-recognition-200k-images-celeba).
I will go full-stack from making model to creating front-end for web-app
Idea: I'm planning on using convolutional neural nets, Let's see how it goes.

**Comment by prathimacode-hub** [comment]
That's great. All the best. @NEERAJAP2001
