### ISSUE TITLE
Captcha Recognition

### ISSUE THREAD

**Issue by Isha307** [prathimacode-hub/ML-ProjectKart#306]
Title: **Captcha Recognition**
About:  **Recognize the captcha letters.**
Name: Isha Shaw
Label: Feature Request
Assignee: 'Isha307'

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

The aim of project is to Recognize the captcha letters.

[Dataset](https://www.kaggle.com/fournierp/captcha-version-2-images) contains CAPTCHA images. The images are 5 letter words, and have noise. The file name is same as the image letters.

**Comment by prathimacode-hub** [comment]
This project is similar to #150. Correct me if i am wrong. @Isha307

**Comment by Isha307** [comment]
> This project is similar to #150. Correct me if i am wrong. @Isha307

Yeah, It is same.

**Comment by prathimacode-hub** [comment]
> > This project is similar to #150. Correct me if i am wrong. @Isha307
> 
> Yeah, It is same.

I am sorry to say, but u have to come up with new issue. Else wait for 20mins, I shall bring up some new issues to work on. @Isha307
