### ISSUE TITLE
Flight Delay Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#31]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/usdot/flight-delays?select=flights.csv) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper [project structure](https://github.com/prathimacode-hub/ML-ProjectKart#project-structure) for code as well as for the README.
Happy coding :)

**Comment by Sumit11081996** [comment]
@prathimacode-hub  can you assign me this.

**Comment by prathimacode-hub** [comment]
You are up for Model Creation? @Sumit11081996

**Comment by Sumit11081996** [comment]
Yes @prathimacode-hub

**Comment by Manasi2001** [comment]
Go ahead @Sumit11081996 👍🏻

**Comment by shivani6320** [comment]
Hello. I would like to contribute to this project as aLGMSOC21 Participant. Please assign me this issue. Thank you.

**Comment by prathimacode-hub** [comment]
Are you sure you want to work on this issue? Kindly say your approach you would follow, algorithms you would consider and and the task you are going to choose? Then, it can be assigned to you. 
@shivani6320

**Comment by shivani6320** [comment]
I would first perform Exploratory data analysis and data visualizations to gain insights from the data. I can use ensemble modeling approach and use various Classification models like RandomForest,KNN,NaiveByes, Catboost,Adaboost, GradientBoost Classifier- to predict future delays in flights.Which ever model gives better results, I will move forward with it.

**Comment by Manasi2001** [comment]
Go ahead @shivani6320 👍🏻
