### ISSUE TITLE
Parkinson's Disease Prediction 

### ISSUE THREAD

**Issue by Akash20x** [prathimacode-hub/ML-ProjectKart#310]
Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

I want to make a model for Parkinson's Disease Prediction which can predict if a patient is healthy or have a parkinson disease by analysing the biomedical voice measurements given in the dataset. I will use Parkinson’s Disease Data Set from kaggle for making this model. 

**Describe the solution you'd like...**

I will use logistic regression, svm, random forest, decision tree and more and compare them which one will give better accuracy for prediction.

**Comment by Akash20x** [comment]
@prathimacode-hub Please assign me this issue

**Comment by prathimacode-hub** [comment]
This is already done. You can come up with an another issue. @Akash20x

**Comment by Akash20x** [comment]
> This is already done. You can improve on [this](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Parkinson's%20Disease%20Prediction) as a enhancement or you can come up with an another issue. @Akash20x

Oh I forget to check that it is already present in repo. OK I will choose another issue

**Comment by prathimacode-hub** [comment]
> > This is already done. You can improve on [this](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Parkinson's%20Disease%20Prediction) as a enhancement or you can come up with an another issue. @Akash20x
> 
> Oh I forget to check that it is already present in repo. OK I will choose another issue

No worries, but never close issue or PR from your end. Not all will take it positive, just letting you know. @Akash20x

**Comment by Akash20x** [comment]
> > > This is already done. You can improve on [this](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Parkinson's%20Disease%20Prediction) as a enhancement or you can come up with an another issue. @Akash20x
> > 
> > 
> > Oh I forget to check that it is already present in repo. OK I will choose another issue
> 
> No worries, but never close issue or PR from your end. Not all will take it positive, just letting you know. @Akash20x

OK i will take care of this from next time.
Thanks for informing!
