### ISSUE TITLE
Amazon Mobile Phones Reviews Analysis

### ISSUE THREAD

**Issue by drashtipatel2503** [prathimacode-hub/ML-ProjectKart#311]
Define You:

- [✓ ] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

I will create a sentiment analyser model which will be train on around 3L dayta points, will output whether a customer is satisfied or not.

Will use flask for deployment n html,css for frontend.

**Comment by prathimacode-hub** [comment]
What's the product you're reviewing @drashtipatel2503

**Comment by drashtipatel2503** [comment]
Food items and electronic gadgets

**Comment by prathimacode-hub** [comment]
> Food items and electronic gadgets

If you're ok with electronic gadgets, you can let me know and also you'll reviewing from which website? @drashtipatel2503

**Comment by drashtipatel2503** [comment]
I can use miTv reveiws from flipkart available on kaggle,
Headphones and smartphone reviews from amazon available on kaggle.

**Comment by prathimacode-hub** [comment]
That's cool. Change the issue title to proper project name. Then I can assign the issue accordingly. @drashtipatel2503

**Comment by drashtipatel2503** [comment]
Done

**Comment by prathimacode-hub** [comment]
> Done

Your issue title isn't changed yet. @drashtipatel2503

**Comment by drashtipatel2503** [comment]
I have changed now!

**Comment by prathimacode-hub** [comment]
> I have changed now!

Change the title to "Amazon Mobile Phones Review Analysis"
