### ISSUE TITLE
Paris Housing Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#313]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/mssmartypants/paris-housing-classification) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by anishamurmu13** [comment]
I will create models using different ML algorithms and compare their accuracy.
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. @anishamurmu13
