### ISSUE TITLE
Scores Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#315]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/saurabh778/student-score-prediction-using-linear-regression) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Jagannath8** [comment]
I will create models use Regression algorithms to predict the scores.
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Can you take up an another issue to work on. This issue is already done. Sorry for the inconvenience. @Jagannath8
