### ISSUE TITLE
Body Fat Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#316]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/fedesoriano/body-fat-prediction-dataset) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Jagannath8** [comment]
I will create models use Regression algorithms to predict the body fat of humans.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. Good choice of the project. @Jagannath8
