### ISSUE TITLE
Appliances Energy Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#318]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/sohommajumder21/appliances-energy-prediction-data-set) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using different types of classification algorithms to deploy the models and then will be checking the accuracy using the accuracy scores. 
Task Taken : Model Creation
Issue #318

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
