### ISSUE TITLE
Football Teams Rating

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#319]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/varpit94/football-teams-rankings-stats) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Jagannath8** [comment]
I will create models use Regression algorithms to predict Football Teams Rating.
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Already an issue is assigned to you. You can work on this, after you create your earlier PR. @Jagannath8

**Comment by Jagannath8** [comment]
okay @prathimacode-hub mam, after making that PR I'll work on this issue.

**Comment by prathimacode-hub** [comment]
Are u interested to work on this issue as said earlier? @Jagannath8

**Comment by Jagannath8** [comment]
yes mam

**Comment by prathimacode-hub** [comment]
Assigned. @Jagannath8
