### ISSUE TITLE
Ice Cream Revenue Prediction

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#32]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/vinicius150987/ice-cream-revenue) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper [project structure](https://github.com/prathimacode-hub/ML-ProjectKart#project-structure) for code as well as for the README.
Happy coding :)

**Comment by raunak51299** [comment]
I would like to work on this. Please assign me on 10th.

**Comment by prathimacode-hub** [comment]
Go through the pinned message in project channel. I have cleared mentioned in the enclosed document. The one who expresses their interest to work on a particular issue first on 10th june, after 10AM would be assigned to this issue. So stay tuned and all the best. This is to be fair with everyone. @raunak51299

**Comment by raunak51299** [comment]
Hello, I would like to work on this issue.

**Comment by prathimacode-hub** [comment]
What's the task you had choosen? Model creation or Front end or Back end or Designing. Let me know it when you raise a issue, so that it would be easier for me to assign. @raunak51299

**Comment by raunak51299** [comment]
I have chosen model creation using linear regression, polynomial regression etc.

**Comment by prathimacode-hub** [comment]
Ok, that's great. I shall keep this on hold. Once you finish the PR of heart disease prediction with changes mentioned. I shall assign you with this issue @raunak51299

**Comment by raunak51299** [comment]
Can I work on this issue?

**Comment by raunak51299** [comment]
---
Title: Ice Cream Revenue Prediction
About:  I would like to make a model to predict ice cream revenue using various linear regression techniques
Name: Raunak Singh
Label: Feature Request
Assignee: 

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**<br>
I would use  use linear regression and polynomial regression from sklearn module to train over the dataset  and then draw comparison between them.

 Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Issue is assigned to you. @raunak51299
