### ISSUE TITLE
Forest Fire Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#323]
Hey LGM-SoC participants, good to see you.

This project will help us in predicting the forest fire using the reported forest fires from brazil dataset

Dataset : https://www.kaggle.com/gustavomodelli/forest-fires-in-brazil

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Isha307** [comment]
> Hey LGM-SoC participants, good to see you.
> 
> This project will help us in predicting the forest fire using the reported forest fires from brazil dataset
> 
> Dataset : https://www.kaggle.com/gustavomodelli/forest-fires-in-brazil
> 
> If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.
> 
> Enjoy your open source journey!😎

@prathimacode-hub I would like to work on this issue. I will work on model creation.

Can I work on this issue?

**Comment by prathimacode-hub** [comment]
Yes, sure. Issue assigned. @Isha307
