### ISSUE TITLE
Solar Radiation Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#324]
Hey LGM-SoC participants, good to see you.

This project will help us in predicting the solar radiation using the given dataset provided.

Dataset : https://www.kaggle.com/dronio/SolarEnergy

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by anishamurmu13** [comment]
I will work on model creation and backend using regression algorithms.
Can I work on this issue? 
I'm a participant of LGM-SOC21

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub .Assign me this issue if possible for model creation.

**Comment by prathimacode-hub** [comment]
Since, it's on FCFS basis, issue is assigned to @anishamurmu13 

Sorry, you can take up an another issue to work on. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
Actually @anishamurmu13 requested to work on 2 issues at the same time, this and #313 and she was assigned #313 as its showing. So I though this request of her would be counted void. Therefore, I posted my comment @prathimacode-hub .

**Comment by Soumayan-pal01** [comment]
Yeah sure @prathimacode-hub , my bad.

> Since, it's on FCFS basis, issue is assigned to @anishamurmu13
> 
> Sorry, you can take up an another issue to work on. @Soumayan-pal01

**Comment by prathimacode-hub** [comment]
I understand, but she has completed her earlier issue taken up, so I did assign this issue after checking for the same. I assure you, that I'll be fair whoever it is. So don't feel bad about it. I shall sum up more issues to work on. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
No its Okay...Actually it was a misinterpretation on my side, as I considered the pull request timing.
