### ISSUE TITLE
Soil Moisture Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#325]
Hey LGM-SoC participants, good to see you.

This project will help us in predicting the soil moisture data using dataset provided.

Dataset : https://www.kaggle.com/amirmohammdjalili/soil-moisture-dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub Please assign me this issue if possible. Will be using the comparative analysis of multiple classifiers.

**Comment by prathimacode-hub** [comment]
Definitely, issue assigned. @Soumayan-pal01
