### ISSUE TITLE
Cervical Cancer Risk Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#326]
Hey LGM-SoC participants, good to see you.

This project will help us in predicting the risk of cervical cancer using the provided dataset

Dataset : https://www.kaggle.com/loveall/cervical-cancer-risk-classification

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using different types of classification algorithms to deploy the models and then will be checking the accuracy using the accuracy scores. 
Task Taken : Model Creation
Issue #326


Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Yes, issue assigned. @abhisheks008
