### ISSUE TITLE
Airbus Ship Detection

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#327]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in detecting the airbus ship using the dataset given

Dataset : https://www.kaggle.com/c/airbus-ship-detection/data

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by Soumayan-pal01** [comment]
Assign me this issue for model creation if possible @prathimacode-hub .

**Comment by prathimacode-hub** [comment]
Sure, issue assigned. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub the dataset is very large 28 GB and my system is lagging a lot after loading the images in local/online platforms in spite of having a high configuration. Have tried several times but same issue every time. Would like to drop this issue and take up a new one.

**Comment by prathimacode-hub** [comment]
Ok, that's upto you. No worries. You can take up a new issue. @Soumayan-pal01
