### ISSUE TITLE
Black Friday Sales - Analysis and Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#329]
Hey LGM-SoC participants, good to see you.

This project will help us in analyzing and predicting the black friday sales using the provided dataset

Dataset : https://www.kaggle.com/sdolezel/black-friday

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by Jagannath8** [comment]
I will create models use Regression algorithms to predict Black Friday Sales.
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
I guess already an issue is assigned to you. @Jagannath8

**Comment by Jagannath8** [comment]
> I guess already an issue is assigned to you. @Jagannath8

yes @prathimacode-hub mam

**Comment by ayushi424** [comment]
Hey @prathimacode-hub,
I'd like to work on this issue, mainly on model creation part.
I'll proceed by data exploration, data cleaning(if required), data visualization to draw insights of the given data, model creation using different prediction algorithms and lastly perform accuracy check to find which algorithm works best.
Please assign.

**Comment by prathimacode-hub** [comment]
Yes, this issue is assigned to you. @ayushi424
