### ISSUE TITLE
Plant Disease Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#330]
Hey LGM-SoC participants, good to see you.

This project will help us in predicting the plant diseases using the given dataset

Dataset : https://www.kaggle.com/vipoooool/new-plant-diseases-dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by Anshal55** [comment]
Hey @prathimacode-hub  Please assign me this issue . I'd like to build an efficient cnn model to classify these images and deploy it with flask.

**Comment by prathimacode-hub** [comment]
Sure, issue assigned. @Anshal55
