### ISSUE TITLE
Kidney Stone Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#347]
Hey LGM-SoC participants, good to see you.

This project will help us in predicting the kidney stones using the given dataset

Dataset : https://www.kaggle.com/utkarshxy/kidney-stone-data

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using different types of classification algorithms to deploy the models and then will be checking the accuracy using the accuracy scores. 
Task Taken : Model Creation
Issue #347


Please assign me this issue.

**Comment by Manasi2001** [comment]
Go ahead @abhisheks008.
