### ISSUE TITLE
Laptop Prices Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#348]
Hey LGM-SoC participants, good to see you.

This project will help us in predicting the laptop prices from wide range of models using the given dataset

Dataset : https://www.kaggle.com/ionaskel/laptop-prices

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using different types of regression algorithms to deploy the models and then will be checking the accuracy using the accuracy scores. 
Task Taken : Model Creation
Issue #348


Please assign me this issue.

I'll work on this issue after #347

**Comment by abhisheks008** [comment]
Ma'am Please assign me this issue!

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
