### ISSUE TITLE
Mall Customer Segmentation

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#349]
Hey LGM-SoC participants, good to see you.

This project should help us in segmenting the customers taking the parameters into consideration

Dataset : You can take up a public dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using good visualizations and classifying efficiently.

**Comment by Rutikab12** [comment]
Hey, @prathimacode-hub I want to work on this issue.

**Comment by prathimacode-hub** [comment]
Sure, issue assigned. @Rutikab12
