### ISSUE TITLE
Text Summarization

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#351]
Hey LGM-SoC participants, good to see you.

This project will help us in summarizing the text into concise manner using the BBC Dataset.

Dataset : https://www.kaggle.com/pariza/bbc-news-summary

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using  **Sequence to Sequence Model** [Seq2Seq] for creating the Text Summarization project. 
Task Taken : Model Creation
Issue #351


Please assign me this issue.

**Comment by abhisheks008** [comment]
I'll work on it after #348

**Comment by prathimacode-hub** [comment]
Sure. @abhisheks008

**Comment by abhisheks008** [comment]
Please assign me this issue!

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
