### ISSUE TITLE
Book Recommendation Systems

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#352]
Hey LGM-SoC participants, good to see you.

This project will help us in recommending and suggesting the good books based on dataset provided.

Dataset : https://www.kaggle.com/jealousleopard/goodreadsbooks

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using different types of classification algorithms to deploy the model and then will be checking the accuracy using the accuracy scores. 
Algorithms : 
1. KNN
2. t-SNE
3. DBSCAN


Task Taken : Model Creation
Issue #352


Please assign me this issue.

I'll work on this issue after #351

**Comment by abhisheks008** [comment]
Please assign me this issue!

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
