### ISSUE TITLE
Dry Beans Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#353]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/josegarban/beans-classification) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Jagannath8** [comment]
I'll use different ML algorithms to classify dry beans and compare their accuracy.
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Already an issue is assigned to you. You can work on this, once you finish that if issue is open by then. @Jagannath8

**Comment by Jagannath8** [comment]
okay @prathimacode-hub mam, after making that PR I'll work on this issue.

**Comment by prathimacode-hub** [comment]
Do you want to work on this issue now? @Jagannath8

**Comment by Jagannath8** [comment]
Yes mam

**Comment by prathimacode-hub** [comment]
Issue assigned. @Jagannath8
