### ISSUE TITLE
Airbnb Price Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#354]
Hey LGM-SoC participants, good to see you.

This project will help us in predicting the airbnb prices using the provided dataset

Dataset : https://www.kaggle.com/stevezhenghp/airbnb-price-prediction

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using different types of regression and neural network algorithms to deploy the model and then will be checking the accuracy using the accuracy scores. 
Algorithms : 
1. Linear Regression
2. Random Forest
3. Gradient Boosting
4. Support Vector Regressor
5. Dense Neural Network


Task Taken : Model Creation
Issue #354


Please assign me this issue.

I'll work on this issue after #352

**Comment by prathimacode-hub** [comment]
Ok, sure. @abhisheks008

**Comment by abhisheks008** [comment]
PLEASE assign me this issue

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
