### ISSUE TITLE
Balls Image Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#355]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/gpiosenka/balls-image-classification) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using dense neural network algorithm [MobileNetV2] along with OpenCV to deploy the model and then will be checking the accuracy using the accuracy scores. 

Task Taken : Model Creation
Issue #355

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
