### ISSUE TITLE
Male & Female Eyes Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#358]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/pavelbiz/eyes-rtte) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using different types neural network algorithms to deploy the model and then will be checking the accuracy using the accuracy scores. 
Architectures : 
1. ConvNet
2. Inception
3. MobileNet
4. Xception


Task Taken : Model Creation
Issue #358


Please assign me this issue.

**Comment by abhisheks008** [comment]
I'll work on this issue after #355

**Comment by prathimacode-hub** [comment]
Ok, sure. @abhisheks008

**Comment by abhisheks008** [comment]
please assign me this issue

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
