### ISSUE TITLE
Twitch Streamer Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#359]
Hey LGM-SoC participants, good to see you.

This project will help us in analyzing the twitch streamers using the dataset given.

Dataset : https://www.kaggle.com/aayushmishra1512/twitchdata

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by Jagannath8** [comment]
I'll use different Regression algorithms to predict how many followers gained by stream.
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Ok, sure also do the overall analysis of the twitch streams. Issue is assigned. @Jagannath8

**Comment by Jagannath8** [comment]
okay mam
