### ISSUE TITLE
English Alphabet Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#360]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/nachiketkanore/english-alphabets-computerized) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Soumayan-pal01** [comment]
Would like on 'Model creation' for this issue @Manasi2001 . Will be using MLP and CNN models to make the classification and then compare their results. Assign me this issue if possible. Thank you.

**Comment by prathimacode-hub** [comment]
Sure, issue assigned. @Soumayan-pal01
