### ISSUE TITLE
Password Strength Classifier

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#361]
Hey LGM-SoC participants, good to see you.

This project will help us in classying the password strength from the given dataset

Dataset : https://www.kaggle.com/bhavikbb/password-strength-classifier-dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by akash435** [comment]
@prathimacode-hub can i work on this issue?

**Comment by Manasi2001** [comment]
Go ahead @akash435.

**Comment by akash435** [comment]
yes mam
