### ISSUE TITLE
Marble Surface Anomaly Detection

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#362]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/wardaddy24/marble-surface-anomaly-detection-2) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using neural network algorithms to deploy the model and then will be checking the accuracy using the accuracy scores. 
Architectures : EfficientNet

Task Taken : Model Creation
Issue #362

Please assign me this issue.

I will work on this issue after #358

**Comment by prathimacode-hub** [comment]
Definitely. @abhisheks008

**Comment by abhisheks008** [comment]
Please assign me this issue

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
