### ISSUE TITLE
Persian License Plate Characters Identification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#363]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/amirebrahimi66/large-dataset-of-persian-license-plate-characters) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using neural network algorithms to deploy the model and then will be checking the accuracy using the accuracy scores. 
Architectures : EfficientNet B1

Task Taken : Model Creation
Issue #363

Please assign me this issue.

I will work on this issue after #362

**Comment by prathimacode-hub** [comment]
Sure. @abhisheks008

**Comment by abhisheks008** [comment]
Please assign me this issue

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
