### ISSUE TITLE
Automated Essay Grading

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#364]
Hey LGM-SoC participants, good to see you.

This project will help us in grading the essay automatically using machine learning

Dataset : https://www.kaggle.com/c/asap-aes/data

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by Akash20x** [comment]
@prathimacode-hub  Please assign me this issue as a part of LGM-SOC'21

I want to build a model to predict score for the essay. I will use models like SVR, LSTM, word2vec, XGBClassifier and RNN and compare them in terms of their accuracy and their cohen kappa score.

**Comment by prathimacode-hub** [comment]
Issue assigned. You can proceed. @Akash20x
