### ISSUE TITLE
Vehicle Image Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#365]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/lyensoetanto/vehicle-images-dataset) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by Soumayan-pal01** [comment]
I would like to work on 'Model Creation' for this issue. Assign me this issue if possible @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned. @Soumayan-pal01
