### ISSUE TITLE
Endangered Right Whales Classification

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#367]
Hey LGM-SoC participants, good to see you.

This project will help us in recognizing and classifying the endangered right whales from the dataset provided.

Dataset : https://www.kaggle.com/c/noaa-right-whale-recognition/data

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by rammya29** [comment]
Please assign this task to me. I would like to work under this project as LGM-SoC . I would like to solve this as a creating a model first by extracting features and doing multiclass classification.

**Comment by prathimacode-hub** [comment]
Issue assigned. @rammya29

**Comment by prathimacode-hub** [comment]
Its been 18days since issue is assigned. @rammya29

**Comment by prathimacode-hub** [comment]
Update please? @rammya29

**Comment by rammya29** [comment]
Sorry mam, busy with exams. Assign to someone else mam. Sorry for inconvenience
