### ISSUE TITLE
Shoulder X-ray Classification

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#368]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/dryari5/shoulder-xray-classification) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by abhisheks008** [comment]
@prathimacode-hub and @Manasi2001 I am up for this issue.
Approach : I will be using neural network algorithms to deploy the model and then will be checking the accuracy using the accuracy scores. 
Architectures : EfficientNet B1

Task Taken : Model Creation
Issue #368

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Already Captcha Decoding is assigned, you can work on this once you complete that issue. @abhisheks008

**Comment by abhisheks008** [comment]
Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
