### ISSUE TITLE
Gender Recognition

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/ML-ProjectKart#369]
Hey LGM-SOC participant, great to have you here! 😀
If you feel like working on this issue, you may refer to this [dataset](https://www.kaggle.com/rashikrahmanpritom/gender-recognition-dataset) or any other dataset of your choice. Try to use at least 3-4 algorithms and draw comparisons between them all. Don't forget to follow proper project structure for code as well as for the README.
Happy coding :)

**Comment by prathimacode-hub** [comment]
@Manasi2001, this is already done.
