### ISSUE TITLE
Uber Fare Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#37]
Hey LGM-SoC participants, good to see you.

This project predicts the fare from source to destination in new york city.

Dataset : https://www.kaggle.com/c/new-york-city-taxi-fare-prediction/data

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub  Please assign me this issue if possible. I have worked on various fare prediction models before and would love to work on this project.

**Comment by prathimacode-hub** [comment]
Glad to know. Express you interest from tomorrow, starting 10AM. It would be assigned on first come first serve basis. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub I would really like to work on 'Model Creation' for this issue as a LGM-SOC participant to predict the fare using different exploratory data analysis techniques to analyse the dataframe and perform data preprocessing to get good accuracy using Random forest, KNN, and other approaches. Would be using the concept of Hyperparameter tuning to increase the efficiency of the model. Please assign me this issue if possible. Thank you.

**Comment by Sumit11081996** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by Soumayan-pal01** [comment]
> Hey @prathimacode-hub I would really like to work on 'Model Creation' for this issue as a LGM-SOC participant to predict the fare using different exploratory data analysis techniques to analyse the dataframe and perform data preprocessing to get good accuracy using Random forest, KNN, and other approaches. Would be using the concept of Hyperparameter tuning to increase the efficiency of the model. Please assign me this issue if possible. Thank you.

Can I work on this issue now @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Yes, you can work on this issue. This issue is assigned to you. @Soumayan-pal01

**Comment by prathimacode-hub** [comment]
Sure. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub I have created the PR. Please review it. Thank you.

**Comment by prathimacode-hub** [comment]
Let me check on it. @Soumayan-pal01
