### ISSUE TITLE
Social Network Influencers Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#371]
Hey LGM-SoC participants, good to see you.

This project will help us in predicting the influential people in social networks

Dataset : https://www.kaggle.com/c/predict-who-is-more-influential-in-a-social-network/data

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by Isha307** [comment]
Can I work on this issue @prathimacode-hub ?

I would like to work on model creation.

**Comment by prathimacode-hub** [comment]
Yes, sure issue assigned. @Isha307
