### ISSUE TITLE
Cats Vs Dogs Classification

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#38]
Hey LGM-SoC participants, good to see you.

With this project you should be able to classify whether images contain either a dog or a cat.

Dataset : https://www.kaggle.com/chetankv/dogs-cats-images

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Chanakya-Sharma** [comment]
Can you assign me this

**Comment by prathimacode-hub** [comment]
Issues will assigned from tomorrow according to guidelines on first come first serve basis.

**Comment by sy07** [comment]
Hi mam, I would like to work on this issue as LGM-SOC'21 participant from June 10. Do assign me if possible.
Thank You!

**Comment by prathimacode-hub** [comment]
Good to see your interest with the issue. But assignment to issues for ML-ProjectKart would start from June10th, 10AM. It would be on FCFS basis. So be prompt enough to respond after the given time. Only participants who expresses their interest first after 10AM would be assigned with the issue. Also I had added up an enclosed document of things you need to follow. It's pinned to the project channel in slack. Do check it out and keep it as a reference. @sy07

**Comment by sy07** [comment]
> Good to see your interest with the issue. But assignment to issues for ML-ProjectKart would start from June10th, 10AM. It would be on FCFS basis. So be prompt enough to respond after the given time. Only participants who expresses their interest first after 10AM would be assigned with the issue. Also I had added up an enclosed document of things you need to follow. It's pinned to the project channel in slack. Do check it out and keep it as a reference. @sy07

Okay mam,
Thank You

**Comment by Anshal55** [comment]
I am a ‘LGM-SOC participant’. How can this issue be assigned to me?

**Comment by raunak51299** [comment]
---
Title: Cats Vs Dogs Classification
About:  I would like to make a CNN model to classify Cats and Dogs Images
Name: Raunak Singh
Label: Feature Request
Assignee: 

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

 Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Yup, this issue is assigned to you. All the best. ✔@raunak51299
