### ISSUE TITLE
Employee Attrition Predictor

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/ML-ProjectKart#381]
Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

In this will create a model which will predict whether the employee is going to leave the company or not.

Will use the dataset from here https://www.kaggle.com/pranavsai98/predicting-employee-status

will use data of employee like 'status' – 
status (Employed / Left)
which department
salary
tenure
satisfaction
lastevaluation

and predict the attrition of the employee.

will use different model like DecisionTree, Random Forest and other for prediction

**Comment by akash435** [comment]
@prathimacode-hub , sorry this was already done

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub , sorry this was already done

Yes, its already done [here](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Employee%20Retention%20Project)
