### ISSUE TITLE
Tweets Sentiment Analysis Prediction

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#383]
Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
This project is done long back. You can choose up from any of the issues up for grabs, else come up with a new issue. But make sure, it's not available in the repo. @aryantiwari10

**Comment by aryantiwari10** [comment]
Hello I want to work on the hotel booking prediction
Can I do that please tell??

**Comment by prathimacode-hub** [comment]
Yes, you can. But be clear with project title, create an issue using template and get it assigned. @aryantiwari10
