### ISSUE TITLE
Fake JobPosting Prediction

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/ML-ProjectKart#387]
Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

In this will create a model for predicting real or fake job posting.

will user this dataset https://www.kaggle.com/shivamb/real-or-fake-fake-jobposting-prediction

And will use algorithm like logistic regression , Decision tree, random forest,.

**Comment by akash435** [comment]
@prathimacode-hub @Manasi2001 can i work on this issue for model creation.

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. Interesting issue. @akash435
