### ISSUE TITLE
License Plate Detection and Recognition

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#39]
Hey LGM-SoC participants, good to see you.

The project helps in the locating the  license plate and extracting the number of the plate when provided with a vehicle image. 

Dataset : Use the public dataset to work on.

If you like to work on this issue, follow the given guidelines for code as well as for the README. 

Enjoy your open source journey!😎

**Comment by Nomulacharitha** [comment]
Can you assign me this issue

**Comment by prathimacode-hub** [comment]
What's the task you're taking? And how would you proceed with this issue? What's your approach? @Nomulacharitha

**Comment by Nomulacharitha** [comment]
Prepocessing the image and detecting the licence plate by using open cv and then performing the character recognition using pytesseract package

**Comment by prathimacode-hub** [comment]
That sounds cool, You'll be taking up a task of Model Creation or you would add up front end or back end as well? @Nomulacharitha

**Comment by Nomulacharitha** [comment]
Model Creation

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can proceed. @Nomulacharitha
