### ISSUE TITLE
Hotel Booking Prediction

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#392]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

**Describe the Bug**

**Steps to Reproduce**

1. 
2. 
3. 
4. 

**Expected Behavior**

**Actual Behavior**

**Screenshots**

**Additional Details**

**Comment by prathimacode-hub** [comment]
This an empty and wrong template you had choosen. Kindly correct it and describe about your project, your approach, algos you would work on and issue you are taking up. @aryantiwari10

**Comment by aryantiwari10** [comment]
Now I have updated please have a look at it
