### ISSUE TITLE
Exploratory Data Analysis on Titanic survival

### ISSUE THREAD

**Issue by Shivani-Khare** [prathimacode-hub/ML-ProjectKart#394]
@prathimacode-hub Please assign me this issue. I am a part of LGM-SoC'21. I really wish to work on this issue.

**Comment by prathimacode-hub** [comment]
This is done long back. You can take up an another issue to work or choose from existing up for grabs issues. Also while raising an issue, follow the template provided in README file with detailed description of what your project is. Do make sure project isn't in the repo, before creating an issue. @Shivani-Khare

**Comment by prathimacode-hub** [comment]
You should never close an issue or PR from your end. That's against the norm. Not all would take this positive. @Shivani-Khare

**Comment by Shivani-Khare** [comment]
Alright. Wasn't aware. Apologies. @prathimacode-hub

**Comment by prathimacode-hub** [comment]
No worries, I just wanted to let you know. Apologises aren't needed. That's how you learn right. @Shivani-Khare

**Comment by Shivani-Khare** [comment]
Yep, Thankyou. @prathimacode-hub
