### ISSUE TITLE
Hotel Booking Prediction

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#395]
Define You: My name is Aryan Tiwari . I am a data science and machine learning enthusiast and currently pursuing B.Tech from Srm University , I am in 3rd year and my branch is computer science.

- [x] LGM-SOC'21 Participant : YES
- [ ] DevIncept Participant
- [ ] Contributor

Plz assign this project to me I want to contribute it
PROJECT TITLE : Hotel Booking Prediction

GOAL : To predict the possibility of the booking ,whether the booking is successfull or not .

DATASET : https://www.kaggle.com/jessemostipak/hotel-booking-demand

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the hotel booking dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization  and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model prediction part I used total 9 machine learning algos . In each algo I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset .

MODELS USED : I used total 9 machine leaning algos in the dataset 
1. Logistic Regression
2. KNeighborsClassifier
3. DECISION TREE CLASSIFIER
4. Random Forest Classifier
5. AdaBoostClassifier
6. Gradient Boosting Classifier
7. XGBClassifier
8. ExtraTreesClassifier
9. Bagging Classifier

LIBRARIES NEEDED :
Pandas
Numpy
Matplotlib
Seaborn
Scipy
Sklearn

CONCLUSION : I got  a accuracy score of 97 % using the Random Forest Classifier and get to know that the booking is succesful.

**Comment by prathimacode-hub** [comment]
Sure, issue is assigned to you. @aryantiwari10

**Comment by aryantiwari10** [comment]
Mam now what I have to do next can I upload the ipynb directly which I have
made?

**Comment by prathimacode-hub** [comment]
Now, you can create a PR if your project is ready. Follow the project structure given in README file of this repo.
