### ISSUE TITLE
Airline Passenger Satisfaction

### ISSUE THREAD

**Issue by Soumayan-pal01** [prathimacode-hub/ML-ProjectKart#398]
---
Title: Airline Passenger Satisfaction
About: The aim of this project is to predict whether a passenger is satisfied or not with the specific Airlines company 
Name: Soumayan Pal
Label: Feature Request
Assignee: 'Soumayan-pal01'

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**The aim of this project is to predict whether the customer is satisfied with the airlines services or not**

**A binary classification model where one class is satisfied and the other class is neutral/not satisfied**

**Will perform a detailed data analysis with different EDA approaches and visualizations. Will be using multiple classifier models to classify the satisfaction of the Airline passenegers.**

**Comment by Soumayan-pal01** [comment]
Will be working on 'Model Creation' for this issue @prathimacode-hub .

**Comment by prathimacode-hub** [comment]
Yup, issue assigned. @Soumayan-pal01
