### ISSUE TITLE
Amazon Books Analysis

### ISSUE THREAD

**Issue by Isha307** [prathimacode-hub/ML-ProjectKart#399]
Title: Amazon Top 50 Bestselling Books Analysis
About: Prediction on book to be fiction and non-fiction using Goodreads
Name: Isha Shaw
Label: Feature Request
Assignee: 'Isha307

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

The aim of project is to build machine learning algorithms to predict whether the book is fiction or non- fiction. 

[Dataset ](https://www.kaggle.com/sootersaalu/amazon-top-50-bestselling-books-2009-2019) contain Amazon's Top 50 bestselling books from 2009 to 2019. Contains 550 books, data has been categorized into fiction and non-fiction using Goodreads

**Comment by prathimacode-hub** [comment]
Change the issue title to project name. that is "Amazon Books Analysis". @Isha307

**Comment by Isha307** [comment]
> Change the issue title to project name. that is "Amazon Books Analysis". @Isha307

Sorry.
It was by mistake.

**Comment by prathimacode-hub** [comment]
No worries, issue assigned. @Isha307
