### ISSUE TITLE
Update the "Look Through the Kart of Amazing Projects" in README

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#402]
Hey, LGMSOC participants. Good to see you here.

Help needed. There are in total '107' projects listed out in the section of "Look Through the Kart of Amazing Projects" in README.md.

Currently, the repo exists with 150+ projects. If anyone is interested to take up this good first issue can forward and express your interest. And, this PR needs to be completed by 9th July, 2021.

All the best for your open source journey ahead. 😎

**Comment by khushi-purwar** [comment]
Can you please assign me this task @prathimacode-hub 

> Hey, LGMSOC participants. Good to see you here.
> 
> Help needed. There are in total '107' projects listed out in the section of "Look Through the Kart of Amazing Projects" in README.md.
> 
> Currently, the repo exists with 150+ projects. If anyone is interested to take up this good first issue can forward and express your interest. And, this PR needs to be completed by 9th July, 2021.
> 
> All the best for your open source journey ahead. 😎

Can you please assign me this issue @prathimacode-hub

**Comment by prathimacode-hub** [comment]
That's great to know. Are you an LGMSOC participant? @khushi-purwar

**Comment by khushi-purwar** [comment]
> That's great to know. Are you an LGMSOC participant? @khushi-purwar

yes @prathimacode-hub , I am a LGMSOC participant

**Comment by prathimacode-hub** [comment]
Sure,this issue is assigned to you. Follow the template as it is and add on the projects but in alphabetical order. All the best. @khushi-purwar

**Comment by khushi-purwar** [comment]
Ok. I will do it accordingly. Thank You
