### ISSUE TITLE
German Traffic Sign System

### ISSUE THREAD

**Issue by Best-forever-003** [prathimacode-hub/ML-ProjectKart#405]
Define You:

NAME: -AAMIR P
USERNAME: Best-forever-003
PROJECT: Heart Disease Prediction
LinkedIn: [](https://www.linkedin.com/in/aamir-p/)

- [x] - [ ]DevIncept Participant 
- [ ] 
- [x] - [ ] Contributor
- [ ] 

**Can you, please assign me this project Madam?**

This project will focus on predicting heart disease using neural networks. Based on attributes such as blood pressure, cholesterol levels, etc.

**Describe the solution you'd like...**

We will be using some common Python libraries, such as pandas, NumPy, and matplotlib.

**Describe alternatives you've considered?**

sklearn and Keras

Nothing Just import and work on.

I'm planning to use at least 30 attributes including age, sex, resting blood pressure,etc.

**Comment by Best-forever-003** [comment]
@prathimacode-hub Madam

**Comment by prathimacode-hub** [comment]
Why had you closed the issue? You should never close issues or PR from your end. And what are you willing to work on? By the way the contribution period for DevIncept would start from 10th of July, 2021. Also make sure, the issues you raise are not in the repo. You can take up an issues available for grabs or come up with your own issues. Issues are assigned on FCFS basis. @Best-forever-003

**Comment by Best-forever-003** [comment]
Yes @prathimacode-hub Madam, that's why I closed it. Sorry Madam

**Comment by prathimacode-hub** [comment]
> Yes @prathimacode-hub Madam, that's why I closed it. Sorry Madam

You shouldn't close it, it's against the norm. Any queries, don't hesitate to ask. @Best-forever-003

**Comment by Best-forever-003** [comment]
@prathimacode-hub can you please connect me on LinkedIn
https://www.linkedin.com/in/aamir-p/

Thanks for being a team player Madam

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub can you please connect me on LinkedIn
> https://www.linkedin.com/in/aamir-p/
> 
> Thanks for being a team player Madam

Most welcome for your humble words. Yes, sent you connection request. Kindly check it.

**Comment by Best-forever-003** [comment]
@prathimacode-hub I didn't receive Madam

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub I didn't receive Madam

I sent you. Refresh it and check on if that was ur linkedin id, you would have got.. @Best-forever-003
