### ISSUE TITLE
Handwritten Digit Recognition

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#41]
Hey LGM-SoC participants, good to see you.

The handwritten digit recognition is the ability of computers to recognize human handwritten digits. This project uses the image of a digit and recognizes the digit present in the image. 

Dataset : https://www.kaggle.com/c/mnist-handwritten-digit-recognition/data

If you like to work on this issue, follow the given guidelines for code as well as for the README.

Enjoy your open source journey!😎

**Comment by Chanakya-Sharma** [comment]
Can you assign me this

**Comment by prathimacode-hub** [comment]
Assigning issues would start from tomorrow, 10AM on first come first serve basis. So stay tuned. You will get all the details on how to get it assigned by today evening in slack channel. @Chanakya-Sharma

**Comment by Nihir2904** [comment]
Hey @prathimacode-hub, it would be great if you let me work on this issue.
Thank You.

**Comment by prathimacode-hub** [comment]
Sure, @Nihir2904. Let me know of the task you're going to work on?
Model Creation (or) Front End (or) Back End (or) Designing. So that I can assign accordingly.

**Comment by Nihir2904** [comment]
I would like to work on model creation part.

**Comment by prathimacode-hub** [comment]
Ok, sure. This issue is assigned to you. You can proceed. @Nihir2904

**Comment by Manasi2001** [comment]
Updates @Nihir2904?

**Comment by prathimacode-hub** [comment]
No updates from you. It's been so long. @Nihir2904

**Comment by prathimacode-hub** [comment]
It's been 18 days, since issue was assigned to you. No update from you yet. So unfortunately, I have to unassign you. You can take up new issues in future, if you could give your time. @Nihir2904

**Comment by shivani6320** [comment]
I would like to work on model creation part. Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Let me know of your approach to move forward? @shivani6320

**Comment by shivani6320** [comment]
i would create a CNN model to recognize the handwritten image and classify it to actual number

**Comment by prathimacode-hub** [comment]
Ok, issue assigned. @shivani6320
