### ISSUE TITLE
Diabetes Prediction 

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#412]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

PROJECT TITLE : Diabetes Prediction
plz assign this project to me .

GOAL : To predict the possibility that a person is suffering from diabetes or not.

DATASET : https://www.kaggle.com/uciml/pima-indians-diabetes-database 

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the diabetes dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model prediction part I used total 9 machine learning algos . In each algo I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset .

MODELS USED : I used total 10 machine leaning algos in the dataset

1. Logistic Regression
2. KNeighborsClassifier
3. SVC
4. Naive Bayes
5. DECISION TREE CLASSIFIER
6. RandomForestClassifier
7. AdaBoostClassifier
8. Gradient Boosting Classifier
9. XGBClassifier
10.ExtraTreesClassifier

LIBRARIES:
PANDAS
NUMPY
MATPLOTLIB
SEABORN
SCIPY
SKLEARN

CONCLUSION : I got a accuracy score of 84 % using the Logistic Regression.

**Comment by prathimacode-hub** [comment]
This is done already. Here it [is](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Diabetes%20Prediction). Before raising an issue, check if it's done in this repo so that your efforts don't go wasted. @aryantiwari10

**Comment by Manasi2001** [comment]
Hey @aryantiwari10, you may take up a new, never included before issue. Closing this duplicate one...
