### ISSUE TITLE
NBA EDA AND PREDICTION

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#413]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

PROJECT TITLE : NBA EDA AND PREDICTION
plz assign this project to me .

GOAL : To predict number of points that were scored in the season 2013-2014 by the NBA players.

DATASET : https://www.kaggle.com/razamh/unsupervised-ml

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the NBA dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model prediction part I used total 9 machine learning algos . In each algo I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset .

MODELS USED : I used total 11 machine leaning algos in the dataset

Logistic Regression
KNeighborsClassifier
SVC
Naive Bayes
DECISION TREE CLASSIFIER
RandomForestClassifier
AdaBoostClassifier
Gradient Boosting Classifier
XGBClassifier
ExtraTreesClassifier
Bagging Classifier

LIBRARIES:
PANDAS
NUMPY
MATPLOTLIB
SEABORN
SCIPY
SKLEARN

CONCLUSION : We get to know that most number of points were scored in the season 2013-2014 by the NBA players.

We get a training score of 100 % using the Random Forest Classifier and Extra Trees Classifier which is quite good.

**Comment by prathimacode-hub** [comment]
Awesome. Issue assigned. @aryantiwari10
