### ISSUE TITLE
Marathon Time Prediction

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/ML-ProjectKart#416]
Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

In this will create a model for predicting the expected Marathon time

will use this dataset https://www.kaggle.com/girardi69/marathon-time-predictions

And will use different regression algorithms like
linear regression
decision tree regression
polynomial regression

and will compare the the accuracy among them

will work on model creation.

**Comment by akash435** [comment]
@prathimacode-hub , please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
