### ISSUE TITLE
Honey Bee Pollen Detection

### ISSUE THREAD

**Issue by Soumayan-pal01** [prathimacode-hub/ML-ProjectKart#418]
---
Title: Honey Bee Pollen Detection
About: This project is all about detecting whether the honey bee is bearing pollen or not.
Name: Soumayan Pal
Label: Feature Request
Assignee: 'Soumayan-pal01'

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**The aim of this project is to detect whether the honey bee is bearing pollen or not**

**The dataset contains images of both pollen bearing and non pollen bearing honey bees.**

**Will be using Neural Networks approach to build a binary classification model**

**Comment by Soumayan-pal01** [comment]
Will be working on 'model creation' for this issue @prathimacode-hub

**Comment by Manasi2001** [comment]
Sounds good @Soumayan-pal01. Go ahead. 👍🏻

**Comment by Soumayan-pal01** [comment]
Thank you for assigning  @Manasi2001
