### ISSUE TITLE
Loan Eligibility Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#42]
Hey LGM-SoC participants, good to see you.

With this project, it helps the company in knowing whether the person is eligible for loan or not, taking various parameters in consideration.

Dataset : https://www.kaggle.com/vikasukani/loan-eligible-dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Rutikab12** [comment]
I would love to work on this issue.  Do assign me if possible.

**Comment by prathimacode-hub** [comment]
Assigning issues would start from tomorrow, 10AM on first come first serve basis. So stay tuned. You will get all the details on how to get it assigned by today evening in slack channel. @Rutikab12

**Comment by Rutikab12** [comment]
> Assigning issues would start from tomorrow, 10AM on first come first serve basis. So stay tuned. You will get all the details on how to get it assigned by today evening in slack channel. @Rutikab12

okay

**Comment by Rutikab12** [comment]
> > Assigning issues would start from tomorrow, 10AM on first come first serve basis. So stay tuned. You will get all the details on how to get it assigned by today evening in slack channel. @Rutikab12
> 
> okay

Hey @prathimacode-hub can I now work on it.

**Comment by prathimacode-hub** [comment]
It's not 10AM yet. Be prompt when it ticks the time. @Rutikab12

**Comment by Rutikab12** [comment]
okay..

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub I would really like to work on 'Model Creation' for this issue as a LGM-SOC participant to find whether the person should be given loan or not using different supervised classification ML algorithms like Decision Tree, LDA, SVC and few more. Please assign me this issue if possible. Thank you.

**Comment by Rutikab12** [comment]
> okay..

Can I now work on this issue @prathimacode-hub .Do assign me if possible.

**Comment by prathimacode-hub** [comment]
Issue is assigned to @Soumayan-pal01 on FCFS basis.

**Comment by prathimacode-hub** [comment]
@Rutikab12 Hey, you can work on other task or this task if you want to work on anything other than 'Model Creation'

**Comment by Rutikab12** [comment]
> @Rutikab12 Hey, you can work on other task or this task if you want to work on anything other than 'Model Creation'

Yes.

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub  I can go ahead with the #40 issue first so @Rutikab12 can work this issue first if he desires. Thank you.

**Comment by Rutikab12** [comment]
> Hey @prathimacode-hub I can go ahead with the #40 issue first so @Rutikab12 can work this issue first if he desires. Thank you.

Its okay @Soumayan-pal01 . I will try another issue.

**Comment by prathimacode-hub** [comment]
Ok that's collaboration. @Rutikab12 I have assigned this issue to you. And @Soumayan-pal01 with issue #40. Kudos.

**Comment by Rutikab12** [comment]
> Ok that's collaboration. @Rutikab12 I have assigned this issue to you. And @Soumayan-pal01 with issue #40. Kudos.

Okay, Thank you @Soumayan-pal01 @prathimacode-hub. In how much time I have to make PR?

**Comment by prathimacode-hub** [comment]
Max time to make a PR is 5 days. @Rutikab12

**Comment by Rutikab12** [comment]
> Max time to make a PR is 5 days. @Rutikab12

Okay.
