### ISSUE TITLE
Web Page Phishing Detection

### ISSUE THREAD

**Issue by kadatatlukishore** [prathimacode-hub/ML-ProjectKart#428]
@prathimacode-hub , I would to like to contribute this project to the repo 

Dataset: https://www.kaggle.com/manishkc06/web-page-phishing-detection

Define You:

- [ ] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
Yes, It's about web page phishing detection. Many people get scammed by this techniques. Detecting them can save people from getting scammed

**Describe the solution you'd like...**
Using multiple classification models and Comparing models. 

**Approach to be followed (optional):**
1. EDA
2. Feature Selection
3. Multiple models: Logistic Regression, Decision Tree Classifier, Random Forest Classifier etc.
4. Models comparsion

**Comment by kadatatlukishore** [comment]
Can I start working on this @prathimacode-hub ?

**Comment by prathimacode-hub** [comment]
Interesting, but needs issue template to get it assigned with the project details. The task you are taking up, approach you would follow, algos you would use. @kadatatlukishore

**Comment by kadatatlukishore** [comment]
Thanks for guidance @prathimacode-hub . Updated the template !

**Comment by prathimacode-hub** [comment]
Most welcome, so you are not any of the participants but a contibutor right? @kadatatlukishore

**Comment by kadatatlukishore** [comment]
Yes @prathimacode-hub. Thanks !

**Comment by prathimacode-hub** [comment]
Issue assigned, @kadatatlukishore
