### ISSUE TITLE
Organ Donors Prediction

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/ML-ProjectKart#429]
Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

In this will create a model for predicting the Donors using the information in the dataset.

will use this https://www.kaggle.com/momohmustapha/donorsprediction

And will use different algorithms like
linear regression
logistic regression
decision tree regression
Random Forest classifier
K Neighbor Classifier

and will compare the the accuracy among them

will work on model creation.

**Comment by akash435** [comment]
@prathimacode-hub  please assign this issue to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Is this for blood donors or organ donors? @akash435

**Comment by akash435** [comment]
Mam i think its an organ donor, by looking into the dataset
