### ISSUE TITLE
Colour Identification using Machine Learning

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#43]
Hey LGM-SoC participants, good to see you.

This project uses Machine Learning to extract a set number of colors from an image.

Dataset : https://www.kaggle.com/adityabhndari/color-detection-data-set

If you like to work on this issue, follow the given guidelines for code as well as for the README.

Enjoy your open source journey!😎

**Comment by psyduck1203** [comment]
Hey I'm a LGM-SoC participant. Can you assign me this issue!

**Comment by prathimacode-hub** [comment]
Can you elaborate of how would you do this? @psyduck1203

**Comment by psyduck1203** [comment]
We can select a point on the image and use the absolute value function to get the RGB value and match with the nearest value and predict the color. I think OpenCV and Pandas will be required.

**Comment by prathimacode-hub** [comment]
Hey you have expressed interest in two projects. Kindly decide one of them to work. Then issue will be assigned @psyduck1203

**Comment by psyduck1203** [comment]
I'll first work on this (Color Identification) and then on the other issues.

**Comment by prathimacode-hub** [comment]
What's the other project you had expressed interest for? @psyduck1203

**Comment by psyduck1203** [comment]
Drowsiness Detection using Computer Vision

**Comment by prathimacode-hub** [comment]
Ok, You want to work on model creation right? @psyduck1203

**Comment by psyduck1203** [comment]
yes

**Comment by prathimacode-hub** [comment]
Ok, this issue is assigned to you. @psyduck1203
