### ISSUE TITLE
World Population by year analysis

### ISSUE THREAD

**Issue by palak740** [prathimacode-hub/ML-ProjectKart#431]
Define You:
- [ ] LGM-SOC'21 Participant
- [x] DevIncept Participant 
- [x] Contributor

In this project, I will do data analysis and visualise the world population change in past 70 years.
Based on the data, I can further work on making a model to predict future world population.

I will use the following dataset:
https://www.kaggle.com/sansuthi/world-population-by-year

**Comment by prathimacode-hub** [comment]
Issue assigned. @palak740

**Comment by jeffryjames** [comment]
Hey! I would like to work on this issue. I will use Random Forest, KMeans and Regression Algorithms to come out with better accuracy. Please assign me this issue as DevIncept Participant. @prathimacode-hub

**Comment by prathimacode-hub** [comment]
This issue is already assigned. You can come up with a new issue. @jeffryjames
