### ISSUE TITLE
Coffee Production Prediction 

### ISSUE THREAD

**Issue by Akash20x** [prathimacode-hub/ML-ProjectKart#432]
Define You:

- [ ] LGM-SOC'21 Participant
- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

I want to add model of Coffee Production Prediction to predict average coffee production from 1990-2018. I will use different models like linear regression, Decision Tree, Random forest, Support Vector Classifier and more and compare their accuracy, RMSE and R2 score. 

**Describe the solution you'd like...**

I will use ICO Coffee Dataset (Worldwide) kaggle dataset for my analysis and predictions. 

Dataset Link : 
https://www.kaggle.com/yamaerenay/ico-coffee-dataset-worldwide

Please assign me this issue

**Comment by prathimacode-hub** [comment]
Issue assigned. @Akash20x

**Comment by Akash20x** [comment]
@prathimacode-hub Please check my pull request
