### ISSUE TITLE
Diabetes Prediction

### ISSUE THREAD

**Issue by arihantrode89** [prathimacode-hub/ML-ProjectKart#433]
Define You:

- [ ] LGM-SOC'21 Participant
- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
->Yes it is related to problem. I just found some issue. The issue is that some of features values are 0 such as BloodPressure, Skinthickness , BMI in some rows are 0 and if we use such kind of values to predict whether a person has diabetes or not then it would definately not able to predict accuractely.

**Describe the solution you'd like...**
->The solution for these problem is that we have to preprocess the dataset and then train classification models on preprocessed dataset.

**Comment by prathimacode-hub** [comment]
This is an enhancement project. So yeah, you can proceed. Don't do any changes to the existing one.
Only project file would undergo changes. And for all the things you had done create a "README_enhanced.md" @arihantrode89

**Comment by arihantrode89** [comment]
Sure.

**Comment by arihantrode89** [comment]
> This is an enhancement project. So yeah, you can proceed. Don't do any changes to the existing one.
> Only project file would undergo changes. And for all the things you had done create a "README_enhanced.md" @arihantrode89

**Comment by arihantrode89** [comment]
Sure.Thank you for asssigning this issue.
