### ISSUE TITLE
Campus Placement Prediction

### ISSUE THREAD

**Issue by Jagannath8** [prathimacode-hub/ML-ProjectKart#435]
Define You:

- [x] LGM-SOC'21 Participant
- [x] Contributor

Dataset: https://www.kaggle.com/benroshan/factors-affecting-campus-placement

The aim is to predict if a student is placed or not according to his/her percentage and other factors.
I'll use different ML algorithms to predict if a student is placed or not and compare accuracy between them.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Yes, you can. @Jagannath8
