### ISSUE TITLE
Cat and Dog classifier

### ISSUE THREAD

**Issue by PrashantVIT1** [prathimacode-hub/ML-ProjectKart#437]
I want to improve the cat and dog classifier by creating a model that has an accuracy of 92% or above by using a data set having 4,000 cats and 4,000 images of dogs for training and 1,000/1,000 images for testing by using CNN with the help of python.

**Comment by prathimacode-hub** [comment]
It's done long back. Before raising kindly check if project is available. Also follow the issue template to get it assigned. Come up with a new issue. @PrashantVIT1

**Comment by PrashantVIT1** [comment]
Yes, I agree that it was done before I have seen that part but the accuracy was around 89% and I am promising 92% or above. So I didn't change the title and also I have mention that I want to do some improvements. So please kindly look into this and guide me in this.

**Comment by prathimacode-hub** [comment]
Ok, got it. So this would be an enhancement project then. Sure, don't do chnages to the existing project. Only thing that changes is improving the project file. Rest shoudl be as it is, if there is anything to add up, you can to existing files. But point to note, you should add up a README_enhanced.md file which shows all the changes and description of the project you had done. The template for README is already provided in the project. Issue assigned. All the best. @PrashantVIT1

**Comment by prathimacode-hub** [comment]
But let me know if you are participant of LGMSOC or DevIncept. Also follow the issue template above using edit option and add the changes according to your project. @PrashantVIT1

**Comment by PrashantVIT1** [comment]
Define You:


- [ ] DevIncept Participant 
- [ ] Contributor
I want to improve the cat and dog classifier by creating a model that has an accuracy of 92% or above by using a data set having 4,000 cats and 4,000 images of dogs for training and 1,000/1,000 images for testing by using CNN with the help of python.



**Is your feature request related to a problem? Please describe.**



**Describe the solution you'd like...**



**Describe alternatives you've considered?**



**Approach to be followed (optional):**



**Additional context**

**Comment by PrashantVIT1** [comment]
Define You:

 DevIncept Participant
 Contributor

I want to improve the cat and dog classifier by creating a model that has an accuracy of 92% or above by using a data set having 4,000 cats and 4,000 images of dogs for training and 1,000/1,000 images for testing by using CNN with the help of python.
Is your feature request related to a problem? Please describe.

Describe the solution you'd like...
I want to use CNN and will use my own data for training and will enhance the model above 90%.

Describe alternatives you've considered?
This project is related to the enhancement of the cat vs dog project model whose accuracy is around 89%.

Thank you

**Comment by prathimacode-hub** [comment]
Great, issue assigned. @PrashantVIT1

**Comment by PrashantVIT1** [comment]
So can you tell me should I fork the complete repo or only that particular repo- cat vs dog classification

**Comment by prathimacode-hub** [comment]
You cannot fork just the project fork. To work on any project or create PR, complete repo should be forked. @PrashantVIT1

**Comment by PrashantVIT1** [comment]
I am unable to upload files how do I upload my that is in cat_vs_dog_classifier_enhanced.ipynb file

**Comment by PrashantVIT1** [comment]
can I make a folder name it as enhanced and save all the related FILES and DOC related to my part in that Folder. So it would not get messed up. As I have used 4 independent models for prediction with different accuracy that is 4 different .h5 files. Also, I have to upload a different dataset. It looks a little messed up and I think it will look good if it is allowed to create a file naming ENHANCEMENT

**Comment by prathimacode-hub** [comment]
Ok, you can proceed. @PrashantVIT1

**Comment by prathimacode-hub** [comment]
Are you a devincept participant?
 @PrashantVIT1

**Comment by PrashantVIT1** [comment]
yes maam
