### ISSUE TITLE
Prediction of loan defaulter

### ISSUE THREAD

**Issue by PrashantVIT1** [prathimacode-hub/ML-ProjectKart#438]
In this, I will be using python and a design tree model to predict the person could be a defaulter or not

**Comment by prathimacode-hub** [comment]
Follow the issue template given. Elaborate your project. Look up with assigned issues on how template looks like. I could understand your project title. @PrashantVIT1

**Comment by prathimacode-hub** [comment]
You cna work on only 1 issue at a time. @PrashantVIT1

**Comment by PrashantVIT1** [comment]
ok I was not aware of that

**Comment by prathimacode-hub** [comment]
That's Ok. I am just letting you know. @PrashantVIT1

**Comment by soma2000-lang** [comment]
@prathimacode-hub 

Please assign this task to me. I would like to work under this project  . I would like to solve this as a creating a model first by extracting features and apply Random Forest Classification techniques

**Comment by prathimacode-hub** [comment]
This issue is already worked on. @soma2000-lang

**Comment by soma2000-lang** [comment]
ok mam,I have opened another  new issue ,kindly check that
