### ISSUE TITLE
Fake Currency Detection

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#44]
Hey LGM-SoC participants, good to see you.

Fake Currency Detection is a task of binary classification in machine learning. If we have enough data on real and fake banknotes, we can use that data to train a model that can classify the new banknotes as real or fake. This project would help in detecting whether the currency is real or fake.

Dataset : Use public dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by jayant766** [comment]
please assign it to me under LGM-SOC'21

**Comment by Manasi2001** [comment]
@jayant766 you can surely work on this, but first let me know how you are planning to proceed, what all algorithms you will use and which task you'll be working on: backend, frontend or model creation. Then, I'll assign it to you :)

**Comment by prathimacode-hub** [comment]
> please assign it to me under LGM-SOC'21

Choose on 1 issue you would like to work on. I have seen you express interest on multiple issues. @jayant766

**Comment by Shady2320** [comment]
Hi @prathimacode-hub, please assign me i can do all the three things.

**Comment by prathimacode-hub** [comment]
That's great. What's the approach you would follow. And algorithms you would work with?
@Shady2320

**Comment by Shady2320** [comment]
At first, i will gather dataset based on Fake Currency Detection and then using Jupyter Notebook i will create model. After creating model i will deploy it using Flask.
I will use mainly two algorithms, Logistic Regression or Random Forest Classifier

**Comment by prathimacode-hub** [comment]
That's cool. This issue is assigned to you. @Shady2320

**Comment by Manasi2001** [comment]
Updates @Shady2320?

**Comment by Shady2320** [comment]
> Updates @Shady2320?

I have completed Model creation and Backend Part just little bit of Frontend part is left.
