### ISSUE TITLE
Heart Attack Analysis

### ISSUE THREAD

**Issue by harshita9621** [prathimacode-hub/ML-ProjectKart#441]
Define You:

- [ ] LGM-SOC'21 Participant
- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

 - I want to  performed in-depth Exploratory Data Analysis and 5-6 Algoritrhm.
 - Dataset:  [https://www.kaggle.com/rashikrahmanpritom/heart-attack-analysis-prediction-dataset](url)

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by harshita9621** [comment]
@prathimacode-hub  Can I work on this issue?

**Comment by prathimacode-hub** [comment]
You can take up an issue as LGMSOC or Devincept. Choose one. @harshita9621

**Comment by harshita9621** [comment]
@prathimacode-hub In DevIncept.

**Comment by prathimacode-hub** [comment]
Ok, provide some details about project in the issue template. Its empty. Add your approach and also let me know the task you are taking up. So I can label accordingly. @harshita9621

**Comment by harshita9621** [comment]
### Problem Description

A heart attack is a medical emergency that occurs when blood supply to part of the heart is suddenly cut off.A heart attack is a medical emergency that occurs when blood supply to part of the heart is suddenly cut off.

The heart muscles are supplied by the coronary arteries, which branch off from a major artery called the aorta. Heart attack occurs when one or more of the coronary arteries becomes blocked. This lack of blood supply and oxygen can cause injury to the heart muscle and if supply is prevented for more than 20 minutes, the part of the muscle tissue failing to receive blood may die. The medical term for a heart attack is myocardial infarction or MI.

### What I will Done

- To Perform Complete EDA.

- Derive Insights from Data.

 - Built Different Classification Models.

- Compare Different Classification Models.

- Select Best Model.

- Fine Tune and Optimize the Best Model.

- Finally Predict a person is prone to Heart Attack or not.

**Comment by prathimacode-hub** [comment]
I asked to add in template not separately. Anyways leave it. @harshita9621
