### ISSUE TITLE
Employee Retention Prediction

### ISSUE THREAD

**Issue by Jagannath8** [prathimacode-hub/ML-ProjectKart#449]
Define You:

- [x] LGM-SOC'21 Participant
- [x] Contributor

Dataset: https://www.kaggle.com/giripujar/hr-analytics

The aim is to predict retention of an employee within an organization such that whether the employee will leave the company or continue with it.
I'll use different ML algorithms to predict retention of an employee and compare accuracy between them.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
It's already done. @Jagannath8
