### ISSUE TITLE
Dog Breed Identification

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#45]
Hey LGM-SoC participants, good to see you.

This project would help in identifying the dog breed. If humans are detected, it would provide the estimate of the dog breed that's most resembling.

Dataset : Use public dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. 

Enjoy your open source journey!😎

**Comment by Anshal55** [comment]
Hi I am a ‘LGM-SOC participant’ asd I'd like to work on this.
How to proceed further?

**Comment by prathimacode-hub** [comment]
Work on the project. I had given all guidelines to follow in README and CONTRIBUTING GUIDELINES of the project. Any specific queries, don't hesitate to ask. First, elaborate the project, how would you expect it to work. You are going to work on which task : "Model Creation" or "Front End" or "Back End" or Designing? The algorithms you would use, how would you optimize it. Let me know the answers to these queries, so that I could assign this issue to you. @Anshal55

**Comment by Anshal55** [comment]
---
Title: Dog Breed Identification
About: Model to predict the breed of a Dog.
Name: Anshal Singh
Label: Feature Request
Assignee: ''

---

Define You:

- [ x] LGM-SOC'21 Participant 
- [ ] Contributor


**Describe the solution you'd like...**
I'd like to work on a dataset containing images of dogs with their breeds and train a model to predict the breed of a dog.
Link for Dataset: https://www.kaggle.com/c/dog-breed-identification

**Comment by Anshal55** [comment]
---
Title: Dog Breed Identification
About: Prediction of breed of a dog based ion images.
Name: Anshal Singh
Label: Feature Request
---

Define You:

I am a LGM-SOC'21 Participant 

I'd like to build a Model that would predict the breed of the dog an the link for the dataset is https://www.kaggle.com/c/dog-breed-identification
My approach towards the problem is to try to use transfer learning to build the model the use python + flask to deploy it.

**Comment by prathimacode-hub** [comment]
So, you will be working on model creation and backend right? @Anshal55

**Comment by Anshal55** [comment]
Yes @prathimacode-hub !

**Comment by prathimacode-hub** [comment]
Yup, go ahead. Issue is assigned to you. @Anshal55

**Comment by Anshal55** [comment]
Thanks @prathimacode-hub !!
