### ISSUE TITLE
Railway Track Fault Detection

### ISSUE THREAD

**Issue by Best-forever-003** [prathimacode-hub/ML-ProjectKart#452]
Define You:

NAME: -AAMIR P
USERNAME: Best-forever-003
PROJECT: Railway Track Fault Detection
 
- [x] DevIncept Participant
- [x] Contributor

**Describe the Bug**

Images to Classify Defective and Non-Defective Railway Track

**Steps to Reproduce**

I'm planning to train the model based on CNN. So, that training accuracy will reach 80%

**Expected Behavior**

If the railway tracks are at fault, our model will notify us.

Can you please assign this task to me Madam @prathimacode-hub 

Dataset link: https://www.kaggle.com/salmaneunus/railway-track-fault-detection

**Comment by prathimacode-hub** [comment]
Wow, it's an innovative project. @Best-forever-003

**Comment by Best-forever-003** [comment]
Thanks Madam @prathimacode-hub
