### ISSUE TITLE
Experimenting using SVM for Student performance prediction

### ISSUE THREAD

**Issue by Priyanka333** [prathimacode-hub/ML-ProjectKart#455]
Hello

Greetings of the day. :)
My name is  Priyanka Shahane.
I'm DevIncept contributor.

I would like to contribute to your 'Student performance prediction' project by implementing the same concept using SVM algorithm.

**Comment by prathimacode-hub** [comment]
This is already done, first check if the project is in the repo. Also follow the template given to raise an issue. Come up with a new issue that's not available in this project. @Priyanka333

**Comment by prathimacode-hub** [comment]
I shall create new issues to work upon. So you would get enough projects to choose from grabs. @Priyanka333

**Comment by Priyanka333** [comment]
Thanks
