### ISSUE TITLE
Using different algorithm for implementation of 'Student Performance Prediction' project

### ISSUE THREAD

**Issue by Priyanka333** [prathimacode-hub/ML-ProjectKart#456]
Hello 

This is Priyanka.

- [ ] LGM-SOC'21 Participant
- [ ] DevIncept Participant 8
- [x] Contributor

I just checked the github repository & found that the 'Student Performance Prediction' project is implemented using Decision Tree Regressor, Linear Regression, Lasso Regression and Random Forest Regressor **but not the SVM** so I would like to implement the same using SVM.

**Comment by prathimacode-hub** [comment]
This can't be worked on. Are you a lgmsoc or devincept participant? @Priyanka333
