### ISSUE TITLE
Employee Attrition Prediction

### ISSUE THREAD

**Issue by drashtipatel2503** [prathimacode-hub/ML-ProjectKart#457]
title: Employee Attrition Prediction
about:  to predict chances of an employee to leave or retire.
name: Patel Drashti
label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

Basically there are many factors on which attrition of an individual is depended like job satisfaction, salary, age, years in same company, years at same position, years with same manager, hourly rate, traveloptions with business, place , environment and others. Depensing on these factors I will try to predict attrition of an employee.

I will be using Kaggle dataset for this.

The approach will be as follow:
1. load dataset and install necessary modules.
2. preprocess dataset
3. scale columns to make it best fit to model
4. build model

**Comment by prathimacode-hub** [comment]
This is already done. @drashtipatel2503

**Comment by prathimacode-hub** [comment]
I shal add up more issues up for grabs soon. @drashtipatel2503
