### ISSUE TITLE
Olympic Medal Prediction

### ISSUE THREAD

**Issue by Akash20x** [prathimacode-hub/ML-ProjectKart#459]
Define You:

- [ ] LGM-SOC'21 Participant
- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

I want to add model of Olympic Medal Prediction to predict whether a given athlete will win a medal or not at the Olympics based on their characteristics. I will different classification machine learning algorithms and compare their accuracy. 

**Describe the solution you'd like...**

I will use 120 years of Olympic history: athletes and results kaggle dataset for predictions. 

Dataset Link:
https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results

Please assign me this issue

**Comment by prathimacode-hub** [comment]
Issue assigned. @Akash20x
