### ISSUE TITLE
Air Quality Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#46]
Hey LGM-SoC participants, good to see you.

With the project, we can predict the air quality index (AQI) based on atmospheric elements in the environment.

Dataset : https://www.kaggle.com/shrutibhargava94/india-air-quality-data (or) Public Dataset.

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by payaldutta** [comment]
Hey, I am interested in this issue can you please elaborate it what actually I have to do, and along with please assign me this issue under LGM-SC'21. @prathimacode-hub 
ThanK You

**Comment by prathimacode-hub** [comment]
This issue is predicting the air quality based on considering various atmospheric materials in the environment. Issues will assigned only from 10th June starting from 10AM. You can express your interest then. @payaldutta

**Comment by sy07** [comment]
Hi mam, I would like to work on this issue as LGM-SOC'21 participant from June 10. Do assign me this task if possible. I would like to work on data.
Thank You!

**Comment by ayushi424** [comment]
Hey @prathimacode-hub, I would like to work on this issue.
Please assign.

**Comment by prathimacode-hub** [comment]
Sure, I would assign it to you. But let me know about your approach, how would you take it further? What's the task you're opting for? @ayushi424

**Comment by ayushi424** [comment]
I'll work on model creation.
For approach, firstly I'll perform data exploration for feature selection.
Then use prediction algorithms and evaluate their efficiency.

**Comment by prathimacode-hub** [comment]
Ok cool. This issue is assigned to you. @ayushi424
