### ISSUE TITLE
Predict Future Sales

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#460]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

PROJECT TITLE : Predict Future Sales
please assign this project to me.

GOAL : To predict the future sales.

DATASET : https://www.kaggle.com/c/competitive-data-science-predict-future-sales

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the Future Sales dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model prediction part I used machine learning algos . In each algo I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset . During the model prediction I got different accuracies from different models .

**Comment by prathimacode-hub** [comment]
Issue assigned. @aryantiwari10
