### ISSUE TITLE
Car insurance prediction 

### ISSUE THREAD

**Issue by soma2000-lang** [prathimacode-hub/ML-ProjectKart#463]
Define You:

- [x] LGM-SOC'21 Participant

**Is your feature request related to a problem? Please describe.**

 @prathimacode-hub ,I want to add a model on the prediction of car insurance prediction. 

**Describe the solution you'd like...**

I would do some data analysis by extracting the features and then would implement some Random forest regressor techniques in it

**Describe alternatives you've considered?**

I would work on all of its important features and try to show a visualization of it .

**Comment by soma2000-lang** [comment]
@prathimacode-hub 
Please assign me this

**Comment by prathimacode-hub** [comment]
Are you a participant of LGMSOC or Devincept? @soma2000-lang

**Comment by soma2000-lang** [comment]
@prathimacode-hub  mam I am a particiapnt of LGMSOC-21

**Comment by prathimacode-hub** [comment]
Issue assigned. @soma2000-lang
