### ISSUE TITLE
Classification of Images using mnist and cifar10 dataset

### ISSUE THREAD

**Issue by RC2208** [prathimacode-hub/ML-ProjectKart#464]
Define You:

- [ ] LGM-SOC'21 Participant
- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

Predict what image it is. with good accuracy.

**Describe the solution you'd like...**

Train two models to predict what the image actually is (label). mnist has grey images of digits 0-9 and cifar10 has coloured images of different objects.

**Additional context**

**Comment by prathimacode-hub** [comment]
Issue not yet assigned, and you had submitted PR? @RC2208

**Comment by RC2208** [comment]
Oh sorry I didn't realize it's not assigned yet. I thought I got a notif but i guess it was a different issue. Then what should i do? Close the PR?

**Comment by prathimacode-hub** [comment]
Yes, I am closing your PR. I am assinged this issue now. Create your PR once again. @RC2208
