### ISSUE TITLE
IMDB Sentiment Analysis

### ISSUE THREAD

**Issue by shivani6320** [prathimacode-hub/ML-ProjectKart#466]
Define You:

- [ ] LGM-SOC'21 Participant
- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
I would Perform Sentiment analysis on IMDB Dataset of 50K Movie Reviews. I'll  do a thorough Exploratory Data Analysis of the dataset and report the final performance metrics.

Dataset : http://ai.stanford.edu/~amaas/data/sentiment/

@prathimacode-hub , Please assign me this issue.

**Comment by prathimacode-hub** [comment]
I guess it's over, can you check it once? @shivani6320

**Comment by shivani6320** [comment]
I  checked, There is no project with sentiment analysis on IMDB dataset.

**Comment by prathimacode-hub** [comment]
Ok, then issue assigned. @shivani6320
