### ISSUE TITLE
Disease Symptom Prediction

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/ML-ProjectKart#467]
Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

In this will create a model for predicting the symptom of various disease using the information in the dataset.

will use this [here](https://www.kaggle.com/itachi9604/disease-symptom-description-dataset)

And will use different algorithms like
linear regression
logistic regression
decision tree regression
Random Forest classifier
K Neighbor Classifier
XG boost classifier

and will compare the the accuracy among them

will be working on model creation.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Assigned. @akash435

**Comment by prathimacode-hub** [comment]
Its been 16days issue assigned, no PR yet. @akash435

**Comment by akash435** [comment]
yes mam i tried to do it, but getting error in implementing more models

**Comment by prathimacode-hub** [comment]
Ok, sure. @akash435
