### ISSUE TITLE
Glass Classification

### ISSUE THREAD

**Issue by Soumayan-pal01** [prathimacode-hub/ML-ProjectKart#469]
---
Title: Glass Classification
About: To classify the type nad purpose of glass
Name: Soumayan Pal
Label: Feature Request
Assignee: 'Soumayan-pal01'

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DCP'21 Participant 
- [ ] Contributor

**To classify different types of glass and thier purposes based on the percentage of different minerals present**

**Will be performing EDA and using different Classifier models to perform a comparative analysis*

**Comment by Soumayan-pal01** [comment]
I would like to work on 'Model Creation' for this issue @prathimacode-hub .Please assign me if possible.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Soumayan-pal01
