### ISSUE TITLE
Car Prices Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#47]
Hey LGM-SoC participants, good to see you.

This project will help in predicting the car prices.

Dataset : https://www.kaggle.com/hellbuoy/car-price-prediction

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Chanakya-Sharma** [comment]
Can you assign me this

**Comment by prathimacode-hub** [comment]
Issues will be assigned only from tomorrow. You will get all the details of how to get it assigned by today evening in slack channel. @Chanakya-Sharma

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
Sorry to say but I won't be able to assign you now. I have to follow some guidelines. But stay tuned, and express your interest promptly tomorrow after 10AM. It would be first come, first serve basis. 👍@harshita9621

**Comment by sy07** [comment]
Hi mam, I would like to work on this issue as LGM-SOC'21 participant from June 10. Do assign me this task tomorrow if possible.
Thank You!

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant . Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
Yeah, this issue is assigned to you. You can start working on it. All the best. @harshita9621
