### ISSUE TITLE
Private Companies Prediction

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#470]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

PROJECT TITLE : Private Companies Prediction

GOAL : To predict the number of the private limited companies.

DATASET : https://www.kaggle.com/aryantiwari123/privated-limited-companiescsv

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the Private Companies dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model prediction part I used different machine learning algorithms . In each algorithm I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset . During the model prediction I got different accuracies from different models , I got the highest accuracy of 100 % using the Random Forest Classifier which is quite well for the given Private Companies dataset . While the other model accuracies can be increased more using the hypertuning . Some plots which I used for visualizing the dataset are Histogram , Barplot , Boxplot, Heatmap , Scatter plot , Pairplot , Jointplot etc.

LIBRARIES:

PANDAS

NUMPY

MATPLOTLIB

SEABORN

SCIPY

SKLEARN

CONCLUSION :

So we get a good accuracy score of 100 % using Random Forest Classifier and Ada Boost Classifier.

The accuracy of other models can be increased by Hypertuning.

**Comment by prathimacode-hub** [comment]
Issue assigned. @aryantiwari10
