### ISSUE TITLE
Generating graphs for comparing Kappa Score of different algorithms.

### ISSUE THREAD

**Issue by Priyanka333** [prathimacode-hub/ML-ProjectKart#473]
Good afternoon

This is Priyanka Shahane.
I'm DevIncept Participant.

**Describe the Bug**

I would like to contribute to the 'Automated Essay Grading ' project by generating graphs for comparing Kappa Score of different algorithms. 

**Steps to Reproduce**

1. Import matplotlib library
2. Generating graphs

**Comment by prathimacode-hub** [comment]
So, is this an enhancement to existing project. @Priyanka333

**Comment by Priyanka333** [comment]
Yes...I have added graphs module to compare the accuracy of different algorithms which was not there in the existing project.

**Comment by prathimacode-hub** [comment]
Ok, great. Issue assigned. @Priyanka333
