### ISSUE TITLE
Avito Product Analysis and Price Prediction

### ISSUE THREAD

**Issue by palak740** [prathimacode-hub/ML-ProjectKart#475]
Define You:

- [ ] LGM-SOC'21 Participant
- [x] DevIncept Participant
- [x] Contributor

This project is related to product data analysis, the dataset contains various information about different products and its location and shop, based on these factors price of product can be predicted after training regression models on the dataset. The dataset needs a lot of cleanup, through this dataset, I want to work more on data cleaning and analysis and thus applying models to predict prices. 

I will use the following dataset:
https://www.kaggle.com/abderrahimalakouche/data-analysis-products-dataset

**Comment by prathimacode-hub** [comment]
Ok, what's the project title? Which product analysis is it? Which product price prediction is it? Which website products you are considering? @palak740

**Comment by palak740** [comment]
> Ok, what's the project title? Which product analysis is it? Which product price prediction is it? Which website products you are considering? @palak740

The dataset contains various products and their ids, based on the input product name and ids, and based on other factors  prices can be predicted. According to kaggle website, these products are from Avito advertisment website.

**Comment by prathimacode-hub** [comment]
Ok then change the issue title to "Avita Product Analysis and Price Prediction". I am assigning this issue to you. @palak740

**Comment by palak740** [comment]
> Ok then change the issue title to "Avita Product Analysis and Price Prediction". I am assigning this issue to you. @palak740

Changed the title, thankyou mam :)
