### ISSUE TITLE
Brazil Fires Prediction

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#479]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

PROJECT TITLE : Brazil Fires Prediction
plz assign this project to me.

GOAL : To predict the number of the fires taken place statewise in brazil.

DATASET : https://www.kaggle.com/gustavomodelli/forest-fires-in-brazil

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the Brazil Fires dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model prediction part I used different machine learning algorithms . In each algorithm I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset . During the model prediction I got different accuracies from different models , I got the highest accuracy of 100 % using the Random Forest Classifier, XG Boost Classifier which is quite well for the given Brazil Fires dataset . While the other model accuracies can be increased more using the hypertuning . Some plots which I used for visualizing the dataset are Histogram , Barplot , Boxplot, Heatmap , Scatter plot , Pairplot , Jointplot etc.

LIBRARIES:

PANDAS

NUMPY

MATPLOTLIB

SEABORN

SCIPY

SKLEARN

CONCLUSION :

So we get a good accuracy and training score of about 100 % using Random Forest Classifier, XG Boost , Gradient Boosting Classifier.

The accuracy of other models can be increased by Hypertuning.

**Comment by prathimacode-hub** [comment]
Issue assigned. @aryantiwari10
