### ISSUE TITLE
Employee Retention Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#48]
Hey LGM-SoC participants, good to see you.

This project will help in predicting the chances of employee leaving the company.

Dataset : Use public dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Jai-Agarwal-04** [comment]
Please assign this issue to me

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub I would like to contribute to this issue as I have already worked on similar projects like this. Please assign me this issue if possible. Thank you.

**Comment by Jai-Agarwal-04** [comment]
I am LGMSOC'21 participant Can you please assign me this!

**Comment by prathimacode-hub** [comment]
Issues will be assigned on first come, first serve basis from tomorrow, starting 10AM. So best of luck. @Jai-Agarwal-04

**Comment by arushi09207** [comment]
hi @prathimacode-hub  can i work on this project and contribute to it? if so plz assign it to me

**Comment by prathimacode-hub** [comment]
Yes, it can be assigned. Let me know about your approach and how would you predict it. Also intimate about the task you're choosing. So that, it would be easier to get issued assigned to you. @arushi09207

**Comment by arushi09207** [comment]
so my approach would be use two datasets one from employee's level and the other one from HR point of view. Further I'll join and merge those datasets , analyse them using visualizations and using feature importance as the main agenda and further using different models to it .

**Comment by prathimacode-hub** [comment]
That's great. This issue is assigned to you. You can proceed. @arushi09207

**Comment by arushi09207** [comment]
thanks @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Any update? @arushi09207

**Comment by arushi09207** [comment]
Please refer to my pr made again! Thanks for all the help. 😃
