### ISSUE TITLE
Object Detection Using OpenCV

### ISSUE THREAD

**Issue by vaishnavipatil4848** [prathimacode-hub/ML-ProjectKart#484]
Define You:

 - [ ] LGM-SOC'21 Participant
 - [x] DevIncept Participant
 - [ ] Contributor
 
Is your feature request related to a problem? Please describe.

I want to perform live object detection using OpenCV. This would in return create Detection model for detecting objects provided in the classic COCO  dataset.

Describe the solution you'd like...
The solution consists of detecting objects live through input video stream and identified using bounding box around the objects.

Dataset Link:
https://cocodataset.org/#home

Please assign me this issue under DCP'21.

**Comment by prathimacode-hub** [comment]
Issue assigned. @vaishnavipatil4848
