### ISSUE TITLE
Snapchat Filters

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/ML-ProjectKart#485]
Title: I want to add a project for snapchat filters using Python
Name: Umesh Singh
Label: Feature Request

Define You-
- [x] LGM-SOC'21 Participant
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
I want to make a project for snapchat filters using python with the help of opencv, numpy, etc.

**Comment by Umesh-01** [comment]
@prathimacode-hub mam should I work on this project??

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. @Umesh-01
