### ISSUE TITLE
Supermarket Sales Prediction

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#488]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

PROJECT TITLE : Supermarket Sales Prediction
plz assign this project to me.

GOAL : To predict about the supermarket sales .

DATASET : https://www.kaggle.com/aungpyaeap/supermarket-sales

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the Super market dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model prediction part I used different machine learning algorithms . In each algorithm I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset . During the model prediction I got different accuracies from different models , I got the highest accuracy of 100 % using the Random Forest Classifier, Extra Trees Classifier which is quite well for the given Supermarket dataset . While the other model accuracies can be increased more using the hypertuning . Some plots which I used for visualizing the dataset are Histogram , Barplot , Boxplot, Heatmap , Scatter plot , Pairplot , Jointplot etc.

ACCURACIES OF DIFFERENT MODELS ARE:

KNeighbors Classifier= 64.75 %

SVC= 55.50 %

Naiye Bayes= 55.10 %

Decision Tree Classifier= 64 %

Random Forest Classifier= 100 %

Ada Boost Classifier= 67 %

Gradient Boosting Classifier= 89 %

XGB Classifier= 64 %

Extra Trees Classifier= 100 %

Bagging Classifier = 51 %

LIBRARIES:

PANDAS

NUMPY

MATPLOTLIB

SEABORN

SCIPY

SKLEARN

**Comment by prathimacode-hub** [comment]
Issue assigned. @prathimacode-hub
