### ISSUE TITLE
Waste Classification

### ISSUE THREAD

**Issue by Soumayan-pal01** [prathimacode-hub/ML-ProjectKart#492]
---
Title: Waste Classification
About: To classify the type of waste
Name: Soumayan Pal
Label: Feature Request
Assignee: 'Soumayan-pal01'

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DCP'21 Participant 
- [ ] Contributor

**A Waste management system that classifies different category of waste**

**Will be using CNN and VGG16 model for classification.**

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub I would like to work on 'Model Creation' for this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Soumayan-pal01
