### ISSUE TITLE
Graduate Admission Prediction

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#494]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

PROJECT TITLE : Graduate Admission Prediction

GOAL : To predict about the Graduate Admissions from an Indian perspective.

DATASET : https://www.kaggle.com/mohansacharya/graduate-admissions

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the Graduate Admission dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning regression algorithms and then predicted the accuracy of every model . In the model prediction part I used different machine learning algorithms . In each algorithm I had included the accuracy score , training score , R2 score, mean squared error as it is a regression problem . While in the EDA part I have included different plots for the different visualizations of our dataset . During the model prediction I got different accuracies from different models , I got the highest accuracy of 85 % using the Linear Regression which is quite well for the given Supermarket dataset . While the other model accuracies can be increased more using the hypertuning . Some plots which I used for visualizing the dataset are Histogram , Barplot , Boxplot, Heatmap , Scatter plot , Pairplot , Jointplot etc.

LIBRARIES:

PANDAS

NUMPY

MATPLOTLIB

SEABORN

SCIPY

SKLEARN

CONCLUSION :
We got a accuracy of about 85 % using Linear Regression and 81 % using Ridge Regression.

The accuracy of other models can be increased by HyperTuning.

**Comment by prathimacode-hub** [comment]
Issue assigned. @aryantiwari10
