### ISSUE TITLE
Tetris Object Counter using OpenCV

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#50]
Hey LGM-SoC participants, good to see you.

This project helps in counting the no of objects present in a tetris image. It uses OpenCV and imutils.

If you like to work on this issue, follow the given guidelines for code as well as for the README.

Enjoy your open source journey!😎

**Comment by noviicee** [comment]
Hey @prathimacode-hub  
Can I work on this under LGM-SOC'21 ?

**Comment by prathimacode-hub** [comment]
Issue would be assigned from June 10th, 10AM. Express interest after 10AM promptly to get this issue asigned it to you. It would be on first come first serve basis. Check out the enclosed document pinned on project channel in slack to clarify your queries. @noviicee

**Comment by noviicee** [comment]
> Issue would be assigned from June 10th, 10AM. Express interest after 10AM promptly to get this issue asigned it to you. It would be on first come first serve basis. Check out the enclosed document pinned on project channel in slack to clarify your queries. @noviicee

Can I take this up as a part of lgm-soc'21?

**Comment by prathimacode-hub** [comment]
Yes, can you elaborate the project? @noviicee

**Comment by 1anshu-56** [comment]
I want to work on this under LGMSOC can you please assign it to me.

**Comment by prathimacode-hub** [comment]
Ok, I shall assign this issue to you. Can you elaborate oh how would you work? @1anshu-56

**Comment by TusharAMD** [comment]
Hello. Is this issue assigned to anyone?
I think I can work on this. Please assign this to me if its available.
First of all its similar to shape detection in opencv which I have already worked on. So first I need to convert the image to grayscale and find the contours.
Each tetris will have certain color so that can be used to differentiate between different blocks.
So like wise I am planning to return each block and color in form of python dictionary. I think I am going in correct path

**Comment by prathimacode-hub** [comment]
This project is not just about tetris but also an object counter as well. Hope you know it. Sure, Let me know on the task you're going to work on? @TusharAMD

**Comment by prathimacode-hub** [comment]
You can now check on with the issue given, We give tetris image as an input and count number of objects  present in it using OpenCV and imutils. @TusharAMD

**Comment by TusharAMD** [comment]
Yes I can work on this one. Can I get the sample of input images? Or should I get it from internet

**Comment by prathimacode-hub** [comment]
You can get it from internet. But make sure it's the valid tetris image files. This issue is assigned to you. @TusharAMD
