### ISSUE TITLE
Book Genre Prediction 

### ISSUE THREAD

**Issue by Akash20x** [prathimacode-hub/ML-ProjectKart#500]
Define You:

- [ ] LGM-SOC'21 Participant
- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

I want to add model of Book Genre Prediction to predict the genre of the book based on book title and summary. The model will predict among these 6 genres (Fiction", "Fanstasy", "Historical novel", "Horror", "Science Fiction", "Thriller"). 

I will use different classification machine learning algorithms and compare their accuracy. 

**Describe the solution you'd like...**

I will use CMU Book Summary Dataset for making this text classification model. 

Dataset Link:
http://www.cs.cmu.edu/~dbamman/booksummaries.html

Please assign me this issue

**Comment by prathimacode-hub** [comment]
Issue assigned. @Akash20x

**Comment by prathimacode-hub** [comment]
Its been 4 days and no update yet

**Comment by Akash20x** [comment]
@prathimacode-hub I will complete it till tommorow and send the pull request

**Comment by prathimacode-hub** [comment]
Ok. @Akash20x
