### ISSUE TITLE
News Articles Classification 

### ISSUE THREAD

**Issue by drishtibaranwal** [prathimacode-hub/ML-ProjectKart#501]
Define You:

- [√] HacktoberFest Participant
- [ ] Contributor

This model will classify any text into different groups of news like politics, religion, sports, space etc.

**Comment by drishtibaranwal** [comment]
I want to work on this issue. Please assign me this issue

**Comment by prathimacode-hub** [comment]
Issue assigned. @drishtibaranwal

**Comment by KhushiChaudhary744** [comment]
Hey, I am a hacktoberfest participant and will love to contribute here!

**Comment by tanvideshmukh29** [comment]
@prathimacode-hub
I would love to contribute as a participant of hacktoberfest2021.
Can you plz assign it to me.

**Comment by prathimacode-hub** [comment]
Issue assigned to @KhushiChaudhary744

**Comment by KhushiChaudhary744** [comment]
Thanks! I am on it!

**Comment by prathimacode-hub** [comment]
By when are you expected to do? Fest is about to end? @KhushiChaudhary744

**Comment by KhushiChaudhary744** [comment]
Hey, sorry for the delay. I got caught up in college activities. By tonight for sure.

**Comment by prathimacode-hub** [comment]
Glad to know. Go ahead. @KhushiChaudhary744
