### ISSUE TITLE
Memepool Prediction

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#503]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

PROJECT TITLE : Memepool Prediction

GOAL : To predict about the memepool in detail.

DATASET : https://www.kaggle.com/aryantiwari123/memepool

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the Memepool dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did the model building using different machine learning classification and regression algorithms and then predicted the accuracy of every model . In the model  In each algo I had included the accuracy score , training score , classification report , confusion matrix . While in the EDA part I have included different plots for the different visualizations of our dataset . While the other model accuracies can be increased more using the hypertuning . Some plots which I used for visualizing the dataset are Histogram , Barplot , Boxplot, Heatmap , Scatter plot , Pairplot ,Regplot etc.

**Comment by prathimacode-hub** [comment]
Issue assigned. @aryantiwari10
