### ISSUE TITLE
Face Eye Detection 

### ISSUE THREAD

**Issue by anubhav201241** [prathimacode-hub/ML-ProjectKart#504]
Define You:

- [x] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

I want to Contribute to your Project Face Eye Detection which can detect the eye and the face with the use of Open cv and Python 

@prathimacode-hub Kindly assign this issue to me :)

**Comment by prathimacode-hub** [comment]
This is already done. Kindly come up with another issue to work on. Make sure the project isn't in the repo. @anubhav201241

**Comment by anubhav201241** [comment]
@prathimacode-hub can I contribute Social Distance Detection code?

**Comment by prathimacode-hub** [comment]
Yes, but first create an issue using template given and get it assigned before you start working. @anubhav201241
