### ISSUE TITLE
Customer Income Segmentation Analysis

### ISSUE THREAD

**Issue by dilroseR** [prathimacode-hub/ML-ProjectKart#505]
Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
Goal: To group customers into 5 categories: 
- low income low spending
- low income high spending
- medium income medium spending
- high income low spending
- high income high spending

**Describe the solution you'd like...**
I would like to group them using KMeans Algorithm 

kindly assign it to me

**Comment by prathimacode-hub** [comment]
First thing, change the issue title as "Customer Income Segmentation Analysis". Then only one algorithm doesn't suffice. You need to work with atleast 3 algorithms and compare the efficiency across. If that's ok, I shall assign it to you. @dilroseR

**Comment by dilroseR** [comment]
> First thing, change the issue title as "Customer Income Segmentation Analysis". Then only one algorithm doesn't suffice. You need to work with atleast 3 algorithms and compare the efficiency across. If that's ok, I shall assign it to you. @dilroseR

ok with it

**Comment by prathimacode-hub** [comment]
Issue assigned. @dilroseR
