### ISSUE TITLE
Classifying imagenet Images and Classes

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#51]
Tasks Include :
* Create a Vgg-19 Model for classifying imagenet images
* Create a simple web app with Flask and Html/CSS/Js
* Upload an image to predict the class of the image.

    Dataset-[Here](https://www.tensorflow.org/datasets/catalog/imagenet2012)

The dataset will be loaded in the code itself, We do not require any manual downloading as it's huge around 15GB.

It has over 200 classes with 100k+ images.
Once The application is done all you need to do is access the web app ( No training as I will be saving the model)

I'd like to work on this as part of the LGMSOC-21.
Thanks

**Comment by NEERAJAP2001** [comment]
Hey @prathimacode-hub Can I work on this?

**Comment by prathimacode-hub** [comment]
Can you say what's the project title and what's the purpose of it @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Imagenet is a renowned dataset with 100k+ images 
It's a Web Application that can Predict the image ( based on training classes like a bird, rabbit...etc)


Title of Project: Web App For Classifying Imagenet Images

**Comment by prathimacode-hub** [comment]
Cool, this issue is assigned to you. You can proceed further. So you will be working on front end or back end? @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
I'll be working on model + backend+ frontend @prathimacode-hub

**Comment by prathimacode-hub** [comment]
That's glad to know.
