### ISSUE TITLE
Update the "Look Through the Kart of Amazing Projects" in README - Part 2

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#511]
Hey, LGMSOC participants. Good to see you here.

Good first issue up for grabs. There are in total '157' projects listed out in the section of "Look Through the Kart of Amazing Projects" in README.md.

Currently, the repo exists with 198 projects. If anyone is interested to take up this good first issue can come forward and express your interest. 

Point to Note : The projects should be added in alphabetical order. Just follow the same format as provided in the table and you are good to go.  And, this PR needs to be completed by 6th Aug, 2021.

All the best for your open source journey ahead. 😎

**Comment by DayneMoonsamy** [comment]
Hello 

I'm new to Open source contributions. Could I take care of this problem for my first contribution.

**Comment by prathimacode-hub** [comment]
Yes you can. By the way are you a contributor or DCP/LGMSOC participant? @DayneMoonsamy

**Comment by DayneMoonsamy** [comment]
Not sure what those are.

Could you tell me what they are or I could find out myself.

**Comment by DayneMoonsamy** [comment]
Just to be clear my task is to go through every missing project and get a basic description so I can add the name and description to the base ReadMe.

**Comment by prathimacode-hub** [comment]
Yes exactly in alphabetical order. You can provide a description based on the project done. @DayneMoonsamy

**Comment by DayneMoonsamy** [comment]
Hey Prathima. Last question. The alphabetical order in the ReadMe is not going to match the folder order for different projects since Github orders the folders like COVID19 before Campus Placement because of the caps. That's fine right?

**Comment by prathimacode-hub** [comment]
Yes, it's ok. That's an odd one out I knew about it. @DayneMoonsamy
