### ISSUE TITLE
Mortality Rate Analysis & Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#513]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in analyzing and predicting the mortality rate using the provided dataset.

Dataset : https://www.kaggle.com/navinmundhra/world-mortality

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Can you please assign me this mam.

**Comment by prathimacode-hub** [comment]
Already an issue is assigned. @ashish-reddy-20-08

**Comment by theshredbox** [comment]
Ma'am I would like to take this issue as a contribution for Hacktoberfest '22.
Name- Aryan Ahuja
Hacktoberfest Participant
Type- Documentation
Approach- Use the above dataset, make some visualizations using Tableau, and make conclusive predictions on the stats.

**Comment by prathimacode-hub** [comment]
Issue assigned to @theshredbox
