### ISSUE TITLE
Pnuemonia Disease Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#514]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in predicting the pneumonia disease using the dataset given

Dataset : https://www.kaggle.com/broach/weekly-cdc-pneumonia-cases

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by deepthi1107** [comment]
please do assign me mam

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107

**Comment by tanvideshmukh29** [comment]
@prathimacode-hub
I would love to contribute mam as a part of hacktoberfest2021.
Can you assign this to me?

**Comment by sy07** [comment]
Hi mam, I would like to work on this issue as Hacktoberfest participant. Please assign me to this task if possible.

**Comment by prathimacode-hub** [comment]
By when are you expected to do? Fest is about to end? @sy07

**Comment by sy07** [comment]
Please unassign me from this task because I won't be able to complete it.

**Comment by prathimacode-hub** [comment]
Ok, sure

**Comment by freny24** [comment]
@prathimacode-hub  This issue is up for hacktober fest 2022 right? 
if yes , please assign this issue to me!
Approach : predict whether the person is diagnosed with pneumonia or not using convolutional neural network

**Comment by prathimacode-hub** [comment]
Issue assigned. @freny24
