### ISSUE TITLE
Butterfly Classification Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#516]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in analyzing and classifying the various species of butterflies using dataset given

Dataset : https://www.kaggle.com/bertcarremans/butterfly-images

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by deepthi1107** [comment]
please do assign me

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107

**Comment by vandit98** [comment]
hi @prathimacode-hub 
I want to work on this problem. Please assign this issue to me.
Thank you
