### ISSUE TITLE
Ramen Noodles Ratings Aanlysis

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#518]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in analyzing and visualizing the ratings of Ramen Noodles company country wise based on popularity, top brands and top ten ratings.

Dataset : https://www.kaggle.com/residentmario/ramen-ratings?select=ramen-ratings.csv

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by abhisheks008** [comment]
@prathimacode-hub I am up for this issue.

- [x] DCP Participant


Approach : I will do these following processes with this dataset.
1. Understanding the data
2. Cleaning the data
3. Visualizing the data
4. Analyze the data


Task Taken : Model Creation
Issue #518

Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
