### ISSUE TITLE
Vehicles and Pedestrian Tracking using OpenCV

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#519]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in tracking vehicles and pedestrians crossing across the signals. 

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by theshredbox** [comment]
Ma'am I would like to take this issue as a contribution for Hacktoberfest '22.
Name- Aryan Ahuja
Hacktoberfest Participant
Type- Documentation
Approach- Use Yolo Object Detection to detect people and vehicles in a video input.

**Comment by prathimacode-hub** [comment]
Issue assigned to @theshredbox
