### ISSUE TITLE
Car Brand Classification using Resnet50

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#52]
---
Title: Car Brand Classification
Name: Neeraj Ap
Label: Feature Request
---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

About : 
Create a Car Brand Classification Project

Tasks:

* Uses Deep learning to detect car brands
* I'm assuming to solve this using resnet50( transfer learning ) but let's see how it goes.
* Dataset consists of Images of 3 different brands ( I'll give the dataset for download in a separate folder)

I'll Work on Model + FrontEnd + Backend

I'd Like to work on this issue as part of LGMSOC-21.

**Comment by NEERAJAP2001** [comment]
Hey @prathimacode-hub  Can I work on this?

**Comment by prathimacode-hub** [comment]
Sure, you can work on this. That's a good explanation. But kindly add a commment according to the issue template. @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Okay @prathimacode-hub

**Comment by Manasi2001** [comment]
Go ahead @NEERAJAP2001 👍🏻
