### ISSUE TITLE
Voice Gender Identification

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#520]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in identifying the gender of the voice

Dataset : https://www.kaggle.com/primaryobjects/voicegender

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by abhisheks008** [comment]
@prathimacode-hub I am up for this issue.
Approach : I will be using the following steps for creating the model.
1. EDA
2. Data Cleaning
3. Data Processing
4. Model Creation [LR, KNN, Decision Tree, Random Forest, Gradient Boosting, SVM]
5. Hyper Parameter Tuning
6. Accuracy Checking

- [x] DCP Participant

Task Taken : Model Creation
Issue #520

Please assign me this issue.

**Comment by abhisheks008** [comment]
I will work on this issue after #518

**Comment by abhisheks008** [comment]
@prathimacode-hub Please assign me this issue!

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
