### ISSUE TITLE
Soil Moisture Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#521]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in predicting the moisture of the soil to check if it's wet or dry

Dataset : https://www.kaggle.com/amirmohammdjalili/soil-moisture-dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , can you please assign me this

**Comment by prathimacode-hub** [comment]
Already an issue is assigned to you. @ashish-reddy-20-08
