### ISSUE TITLE
Crop Fertilizers Analysis and Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#522]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in analyzing and predicting the fertilizers needed for the specific crops

Dataset : https://www.kaggle.com/gdabhishek/fertilizer-prediction

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by akash435** [comment]
@prathimacode-hub can i work on this issue under LGM SOC

Will be working on model creation

will use different visualization graph and 

use different algorithms like
linear regression
logistic regression
decision tree regression
Random Forest classifier
K Neighbor Classifier
XG boost classifier

and compare the the accuracy among them

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
