### ISSUE TITLE
Salt Deposits Identification & Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#523]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in identifying and predicting the salt deposits beneath the earth's surface.

Dataset : https://www.kaggle.com/c/tgs-salt-identification-challenge

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by abhisheks008** [comment]
@prathimacode-hub I am up for this issue.

Approach : I will be using Convolution Neural Network architectures for creating the model and the accuracy will be judged based on the accuracy scores.

Architecture : U-net with ResNet

Issue #523
Topic : model creation

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008

**Comment by prathimacode-hub** [comment]
As DCP participant right? @abhisheks008

**Comment by abhisheks008** [comment]
Yup! DCP Participant. Sorry ma'am my bad!
