### ISSUE TITLE
Electricity Outage Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#525]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in predicting the outage of electricity using the dataset provided

Dataset : https://www.kaggle.com/autunno/15-years-of-power-outages

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , can you please assign me this

**Comment by prathimacode-hub** [comment]
Yes, issue assigned to @ashish-reddy-20-08
