### ISSUE TITLE
Barcode and QR code Recognition

### ISSUE THREAD

**Issue by vaibhavgupta2499** [prathimacode-hub/ML-ProjectKart#528]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in Recognition of Information stored through Barcode and QR Code, with the help of Python.

Barcode Dataset : https://www.kaggle.com/whoosis/barcode-detection-annotated-dataset
QRcode Dataset : https://www.kaggle.com/coledie/qr-codes

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try using different algorithms and Python libraries.

**Comment by navya-Singla-1-3-0-9** [comment]
Hey, is this issue open for hacktoberfest 2022? If yes, can you please assign this issue to me?

**Comment by adi271001** [comment]
can you please assign this to me @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned @adi271001
