### ISSUE TITLE
Covid-19 Data Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#533]
Hey peeps! This project being a very popular choice is opened again for your contributions. But you can only do the analysis that has not been done before. So, if you feel like you can bring something new to the table then show your interest and get this issue assigned to you.

This issue is again open for contributions. Here are the datasets to follow. You can choose any one of the datasets to perform COVID-19 Data Analysis.

Dataset 1 : https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge (or)

Dataset 2 : https://www.kaggle.com/imdevskp/corona-virus-report (or)

Dataset 3 : https://www.kaggle.com/sudalairajkumar/novel-corona-virus-2019-dataset

By the way, I had created a new repo of [Covid-19 Data Analysis](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Covid-19%20Data%20Analysis). In this repo, you can add up your "Full Name" as your folder title. Inside that, you can follow the project structure as usual. So that, mulitple persons can work on this issue, and their way of analysis can be differentiated by their names.

**Comment by Harish-Soni1** [comment]
Hello @prathimacode-hub, how can I contribute in this

**Comment by prathimacode-hub** [comment]
You want to contribute as part of any event or in general? @Harish-Soni1

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Can i work on this issue mam.

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. Issue assigned to @ashish-reddy-20-08

**Comment by tanvideshmukh29** [comment]
@prathimacode-hub 
I would love to contribute mam as a part of hacktoberfest2021.
Can  you assign this to me?

**Comment by dhruvkej9** [comment]
@prathimacode-hub Assign me this for hacktoberfest2022

**Comment by prathimacode-hub** [comment]
Issue assigned to @dhruvkej9
