### ISSUE TITLE
Named Entity Recognition

### ISSUE THREAD

**Issue by vaibhavgupta2499** [prathimacode-hub/ML-ProjectKart#535]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in prediction of the type of Entity a particular word represent, like Noun, Verb, et cetera.

Dataset : https://www.kaggle.com/abhinavwalia95/entity-annotated-corpus

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by seanbenhur** [comment]
Hi @vaibhavgupta2499 , I would like to work on this!

**Comment by prathimacode-hub** [comment]
You are a participant of? @seanbenhur

**Comment by seanbenhur** [comment]
I am LGMSOC21 participant

**Comment by prathimacode-hub** [comment]
Ok, issue assigned. @seanbenhur
