### ISSUE TITLE
Prediction of Subject based on Question (NLP)

### ISSUE THREAD

**Issue by vaibhavgupta2499** [prathimacode-hub/ML-ProjectKart#538]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in Prediction of Subject based on Question, for exams of IITJEE, NEET, AIIMS.

Dataset : https://www.kaggle.com/mrutyunjaybiswal/iitjee-neet-aims-students-questions-data

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different NLP algorithms..

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub I would like to work on 'Model Creation' this issue. Please assign me if possible.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Soumayan-pal01
