### ISSUE TITLE
Emotion Recognizer in Python( NLP Based ) 

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#54]
Hello!! I have an NLP-based Project Idea.
Problem staement : Emotion Recogiser 
I've been working on this already would be happy to add this project here.
Here is  a [glimpse](https://github.com/NEERAJAP2001/EmoRec) 
Please assign this issue to me so that I can start working.
Thanks

I'd Like to work on this as part of LGMSOC-21

I will work on front end + model + backend of the Project ( Fullstack )

**Comment by prathimacode-hub** [comment]
I understood your projects, you experssed your interest in . All sounds interesting. But issues should be raised only from tomorrow morning 10AM. You have should follow the templates given in README file of the project when you raise a new issue from your end. That is to know you as LGM-SOC particpant. Also make sure to check, if issue is in the list. Emotion recognizer is already in the issues list created. Issues will be assigned on first come first serve basis and only 1 task would be assigned at a time. So stay tuned. These issues created now won't be taken into consideration. Do raise a same issue, after the stipulated time. Then get it assigned to you by giving short description of how would you expect it to work. Kudos to you. All the best for your open source journey ahead. @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Thanks @prathimacode-hub for clarification.
Hope to contribute! 
Thanks

**Comment by prathimacode-hub** [comment]
You're welcome. Looking forward to your projects. I will update with the process of how to get it assigned in slack channel by today evening.👍

**Comment by prathimacode-hub** [comment]
Yeah, and when you raise a issue next time, do also mention the task you will be working on : Like Model Creation (or) Front End (or) Back End (or) Data Analysis (or) UI/UX Design along with the above mentioned details using template. @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Hey @prathimacode-hub Can I Start Working?


> I will work on front end + model + backend of the Project ( Fullstack )

This is What I will do

**Comment by prathimacode-hub** [comment]
Sure. I had assigned this task to you. All the best @NEERAJAP2001
