### ISSUE TITLE
Face Detection and Blurring

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/ML-ProjectKart#546]
Title: A project for Face Detection and Blurring  
**Name: Umesh Singh**
Label: Feature Request

Define You-
- [x] LGM-SOC'21 Participant
- [x] Contributor

### Solution For Issue:
I want to make a project for detection of face from any image and also we can apply the blurring effect on them like we see in images and videos that some part of image is blurred, but we will be using python for this project.

**Comment by prathimacode-hub** [comment]
Hmm, script is good and unique but are you using ML in this? @Umesh-01

**Comment by Umesh-01** [comment]
> Hmm, script is good and unique but are you using ML in this? @Umesh-01

yes @prathimacode-hub mam

**Comment by prathimacode-hub** [comment]
What are the libraries that would be used? @Umesh-01

**Comment by Umesh-01** [comment]
@prathimacode-hub mam it will use libraries like-
- opencv
- numpy
- matplotlib
- mtcnn
- tensorflow

**Comment by prathimacode-hub** [comment]
Ok i shall assign this issue as you are using tensor flow. @Umesh-01
