### ISSUE TITLE
Detecting Motion and Moving Objects in a Video

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/ML-ProjectKart#558]
Define You-

- [x] LGM-SOC'21 Participant
- [x] Contributor

Title:
A project for detecting motion in moving objects in a video 
**Name: Umesh Singh**
Label: Feature Request

### Solution For Issue:
I want to make a project that can help us to detect the motion of objects in videos using some libraries in python. I will be adding working instructions for the project in the readme file with some screenshots.

**Comment by Umesh-01** [comment]
@prathimacode-hub mam should I start working on this project??

**Comment by prathimacode-hub** [comment]
Can you elaborate it more? @Umesh-01

**Comment by Umesh-01** [comment]
> Can you elaborate it more? @Umesh-01

@prathimacode-hub mam I will take a video of some moving objects and then based on the position of those objects, will identify whether the object is in motion or not...

**Comment by prathimacode-hub** [comment]
Ok, but can you assure you can finish it off by tomorrow? @Umesh-01

**Comment by Umesh-01** [comment]
> Ok, but can you assure you can finish it off by tomorrow? @Umesh-01

Yes mam, I will do..
