### ISSUE TITLE
Customer Modeling Analysis

### ISSUE THREAD

**Issue by aryantiwari10** [prathimacode-hub/ML-ProjectKart#559]
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

PROJECT TITLE : Customer Modeling Analysis

GOAL : To predict about the customers modeling using ANN .

WHAT I HAD DONE : In this project first I performed a exploratory data analysis on the Customer Modeling dataset which includes of data cleaning , data manipulation, data preprocessing , data visualization and after that I did training and testing , then I did the feature scaling and used ANN for the prediction. While in the EDA part I have included different plots for the different visualizations of our dataset .

LIBRARIES:

PANDAS

NUMPY

MATPLOTLIB

SEABORN

SCIPY

SKLEARN

Keras

TensorFlow

**Comment by prathimacode-hub** [comment]
Issue assigned. @aryantiwari10
