### ISSUE TITLE
Add Face Clustering Project

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#564]
Define You:

- [x] Hacktoberfest2021 Participant 
- [ ] Contributor

Face clustering we need to perform unsupervised learning — we have only the faces themselves with no names/labels. From there we need to identify and count the number of unique people in a dataset.

As a quick breakdown, here is everything you’ll need in your Python environment:
* OpenCV
* dlib
* imutils
* scikit-learn

@prathimacode-hub I'd like to work on this.

**Comment by deepthi1107** [comment]
please do assign me

**Comment by prathimacode-hub** [comment]
Issue assigned to @NEERAJAP2001
