### ISSUE TITLE
Add Cartoonify Image using KMeans Algorithm

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#567]
Define You:

- [x] Hacktoberfest2021 Participant 
- [ ] Contributor

This project would be one of such inspirations in which cartoon images and videos using only core OpenCV filters and functions. It also will be using a K-means clustering algorithm to compress the image. This clustering gives it the basic cartoonish tinge it requires.

Algorithm- K_Means Clustering
Filters-Bilateral Filter, Contours, erode, Canny(edge detection)

I'd Like to work on this as part of Hacktoberfest-21

**Comment by prathimacode-hub** [comment]
Issue assigned to @NEERAJAP2001
