### ISSUE TITLE
Heart disease prediction

### ISSUE THREAD

**Issue by raunak51299** [prathimacode-hub/ML-ProjectKart#57]
I would like to make a model to predict heart disease using SVM and K-Nearest Neighbours techniques.
Project title would be **Heart disease prediction**
I would be using [this](https://www.kaggle.com/ronitf/heart-disease-uci) dataset.
please assign me this issue.

**Comment by prathimacode-hub** [comment]
When you raise a new issue, you should follow the template given in README file. @raunak51299

**Comment by raunak51299** [comment]
ok sorry I'm new here

**Comment by raunak51299** [comment]
---
Title: Heart disease prediction
About: I would like to make a model to predict heart disease using SVM and K-Nearest Neighbours techniques
Name: Raunak Singh
Label: Feature Request
---
 - [x] LGM-SOC'21 Participant

**Comment by prathimacode-hub** [comment]
That's ok, you're allowed to make mistakes. Create a new issue with Heart Disease Prediction now. I shall add the reference template to your new issue. You can then edit according to your project and update the comment. @raunak51299
