### ISSUE TITLE
Face Emotion Detection without a neural Network

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#572]
Define You:

- [x] Hacktoberfest2021 Participant 
- [ ] Contributor

Problem Statement :
Given a data set consisting of facial images and their sketches, retrieve all images (real and /or sketch) which are similar to the given test image, along with attributes of the image such as expression.

Non-neural network approach:
* K Nearest Neighbours (with k = 5, minkowski distance with p = 2)
* Support Vector Machine (linear kernel)
* Naive Bayes (Gaussian with variance 10^-9)
* Decision Tree
* Random Forest

**Comment by prathimacode-hub** [comment]
Issue assigned to @NEERAJAP2001

**Comment by prathimacode-hub** [comment]
By when are you expected to do? Fest is about to end? @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Thanks! But I'm still devoleping the project.
I'll come back once it's done.

**Comment by prathimacode-hub** [comment]
Why have you closed it? @NEERAJAP2001
