### ISSUE TITLE
Heart disease prediction

### ISSUE THREAD

**Issue by raunak51299** [prathimacode-hub/ML-ProjectKart#58]
---
Title: Heart disease prediction
About:  I would like to make a model to predict heart disease using SVM and K-Nearest Neighbours techniques
Name: Raunak Singh
Label: Feature Request
Assignee: 

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**<br>
I would use [this](https://www.kaggle.com/ronitf/heart-disease-uci) dataset and the use SVM and K-Nearest Neighbours techniques from sklearn module to train over the dataset .

**Comment by prathimacode-hub** [comment]
Fill this template, to get issue assigned to you. @raunak51299

**Comment by raunak51299** [comment]
done

**Comment by prathimacode-hub** [comment]
Issue is assigned to you. Go ahead. By the way, what's the task? Model Creation?

**Comment by raunak51299** [comment]
yes model creation

**Comment by 1anshu-56** [comment]
I want to work on this issue please assign it to me, Thank you!

**Comment by raunak51299** [comment]
> I want to work on this issue please assign it to me, Thank you!

I was assigned this issue and have already made pull request.

**Comment by prathimacode-hub** [comment]
> I want to work on this issue please assign it to me, Thank you!

Yes, this issue is taken, and PR is approved. @1anshu-56
