### ISSUE TITLE
CartPole Balancing using DQN

### ISSUE THREAD

**Issue by Sidhved** [prathimacode-hub/ML-ProjectKart#586]
Define You:

- [X] Hacktoberfest2021 Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**
CartPole problem is the problem of balancing the CartPole. CartPole is the structure where a pole is attached to the cart and the cart is free to slide across the frictionless surface. By sliding the cart left or right, the CartPole is balanced.

**Describe the solution you'd like...**
Using Deep Q-Network, we will simulate the Cartpole Balancing. With each iteration, the agent is rewarded/punished based on the performance until we reach maximum high score and minimum exploration rate

**Comment by Sidhved** [comment]
@prathimacode-hub on some research, I have found that I can also add Mountain Climbing as a new feature in addition to the CartPole. Can you please assign me this issue under Hacktoberfest2021?

**Comment by prathimacode-hub** [comment]
I have reviewed and suggested the changes. By when are you expected to do? Fest is about to end? @Sidhved
