### ISSUE TITLE
Brain Tumor Detection and Classification

### ISSUE THREAD

**Issue by PriyankaHotchandani** [prathimacode-hub/ML-ProjectKart#59]
As a participant of LGM-SOC'21, I would like to contribute by building a model for detection of brain tumor from MRI images of the patient and then further classify them as pituitary, glioma, or meningioma. 

The dataset to be used: https://www.kaggle.com/sartajbhuvaji/brain-tumor-classification-mri

**Comment by prathimacode-hub** [comment]
Interesting project. Kindly raise a new issue using the template mentioned in README along with short details of project and dataset to get an issue assigned to you. @PriyankaHotchandani

**Comment by PriyankaHotchandani** [comment]
---
Title: Brain Tumor Detection and Classification
About: Building a model for detection and classification of brain tumor from MRI images of the patient
Name: Priyanka Hotchandani
Label: Feature Request
Assignee: 

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
Diagnosis of brain tumors in the early stages of the tumor’s start is difficult because it cannot accurately measure the size and resolution of the tumor. Therefore, the treatment of tumor depends on the timely diagnosis of the tumor. For skilled radiologists, analysis of multimodal MRI scans can take up to 20 minutes. Since manual image feature extraction methods are very time inefficient, limited to operator experience, and are prone to human error, a reliable and fully automatic classification method using MRI data is necessary for efficient cancer detection.

**Describe the solution you'd like...**
Build a model to detect whether a brain tumor is present in a patient or not. If the presence of tumor is detected, it is then classified into ‘Glioma’, ‘Pituitary’ and ‘Meningioma’. This automated detection technique facilitates accurate, efficient and cost-effective detection of brain tumors whilst alleviating the bottleneck of limited diagnosis time for doctors. 
Dataset:  https://www.kaggle.com/sartajbhuvaji/brain-tumor-classification-mri

**Comment by prathimacode-hub** [comment]
Can you raise a new issue with the same information given here. You had explained it wonderfully. Kudos. Once you do it, I shall assign the issue. @PriyankaHotchandani

**Comment by PriyankaHotchandani** [comment]
Done, I'm sorry for the initial inconvenience.

**Comment by prathimacode-hub** [comment]
No, that's ok. That's how we learn right from our mistakes. @PriyankaHotchandani
