### ISSUE TITLE
Anime Recommendation Systems

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#596]
Hey Hacktober participants, good to see you.

This project will help us in provided appropriate recommendations using ratings provided on anime dataset.

Dataset : https://www.kaggle.com/CooperUnion/anime-recommendations-database

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to provide overall analysis using visualizations and suggest with anime recommendations based on ratings given.

**Comment by photon149** [comment]
I would like to work on the same , will provide a detailed EDA as well as apply a recommendation model to give the anime recommendations

**Comment by prathimacode-hub** [comment]
Issue assigned. Get going. @photon149
