### ISSUE TITLE
New filter into the Snapchat filters Folder

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#599]
Define You:

- [x] Hacktoberfest2022 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

I'd like to add a new filter into the Snapchat filters folder:

Filter : ( I will be using cropped version ) 
![this](https://user-images.githubusercontent.com/65017645/193595737-a52ec900-7f20-411d-bb9c-f289d191b616.png)

We, Will, be using :

* Python
* The program makes use of Dlib-facial feature points
* OpenCV
* Tkinter
* Shape predictor 68 face landmark points Model

I'd like to work on this as part of the Hacktoberfest-2022

**Comment by prathimacode-hub** [comment]
Issue assigned to @NEERAJAP2001. You can start working.
