### ISSUE TITLE
Facial Expression Recognition using ML

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#601]
Define You:

- [x] Hacktoberfest2022 Participant 
- [ ] Contributor

* Facial expression recognition software is a technology which uses biometric markers to detect emotions in human faces. 
* More precisely, this technology is a sentiment analysis tool and is able to automatically detect the six basic or universal expressions: happiness, sadness, anger, neutral,  surprise, fear, and disgust.
* Facial expressions and other gestures convey nonverbal communication cues that play an important role in interpersonal relations.

## Planning to Build With

* [Python](https://www.python.org/)
* [Jupyter Notebook](https://jupyter.org/)
* [Google Colab](https://colab.research.google.com/)

**Comment by prathimacode-hub** [comment]
Issue assigned to @NEERAJAP2001
