### ISSUE TITLE
Cat Mask Filter

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#602]
Define You:

- [x] Hacktoberfest2022 Participant 
- [ ] Contributor

I'd like to add a new filter into the Snapchat filters folder:

Filter : ( I will be using cropped version ) 
![cats](https://user-images.githubusercontent.com/65017645/193784653-7e5e0559-c527-4aec-a5eb-3ce4f3976f17.png)

We, Will, be using :

* Python
* The program makes use of Dlib-facial feature points
* OpenCV
* Tkinter
* Shape predictor 68 face landmark points Model

I'd like to work on this as part of the Hacktoberfest-2022

**Comment by prathimacode-hub** [comment]
Issue assigned to @NEERAJAP2001

**Comment by prathimacode-hub** [comment]
Update please? @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Sorry! Out of schedule!!
