### ISSUE TITLE
Face Detection using YOLO V3 - State of art algorithm

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/ML-ProjectKart#606]
Define You:
- [x] Hacktoberfest2022 Participant 
- [ ] Contributor

The YOLOv3 (You Only Look Once) is a state-of-the-art, real-time object detection algorithm. The published model recognizes 80 different objects in images and videos. For more details, you can refer to this [paper](https://pjreddie.com/media/files/papers/YOLOv3.pdf).

**Comment by prathimacode-hub** [comment]
Issue assigned. @NEERAJAP2001
