### ISSUE TITLE
Age, Gender, emotion detection with DeepFace

### ISSUE THREAD

**Issue by SoyabulIslamLincoln** [prathimacode-hub/ML-ProjectKart#61]
DeepFace is a python framework for  lightweight face recognition and facial attribute analysis (age, gender, emotion and race)  .  It is a hybrid face recognition framework wrapping state-of-the-art models: VGG-Face, Google FaceNet, OpenFace, Facebook DeepFace, DeepID, ArcFace and Dlib. 

I will build a gui that will run live video and show the age, gender adn emotion of that person.

**Comment by prathimacode-hub** [comment]
Wait, are you a LGM-SOC participant?

**Comment by prathimacode-hub** [comment]
First thing, complete the issue taken before. It's still assigned to you. @SoyabulIslamLincoln

**Comment by SoyabulIslamLincoln** [comment]
Yes. I am LGM_SOC participant. Thank you for informing me I will complete that issue before. Thank you

**Comment by prathimacode-hub** [comment]
Ha, but remember the issue you had taken earlier won't count under LGM-SOC as that issue was created before 10th June Ok? @SoyabulIslamLincoln

**Comment by SoyabulIslamLincoln** [comment]
Okay. No problem

**Comment by prathimacode-hub** [comment]
That's great. I shall assign this issue to you. As earlier issue, isn't considered in this program. @SoyabulIslamLincoln

**Comment by prathimacode-hub** [comment]
You hadn't updated anything since past 3 days, neither responded with your progress? @SoyabulIslamLincoln

**Comment by SoyabulIslamLincoln** [comment]
Going to submit by tomorrow

**Comment by prathimacode-hub** [comment]
What's the task you're working upon? I just want to know the progress. @SoyabulIslamLincoln

**Comment by SoyabulIslamLincoln** [comment]
Currently working on this issue. @prathimacode-hub ... Sorry for late reply

**Comment by prathimacode-hub** [comment]
Yes, I am asking the task. "Model Creation" or "Front End"  or "Back End"? @SoyabulIslamLincoln

**Comment by SoyabulIslamLincoln** [comment]
Back End @prathimacode-hub

**Comment by prathimacode-hub** [comment]
It's been 6 days. As said, time to complete PR is only 5 days and no update since then. I already mentioned, you should update your progress once in 2 days. @SoyabulIslamLincoln

**Comment by prathimacode-hub** [comment]
Tomorrow hasn't come yet? @SoyabulIslamLincoln

**Comment by SoyabulIslamLincoln** [comment]
Sorry @prathimacode-hub . My pc got busted . Got the pc today. Wasn't able to complete it. bOth the issues.

**Comment by prathimacode-hub** [comment]
Kindly complete this issue first, as it's the part of an open source program. @SoyabulIslamLincoln

**Comment by SoyabulIslamLincoln** [comment]
Will do. Sorry again for the delay.

**Comment by prathimacode-hub** [comment]
> Will do. Sorry again for the delay.

ok

**Comment by prathimacode-hub** [comment]
What happen? @SoyabulIslamLincoln

**Comment by prathimacode-hub** [comment]
I'll wait for 2 more days. If there is no response, i have no option than to assign it to someone else. Actually max PR time is 5 days. But u held this issue for so long. This is not right. @SoyabulIslamLincoln
