### ISSUE TITLE
KWOC 2023 : Covid-19 Data Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#615]
Define You:

- [x] KWOC 2023 Participant 
- [ ] Contributor

Hey peeps! This project being a very popular choice is opened again for your contributions. But you can only do the analysis that has not been done before. So, if you feel like you can bring something new to the table then show your interest and get this issue assigned to you.

This issue is again open for contributions. Here are the datasets to follow. You can choose any one of the datasets to perform COVID-19 Data Analysis.

Dataset 1 : https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge (or)

Dataset 2 : https://www.kaggle.com/imdevskp/corona-virus-report (or)

Dataset 3 : https://www.kaggle.com/sudalairajkumar/novel-corona-virus-2019-dataset

By the way, I had created a new repo of [Covid-19 Data Analysis](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Covid-19%20Data%20Analysis). In this repo, you can add up your "Full Name" as your folder title. Inside that, you can follow the project structure as usual. So that, mulitple persons can work on this issue, and their way of analysis can be differentiated by their names.

**Comment by mariam7084** [comment]
Please assign this issue to me. @prathimacode-hub 

Role : KWoC 2023 participant
Name : Mariam
github : [github.com/mariam7084](https://github.com/mariam7084)

**Comment by prathimacode-hub** [comment]
Issue assigned to @mariam7084. Start working.

**Comment by prathimacode-hub** [comment]
Any update? @mariam7084

**Comment by mariam7084** [comment]
Half way through the project. Will make a PR by tomorrow.

**Comment by prathimacode-hub** [comment]
Great to hear @mariam7084
