### ISSUE TITLE
KWOC 2023 : Gun Detection using YOLO

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#624]
Define You:

- [x] KWOC 2023 Participant 
- [ ] Contributor

Hey OS participants, good to see you.

This project will help us in detecting the gun using YOLO.

Dataset : https://www.kaggle.com/atulyakumar98/gundetection

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms for better modelling practices.

**Comment by Pranay38** [comment]
Please assign this issue to me. I have done a few object detection projects using the YOLO  model. I am well versed with it.

**Comment by prathimacode-hub** [comment]
Sure, go ahead. @Pranay38

**Comment by prathimacode-hub** [comment]
Use atleast 3-4 algorithms for best results. Glad to hear. @Pranay38

**Comment by prathimacode-hub** [comment]
Any update? @Pranay38

**Comment by Pranay38** [comment]
I have made a pull request please check

**Comment by Pranay38** [comment]
It's #626
