### ISSUE TITLE
KWOC 2023 : Bangladesh Premier League Model

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [prathimacode-hub/ML-ProjectKart#627]
Define You:

- [x] KWOC 2023 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
The main aim of the project to analysis the dataset by taking different crieterias into account.

**Describe the solution you'd like...**
- Analysing the dataset.
- EDA processing.
- Filtering the dataset so that which can easily fit into any type of the dataset.
- Applying the different type of the algorithms.
- Summarizing all the algorithms at the end of the notebook.

**Comment by Avdhesh-Varshney** [comment]
@prathimacode-hub please assign this project to me to contribute under KWOC

**Comment by prathimacode-hub** [comment]
Issue assigned. Go ahead. @Avdhesh-Varshney
