### ISSUE TITLE
KWOC 2023 : Body Parts Classification

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [prathimacode-hub/ML-ProjectKart#628]
Define You:

- [x] KWOC 2023 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
- Identifying the images of different body parts using ml model.

**Describe the solution you'd like...**
- Analysing the dataset.
- EDA processing.
- Filtering the dataset so that which can easily fit into any type of the dataset.
- Applying the different type of the algorithms.
- Summarizing all the algorithms at the end of the notebook.

**Comment by Avdhesh-Varshney** [comment]
@prathimacode-hub please assign this project to me to work on it and contribute in your repo under KWOC'23

**Comment by prathimacode-hub** [comment]
Issue assigned. Keep going. @Avdhesh-Varshney
