### ISSUE TITLE
OpenCV Cartoonification

### ISSUE THREAD

**Issue by Sidhved** [prathimacode-hub/ML-ProjectKart#76]
@prathimacode-hub 
Hey, I would like to work on this new project,
Cartoonification using OpenCV
It is a fun and interactive program that will create a cartoonified image of the given input image
This project can also be further worked upon to create filter for different social media platforms

Can this issue please be assigned to me under LGMSOC'21?

**Comment by prathimacode-hub** [comment]
Yes, this issue can be assigned to you. But there is a template to follow for issues and PR. Kindly follow that to get this issue assigned to you. It is know you as a LGMSOC participant. Interesting project. @Sidhved

**Comment by Sidhved** [comment]
---
Title: Animate me!
About: Create Cartoonified Image
Name: Sidhved
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor


It is a fun and interactive program that will create a cartoonified image of a given input image
I will primarily focus on model creation part
It can be further worked upon to create interesting filters for different social media platforms

@prathimacode-hub Please assign it to me under LGMSOC'21.

**Comment by prathimacode-hub** [comment]
Yeah, this issue is assigned to you. You can start working. All the best. @Sidhved
