### ISSUE TITLE
Iris Flower Classification

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#77]
Hey LGM-SoC participants, good to see you.

This project should help you in classifying the flowers based on feaures using machine learning

Dataset : https://www.kaggle.com/arshid/iris-flower-dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README.

Enjoy your open source journey!😎

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant . Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
Car Prices Prediction has been assigned to you. @harshita9621

**Comment by Sidhved** [comment]
Hi
@prathimacode-hub I would like to work on this as my next contribution under LGMSOC'21
I propose to apply 5 different classifiers and also plot a comparative graph determining the best model for the same.
Thus I would like to prioritize on Model Creation for this project.
Please assign this to me!

**Comment by prathimacode-hub** [comment]
Glad to know. Definitely, this issue is assigned to you. You can proceed. @Sidhved
