### ISSUE TITLE
Wine Quality Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#79]
Hey LGM-SoC participants, good to see you.

This project helps in predicting the wine quality using machine learning algorithms.

Dataset : https://www.kaggle.com/danielpanizzo/wine-quality

If you like to work on this issue, follow the given guidelines for code as well as for the README.

Enjoy your open source journey!😎

**Comment by Rutikab12** [comment]
Hey @prathimacode-hub I would love to work on this issue as lgmsoc participant. Please assign me if possible.

**Comment by prathimacode-hub** [comment]
Yup, definitely. Model Creation or anything else you would like to add up? @Rutikab12

**Comment by Rutikab12** [comment]
> Yup, definitely. Model Creation or anything else you would like to add up? @Rutikab12

Yes, @prathimacode-hub I would like to try a model deployment.

**Comment by prathimacode-hub** [comment]
Cool, this issue is assigned to you. You can go ahead. @Rutikab12

**Comment by Rutikab12** [comment]
Okay. Thank You !

**Comment by Rutikab12** [comment]
Hey, @prathimacode-hub Done with model creation just a few changes left. I will be making PR by tomorrow.
