### ISSUE TITLE
Customer Segmentation using ML

### ISSUE THREAD

**Issue by theanshulcode** [prathimacode-hub/ML-ProjectKart#8]
This project is related to Customer Segmentation, in which I would be using Unsupervised ML Algorithm called Clustering on the Mall Customer Dataset.

Please assign this task to me @prathimacode-hub .

**Comment by prathimacode-hub** [comment]
Yup, go ahead. Great to know. It's an interesting project. I am assigning this task to you. @theanshulcode

**Comment by theanshulcode** [comment]
Thank you @prathimacode-hub .

**Comment by prathimacode-hub** [comment]
Have you created a new PR again with this project? @theanshulcode

**Comment by theanshulcode** [comment]
No

**Comment by prathimacode-hub** [comment]
I guess you have closed that PR. Any queries, don't hesitate to ask. You can create a new PR for the project. 👍 @theanshulcode

**Comment by theanshulcode** [comment]
That PR is different, the one in which I had made a mistake.

For "Customer Segmentation using ML", I have not made any PR till now.

**Comment by prathimacode-hub** [comment]
It's been long time, you hadn't created any PR yet? @theanshulcode

**Comment by prathimacode-hub** [comment]
What happen? @theanshulcode

**Comment by prathimacode-hub** [comment]
Sorry, but I have to close this issue. It's been 25 days since you opened up an issue, no PR yet. Anyways, if u r interested to contribute in future, you can come up with new issue to work on. @theanshulcode
