### ISSUE TITLE
Breast Cancer Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#80]
Hey LGM-SoC participants, good to see you.

This project helps in predicting whether the patient who is suffering from breast cancer is benign or malignant.

Dataset : https://www.kaggle.com/uciml/breast-cancer-wisconsin-data

If you like to work on this issue, follow the given guidelines for code as well as for the README.

Enjoy your open source journey!😎

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Are you sure you want to work on this issue? As you had raised a new issue on Diabetes Prediction. @Jagannath8

**Comment by Jagannath8** [comment]
Yes mam

**Comment by prathimacode-hub** [comment]
Choose 1 out of 2 issues, and it would get assigned to you. @Jagannath8

**Comment by Jagannath8** [comment]
Okay mam, first I'll work on Breast Cancer Prediction then I'll go to Diabetes Prediction.

**Comment by prathimacode-hub** [comment]
Ok sure, This issue is assigned to you. What would be your approach to work on? @Jagannath8

**Comment by Jagannath8** [comment]
I'll use Logistic Regression algorithm to predict Breast Cancer.

**Comment by prathimacode-hub** [comment]
Ok, what's the task you're taking up? @Jagannath8

**Comment by Jagannath8** [comment]
Model creation

**Comment by prathimacode-hub** [comment]
Ok, you can proceed with your issue. This issue is allotted to you. @Jagannath8
