### ISSUE TITLE
Crop Yield Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#82]
Hey LGM-SoC participants, good to see you.

This project helps in predicting the yield of a crop based on the geography, season and area under cultivation.

Dataset : https://www.kaggle.com/santoshd3/crop-price-prediction

If you like to work on this issue, follow the given guidelines for code as well as for the README.

Enjoy your open source journey!😎

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant . Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
Yeah, you will be working on model creation? I would assign it soon once I review your pending PR. @harshita9621

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant . Do assign me if possible. Thank You!

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can start working. @harshita9621

**Comment by prathimacode-hub** [comment]
How would you work on it? What's your approach? @harshita9621

**Comment by harshita9621** [comment]
I will follow the traditional data pipe line and make a efficient out put with the data set.

**Comment by prathimacode-hub** [comment]
Ok, cool. You can proceed ahead. @harshita9621
