### ISSUE TITLE
Image Compression using Clustering

### ISSUE THREAD

**Issue by Soumayan-pal01** [prathimacode-hub/ML-ProjectKart#83]
A K-Means Clustering algorithm that compresses images by clustering the pixel values into k-clusters. 16 million color channels are converged into k-color channels. This reduces both the size and quality of the images. This algorithm will prove useful to reduce the image size if it exceeds the maximum size limit.

**Comment by Soumayan-pal01** [comment]
Please assign me this issue @prathimacode-hub .

**Comment by Soumayan-pal01** [comment]
Please assign me this issue for 'Model Creation' @prathimacode-hub .Thank you.

**Comment by prathimacode-hub** [comment]
Issue template needed. Kindly update your comment. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
---
Title: Image Compression using Clutering
About: This project is about compressing image colors into k-colors
Name: Soumayan Pal
Label: Feature Request
Assignee: 'Soumayan-pal01'

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor




**Yes I have discussed about this issue with Project admin**



**A K-Means Clustering algorithm that compresses images by clustering the pixel values into k-clusters. 16 million color channels are converged into k-color channels. This reduces both the size and quality of the images.**



**This algorithm will prove useful to reduce the image size if it exceeds the maximum size limit.**





**Mini Batch K-Means - Clustering algorithm (Unsupervised learning approach)**

**Comment by prathimacode-hub** [comment]
That sounds wonderful. Issue is alloted to you. You can go ahead. @Soumayan-pal01

**Comment by Soumayan-pal01** [comment]
Hey @prathimacode-hub I have created the PR for this issue. Please review it. Thank you.
