### ISSUE TITLE
Bike Sharing Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#85]
Hey LGM-SoC participants, good to see you.

This project helps in predicting the number of bike share users.

Dataset : https://archive.ics.uci.edu/ml/datasets/bike+sharing+dataset#

If you like to work on this issue, follow the given guidelines for code as well as for the README.

Enjoy your open source journey!😎

**Comment by queenish001** [comment]
Please assign this issue to me

**Comment by Manasi2001** [comment]
You can work on this @queenish001. But first, please let me know what you are willing to work on, 'front-end', 'back-end' or 'model creation'. Also, what all algorithms you are planning to use and the analysis you'll be performing. Then, I'll assign it to you :)

**Comment by queenish001** [comment]
I will work on Model Creation, first I will perform exploratory data analysis to visualize the dataset, and then I'll train the model by Linear Regression and Random Forest Regressor

**Comment by Manasi2001** [comment]
Good @queenish001. Assigned to you 👍🏻
