### ISSUE TITLE
Diabetes Prediction

### ISSUE THREAD

**Issue by Jagannath8** [prathimacode-hub/ML-ProjectKart#86]
I'll use Logistic Regression algorithm to implement this.
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Issue template please. @Jagannath8

**Comment by Jagannath8** [comment]
This project helps in predicting the diabetes using machine learning algorithms.

Dataset : https://www.kaggle.com/mathchi/diabetes-data-set

**Comment by suy1968** [comment]
I'm a participant of LGMSOC21, please assign me
predicting the diabetes using Ml Algo.

**Comment by prathimacode-hub** [comment]
Kindly raise a new issue of the project using the template given to get it assigned to you. @suy1968

**Comment by prathimacode-hub** [comment]
> This project helps in predicting the diabetes using machine learning algorithms.
> 
> Dataset : https://www.kaggle.com/mathchi/diabetes-data-set

You hadn't used the issue template yet and as well your PR needed changes. Kindly correct it. As you know, issues are on FCFS basis. @Jagannath8

**Comment by Jagannath8** [comment]
> This project helps in predicting the diabetes using machine learning algorithms.
> 
> Dataset : https://www.kaggle.com/mathchi/diabetes-data-set

Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
I know you're a participant of LGM SoC21. But to assign it, the issue should a template. This is not your first time I guess. @Jagannath8

**Comment by Jagannath8** [comment]
**Diabetes Prediction**

**Objective**
The main objective of this project is to predict diabetes using machine learning algorithms.

**Dataset** 
https://www.kaggle.com/mathchi/diabetes-data-set

**Comment by prathimacode-hub** [comment]
This is not the template. Kindly check out with the template given in README file of the project. @Jagannath8

**Comment by prathimacode-hub** [comment]
This is not the full template yet.🙂 Still I would assign. Next time, make sure you follow full template. @Jagannath8

**Comment by Jagannath8** [comment]
Mam, Can you give an example of full template

**Comment by prathimacode-hub** [comment]
This is the example of full template.
https://github.com/prathimacode-hub/ML-ProjectKart/blob/main/.github/issue_template/feature_request.md

Atleast adding up a soluion you have in mind is needed. @Jagannath8

**Comment by Jagannath8** [comment]
Okay mam
