### ISSUE TITLE
Adding SVM model to predict heart disease.

### ISSUE THREAD

**Issue by raunak51299** [prathimacode-hub/ML-ProjectKart#9]
I would like to work on this issue when the coding round begins for LGM SOC.

**Comment by prathimacode-hub** [comment]
Glad to know your interest. Can you mention the project title as well in this issue. So that I can keep this issue assigned to you. @raunak51299

**Comment by raunak51299** [comment]
Sure, It would be **Heart Disease prediction using SVM**.

**Comment by prathimacode-hub** [comment]
Sure. So I will assign this issue to you timely. But also do make sure to create a new issue stating the project title and what it does when contribution period starts. So that label can be assigned then. @raunak51299
