### ISSUE TITLE
US-Aviation-Industry-analysis

### ISSUE THREAD

**Issue by HitainKakkar** [prathimacode-hub/ML-ProjectKart#96]
Greetings Sir/Mam,

I would like to work on this project and contribute!!
For this I have prepared a 2 Jupyter notebook for the main code/analysis, one python file for launching and 1 datasets.
Kindly assign me this issue.
This is regarding LGMSOC.

{Description of project}
This project helps us visualize report the insights and keys results of customer reviews about various domestic airlines information about variuos customer views and sentiments (positive, negative or neutral) avialable widely on social media platforms such as twitter. It uses an excel sheet in fromat of csv files which has a report of tweets from US metioned about the various airlines. It uses various libraries such as visualization library like pyplot to create data visualization, Streamlit’s open-source app framework to web apps and other libararies such as pandas to analyse and manupilate data. It has an interactive dashboard to with key results (negative, positive or neutral)to look for relavent data acc to reqiurement and select visualizations i.e bar plot, pie chart that appeal most to the user. Also the dashboard helps the user to locate from which part of country user tweeted from. It also has the option to see the word cloud of sentiments of people.

**Comment by Manasi2001** [comment]
Hey @HitainKakkar, this project sounds really awesome too. But, you can work on only 1 project at a time. Once you complete the other one, I'll assign it to you as a 'frontend' one. 👍🏻

**Comment by HitainKakkar** [comment]
Sure!!
Kindly Assign me this project!!

**Comment by prathimacode-hub** [comment]
Yes, this issues is assigned to you. So you will doing frontend and model creation? @HitainKakkar

**Comment by HitainKakkar** [comment]
I will be doing Model Creation/ Backend.

**Comment by HitainKakkar** [comment]
Kindly assign this issue a level , so that it can be considered for scoring in LGMSOC.
Thank you!!

**Comment by prathimacode-hub** [comment]
Ok, that's cool. Level would be assigned only after PR is reviewed. LGMSOC label has already been tagged for this issue. @HitainKakkar

**Comment by prathimacode-hub** [comment]
It's been more than 4 days. No update from you about your progress. It's already mentioned, that you'have to update once in 2 days. @HitainKakkar

**Comment by HitainKakkar** [comment]
Sorry for the delay!!
Actually my exam are going on!!
So I was busy with them!!
I will make sure that the PR is made today evening.

**Comment by prathimacode-hub** [comment]
That's ok. No issue. If you inform, it would help us in getting notified. @HitainKakkar

**Comment by HitainKakkar** [comment]
Sorry, but I lost my jupyter notebook file with the analysis of the data for this project.
So I am closing this issue.
Will soon make a new file and contribute.
Thank you for your patience.

**Comment by prathimacode-hub** [comment]
You should never close a PR or issue from your end, That's ok. It's upto you. @HitainKakkar

**Comment by HitainKakkar** [comment]
Will keep in mind next time.
